### ISSUE TITLE
feature: add NanCallback::IsEmpty()

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/nan#104]
It's not really possible right now to find out if a callback has been assigned.  Suggestion: add a `bool NanCallback::IsEmpty() const` method

I say 'not really' because while in theory you can do `nan_callback->GetFunction()->IsFunction()`, that will assert in debug builds because of the cast from Undefined to Function.

**Comment by Dzenly** [comment]
Node 0.12.7, NAN 2.1.0.

I passed a number instead of function to my module function.
(intentionaly, because I write unit tests for my module).

In С++ function I have:
```
Callback *callback = new Callback(info[0].As<Function>());
```
And ```callback->IsEmpty()``` returned false.

Then, at ```callback->call()``` my module is silently crashed.

Am I wrongly thought that IsEmpty can check if there is a really callback?

**Comment by bnoordhuis** [comment]
@Dzenly From your description it sounds like either `info[0]` was not a function, or you're doing something undefined like invoking `callback->Call()` from a different thread.  Not enough information to say for sure, though.

**Comment by agnat** [comment]
`IsEmpty()` only checks if the handle is empty. Since you deliberately assigned a number, the handle is not empty but its not a function either. `.As<Function>()` says "do it anyway" and you got to make sure things actually add up in the end.

**Comment by Dzenly** [comment]
Ok, for now I will believe that Nan::Callback does not allow to check function correctness. And I will use callback->GetFunction()->IsFunction().

**Comment by bnoordhuis** [comment]
@Dzenly Next time, try compiling a debug build of node.js (`./configure --debug`) and your add-on (`node-gyp --debug`), that catches the error immediately when you do `.As<Function>()` on something that's not a function.

**Comment by Dzenly** [comment]
@bnoordhuis Thank you.
I really believe that it is good practice to use asserts at debugging,
but I can not force users of my module to use debug node version at development,
so I added ```callback->GetFunction()->IsFunction()``` with appropriate Exception, and it seems to handle everything as I wish.
I will take your advice into account.
