### ISSUE TITLE
NAN 2 Discussion

### ISSUE THREAD

**Issue by rvagg** [nodejs/nan#208]
Just a place for putting ideas of things that we might want to break. I don't believe we should invest too much in this and make it a big deal, the more we put in here the longer it'll take and more painful it will be. I think we should just embrace a more rapid release model and not treat a 2.0.0 as a particularly big deal. Regardless, there still needs to be breakage to fix and improve things so put them in here!

Something I'd like us to think about for some point in the future (probably not v2) is making Isolates first-class in NAN so that we're not dealing with a lowest-common-denominator API. Perhaps we introduce a `NanIsolate` that's a placeholder for pre-0.11 but a real Isolate after that. Then we could require it everywhere V8 needs now but just ignore it in older versions. The point of this would be to make way for code that wants to use Isolates in a more sophisticated way, even though it'd be unlikely you could do that with code that supports pre-0.11 code you'd still be able to use NAN for the additional sugar and helpers and we'd set NAN up better for supporting future versions of V8.

**Comment by kkoopa** [comment]
Closing in favor of #334.
