### ISSUE TITLE
V8 4.4 to remove indexed properties via external data

### ISSUE THREAD

**Issue by kkoopa** [nodejs/nan#316]
https://github.com/iojs/io.js/issues/1451

How to solve this in NAN?

**Comment by kkoopa** [comment]
What about updating https://github.com/joyent/node/blob/v0.10.38/src/v8_typed_array.cc to conform with the final spec and creating wrapper functions that use this for old versions and v8's own implementation for new versions?

**Comment by kkoopa** [comment]
@trevnorris What's the status of `Buffer` for io.js 3.0? Do you have anything that works with nodejs/next? Have you settled on an external API? What's what? The new `Buffer` API is the only major thing holding off NAN 2.0.

**Comment by trevnorris** [comment]
@kkoopa I don't have an implementation complete, but my preliminary research shows that we should be able to keep the current C++ `Buffer` implementation as it is. Despite all the internal changes that we'll have to make. There is one difference in that there will no longer exist the upper limit of `0x3fffffff` starting with 4.4 IIRC. But that shouldn't pose any problem.

Maintaining the same JS API has yet to be determined, but I don't believe that affects this.

**Comment by kkoopa** [comment]
OK, that's good, I think. I don't care about the JS API. The question remains whether to backport typed arrays or not. Buffer should suffice, shouldn't it? That would mean addons neither set external array data nor use typed arrays. Does Buffer handle all those cases efficiently?

**Comment by trevnorris** [comment]
@kkoopa Buffer does contain all the necessary APIs to create objects with a backing store of external memory. Either new, or from an existing allocation. So you shouldn't need to backport either the external array data or the array buffer APIs.

**Comment by kkoopa** [comment]
That is very good. Less work for me. Then I'll close this issue, as there is nothing left to do.
