### ISSUE TITLE
[news test] NanNew<RegExp>("foo", kNone) is not /foo/g ?

### ISSUE THREAD

**Issue by kapouer** [nodejs/nan#352]
Hi,
the "news" test fails here (nodejs 0.10.33 with old v8 3.14) and just returns /foo/ not /foo/g.
https://github.com/nodejs/nan/blob/master/test/cpp/news.cpp#L87
https://github.com/nodejs/nan/blob/master/test/js/news-test.js#L54

is this failing for you too ?

**Comment by kkoopa** [comment]
[No](https://travis-ci.org/nodejs/nan/jobs/62850355), but we use node 0.10.38.

**Comment by bnoordhuis** [comment]
That's odd, actually.  I would expect it to fail because the kGlobal is not set.

**Comment by kapouer** [comment]
did i say 33 ? i meant 38. I must mention, to be honest, that i'm using the debian one - the one using a mostly non-patched v8 3.14.5.

**Comment by kkoopa** [comment]
It has always passed on every version tested since it was first created. Currently, we test the latest versions of 0.8, 0.10, 0.12, 1 and 2. The `kGlobal` flag has never been set. bf3f00539947cb939a5d68dcf17274358a598a0e

**Comment by kkoopa** [comment]
@kapouer Can you try master and see if tests pass? Reopen if not.

**Comment by kapouer** [comment]
Yes tests do pass now with https://github.com/nodejs/nan/commit/5729a46247261db5804d62940ce82c7bb4a4e898, thank you.

**Comment by kkoopa** [comment]
Ok, I might as well release 1.9.0 now then.
