### ISSUE TITLE
Callback with DWORD and recommendation for while(1) loops?

### ISSUE THREAD

**Issue by dubcanada** [nodejs/nan#361]
I am trying to get a NaN module working and I have it all working but one part, it's a read which reads a i/o card constantly and returns what it says

I have the following...

	NAN_METHOD(moxa_read) {
		NanScope();
		
		v8::Local<v8::Function> callbackHandle = args[0].As<v8::Function>();
		
		int iRet;
		int	iHandle;
		BYTE bytStartChannel = 0;
		BYTE bytCount = 8;
		DWORD dwValue[16] = {'\0'};
		
		while(1)
		{
			bytStartChannel = 0;
			bytCount = 8;
			
			iRet = E1K_DI_Reads(iHandle, bytStartChannel, bytCount, dwValue);
			
			NanMakeCallback(NanGetCurrentContext()->Global(), callbackHandle, 0, dwValue[0]);
		}

		NanReturnUndefined();
	}

But I can't figure out how to return a DWORD, I need to cast it to a `v8::Handle(v8::Value)` according to what it says. `error: invalid conversion from ‘unsigned int’ to ‘v8::Handle<v8::Value>*’`. But I can't seem to find any examples on how to convert it properly.

Also is there a better way to do this in NaN, the while loop and read inside that is?

**Comment by kkoopa** [comment]
Using `uv_timer` or `uv_poll` would be better.
A `DWORD`is just a 32-bit unsigned integer. `NanMakeCallback(NanGetCurrentContext()->Global(), callbackHandle, 1, NanNew(dwValue[0]));` should work.

**Comment by dubcanada** [comment]
Yah I tried that and kept getting a ` error: no matching function for call to ‘NanMakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>&, int, NanIntern::FactoryBase<v8::Uint32>::return_t)’`

I will investigate `uv_timer` and `uv_poll` thanks.

**Comment by kkoopa** [comment]
The error is that the last argument to `NanMakeCallback` should be a pointer.
v8::Local<v8::Value> v = NanNew(dwValue[0]);
`NanMakeCallback(NanGetCurrentContext()->Global(), callbackHandle, 1, &v);`
