### ISSUE TITLE
Release proposal: 1.9

### ISSUE THREAD

**Issue by kkoopa** [nodejs/nan#365]
Let's get this out before io.js 3.0 is out, so the 1-series can be laid to rest. There will be no more features added to NAN 1 ever.

Only sort of open issue is https://github.com/nodejs/nan/issues/362, but I believe it might be erroneous somehow since all our tests pass and the code is rather straightforward. If it is real it can be fixed in a patch release.

**Comment by rvagg** [comment]
:thumbsup: what's the delta between 1.8.4 and this?

**Comment by kkoopa** [comment]
Insignificant, IIRC. A couple deprecations, some small additions. The deprecations could even be undone. So much will change that a migratory path through deprecations won't work. There would be hardly any non-deprecated functionality left.

Basically just to tie up a few loose ends and say goodbye to NAN 1.

**Comment by kkoopa** [comment]
To clarify, here are the (significant) commits:

Added `NanFatalException` 81d4a2c0e04fab2ec4a48bdd776b722077de94be

Introduce and use macros for disallowing assign, copy and move 3357130aa844ec795471743c025d0dd399bbf855

Prohibit moving non-copyable classes fba4a299d18ce2f81f76f49ae41e3e43ab875c21

Disallow assign, copy and move in `_NanWeakCallbackInfo` c96d9b206103f4122059c99530ecac2872d2a56c

Disallow assign, copy and move in `NanCallback` 4b808cbfba50322202e8f976fa6d494e00f81714

Disallow assign, copy and move in `NanAsyncWorker` 1f55c595d817ee9aa204fb6327fbc7c875b5ef9e

Allow `NanReturnValue(Persistent<T>)` 915f1553281ec46a47f5782e074ad5217eafe68d
In NAN 2.0, the equivalent will only work for `Global`s (previously known as `UniquePersistent`s) due to upcoming changes in V8 4.5.

Deprecate `NanGetPointerSafe` and `NanSetPointerSafe` 3e60290a31d7d650b9f46a846da5d42be98b7cb8

Deprecate `NanBooleanOptionValue` and `NanUInt32OptionValue` 0ad254b48668728f9cd738c377ae609bf2808f02

Added more error types and made them all accept `Handle<String>` as arguments 4265f06c880f9c166716c45b0aed05a90452f49d
Needs doc update to list new error types.

Additionally, these could be backported from 'next':

Added indexed `GetFromPersistent` and `SaveToPersistent` 540d00d54f1b870e7d55e7c8e2e03dcbc6eb88a3

Added `SaveToPersistent(Handle<String>, ...)` and `GetFromPersistent(Handle<String>)`
9891b2fe3479f07b81ad7a4f59909d465e93abb2

Added more tests for `SaveToPersistent` and `GetFromPersistent` 872f105b0fdacbee13e5507480a3671ce5b39c09

**Comment by rvagg** [comment]
great, looks like a changelog entry to me! do eeet!

**Comment by kkoopa** [comment]
I'll probably have time today, yes. Think I'll do the backports too. That takes slightly longer.

**Comment by sam-github** [comment]
Also added is https://github.com/nodejs/nan/commit/dd87d9e9280cdf27488377b7d6a8cc1d6bd1a34d, which I've been waiting to hit a release for https://github.com/baudehlo/node-fs-ext/pull/48

**Comment by kkoopa** [comment]
1.9.0 is already released and this is mentioned in the [changelog](https://github.com/nodejs/nan/blob/v1.9.0/CHANGELOG.md).

**Comment by sam-github** [comment]
ah, great, thank you.
