### ISSUE TITLE
NanNew doesn't work with promise resolvers

### ISSUE THREAD

**Issue by Venemo** [nodejs/nan#366]
The following line of code doesn't compile:

```cpp
::v8::Local<::v8::Promise::Resolver> promiseResolver = NanNew<::v8::Promise::Resolver>();
```

Not sure if I'm doing something wrong or Nan simply doesn't support this use case.
According to [the docs][1], `::v8::Promise::Resolver` should be equally as easy to construct as any other object.

[1] https://v8docs.nodesource.com/node-0.12/d5/d76/classv8_1_1_promise_1_1_resolver.html

**Comment by Venemo** [comment]
The compile error is the following:

```
../node_modules/nan/nan_new.h:245:1: note: candidate: template<class T, class A2> typename NanIntern::Factory<T>::return_t NanNew(NanFunctionCallback, v8::Handle<v8::Value>, A2)
 NanNew( NanFunctionCallback callback
 ^
../node_modules/nan/nan_new.h:245:1: note:   template argument deduction/substitution failed:
../node_modules/nan/nan_new.h: In substitution of ‘template<class T, class A2> typename NanIntern::Factory<T>::return_t NanNew(NanFunctionCallback, v8::Handle<v8::Value>, A2) [with T = v8::Promise::Resolver; A2 = <missing>]’:
../src/misc.h:244:96:   required from here
../node_modules/nan/nan_new.h:245:1: error: invalid use of incomplete type ‘struct NanIntern::Factory<v8::Promise::Resolver>’
In file included from ../node_modules/nan/nan.h:82:0,
                 from ../src/database-wrap.h:36,
                 from ../src/database-wrap.cpp:30:
../node_modules/nan/nan_new.h:43:30: note: declaration of ‘struct NanIntern::Factory<v8::Promise::Resolver>’
 template <typename T> struct Factory;
                              ^
```

**Comment by kkoopa** [comment]
There's no support for ES 6 features. If it's not doable on Node 0.8, it is likely not doable with NAN. You have to use raw V8 for these parts.

**Comment by Venemo** [comment]
Oh, I see your point. There are no promises in the V8 version of Node 0.8 and 0.10 either. Sorry for opening this issue then! :)

**Comment by kkoopa** [comment]
No problem. Just use `Promise::Resolver::New` directly. Do not that its signature has changed in V8 4.3 to return a `MaybeLocal<Resolver>`, so you'll have to do conditional compilation if you want to support that.

**Comment by bnoordhuis** [comment]
Is there a reason we can't add a v0.12+-only overload for NanNew?  I suppose the biggest issue is that the C++ Promise API is still experimental-ish and going through some changes because of the Local/MaybeLocal switch.

**Comment by kkoopa** [comment]
Only major reason is that I like to keep the API uniform. In time, as interest grows and fewer use 0.8 or 0.10, I imagine this can be loosened, but I don't want a torrent of inane issues about that kind of functionality not being available on some old version.

**Comment by Venemo** [comment]
I was personally thinking about creating a custom, promise-like object for use in versions < 0.12 - do you think such a thing would be welcome in Nan?

**Comment by kkoopa** [comment]
Only if it is a working port of V8's promises, with the same API, the same 
features and consistent behavior on all supported platforms. That will be a 
ton of work if it works at all.

If you were thinking of something more lightweight, you're probably better off 
writing an addon offering the intended functionality.

**Comment by Venemo** [comment]
Hm. There is one more thing I'm not sure about: performance-wise, is it worth the effort to pursue promises on the C++ side, or is it equally as good if I just choose a JavaScript-based promise library (`Q` or `kew` come to mind) and write a JS wrapper around my C++ add-on?

**Comment by kkoopa** [comment]
Each transition between C++ and javascript has a fixed cost, so if you do work 
that requires less time than this, it will be faster to run it in javascript. 
V8's promise implementation has not yet been optimized for performance, which 
is why bluebird beats it in tests. You're probably better off doing the 
promises in JavaScript. It will at least be much easier to get it right.

**Comment by jokeyrhyme** [comment]
These benchmarks are totally contrived, but it looks Lie could be faster than Bluebird (and both still completely smash V8):

- http://jsperf.com/promise-comparisons/155
- https://github.com/calvinmetcalf/lie

**Comment by Venemo** [comment]
@jokeyrhyme What do you mean, contrived? Btw, I've found this comparison: http://complexitymaze.com/2014/03/03/javascript-promises-a-comparison-of-libraries/ - according to this guy, lie, q and bluebird are in the middle and kew is the fastest.

**Comment by jokeyrhyme** [comment]
@Venemo nice comparison, especially in terms of features and size, although the benchmark (actually an older version of the one I linked) uses old versions of these libraries. By "contrived", I mean the jsPerf is a bit unrealistic: it just immediately resolves Promises with no work, no errors, no chaining, no `.all()`ing, etc.

**Comment by Venemo** [comment]
@jokeyrhyme To be honest, I agree and don't think these benchmarks have any actual meaning in real-world applications (which are more likely to be I/O bottlenecked), but it never hurts to look around to find the most performant choice. :) Your link doesn't contain a benchmark for kew, btw.
