### ISSUE TITLE
Better documentation for passing values to Execute in NanAsyncWorker

### ISSUE THREAD

**Issue by LinusU** [nodejs/nan#374]
I'm having a really hard time trying to figure out what the best practices is for passing values between threads when using `NanAsyncWorker`. It would be great if we could expand the documentation for this a  bit, especially for passing strings and custom structs.

Currently I'm doing this to pass strings but I'm not 100% sure that it's correct. Am I using memory that is deallocated?

```c++
class CaptureWindowWorker : public NanAsyncWorker {
public:
  CaptureWindowWorker (v8::Local<v8::Value> bundle, NanCallback *callback)
    : NanAsyncWorker(callback), bundle(bundle) {}
  ~CaptureWindowWorker () {}

  void Execute () {
    NSString *nsBundle = [NSString stringWithUTF8String: *bundle];

    // ...
  }

  void HandleOKCallback () {
    NanScope();

    v8::Local<v8::Value> argv[] = { NanNull(), NanNew(*bundle) };
    callback->Call(2, argv);
  }

private:
  NanUtf8String bundle;
};

NAN_METHOD(capture_window) {
  NanScope();

  NanCallback *cb = new NanCallback(args[1].As<v8::Function>());
  NanAsyncQueueWorker(new CaptureWindowWorker(args[0], cb));

  NanReturnUndefined();
}
```

Full project here: [LinusU/node-capture-window](https://github.com/LinusU/node-capture-window).

**Comment by kkoopa** [comment]
What you pasted looks correct. `NanAsyncQueueWorker` ensures that the provided worker is deleted after it has executed. Essentially it all comes down to subclassing `NanAsyncWorker` to add on additional data members to access from the `Execute` method. Strings, structs, whatever are all handled the same way.
