### ISSUE TITLE
Is it possible to wrap Windows RegisterDeviceNotification in a NanAsyncWorker?

### ISSUE THREAD

**Issue by opensourcegeek** [nodejs/nan#375]
I have a library that does device discovery in windows, the core of that library relies on the RegisterDeviceNotification function. To execute that function you create a dummy window so that windows can push message to this window when there's new device or when a device is removed. I'd like to use this functionality in node - I've been writing some basic addons using nan  and I'm starting to get the hang of it. 

So for my problem, I could make a call from node api which initializes the window creation and setting up device notifications in a synchronous call and then use NanAsyncWorker to wait for windows to tell me when devices are added or removed and then run NanCallback perhaps to pass the message to node. I'm not sure if this approach is right though. I've just started using nan so any pointers or directions would be appreciated. Thanks.

**Comment by bnoordhuis** [comment]
Going by your description, I think the answer is 'no'.

A thread may be the right solution but NanAsyncWorker probably is not.  It runs tasks in a shared thread pool and is really only intended for things that only take a brief time to complete.

By the sound of it, `RegisterDeviceNotification()` is something that runs indefinitely.  Use `uv_thread_create()` for that.

**Comment by springmeyer** [comment]
> It runs tasks in a shared thread pool and is really only intended for things that take a brief time to complete.

@bnoordhuis this comment reminded me of a question I've long been wondering about but have yet to understand/track down in the libuv code. If `process.exit` is called from JS will node wait to fully exit until all work currently in the threadpool is finished? It seems like the answer to this is no from my experience, but I'm curious if this behavior is well defined.

**Comment by bnoordhuis** [comment]
@springmeyer The answer is actually 'yes', although [not everyone is pleased by that](https://github.com/libuv/libuv/issues/203).

**Comment by opensourcegeek** [comment]
@bnoordhuis thanks - RegisterDeviceNotification runs indefinitely, you're right. I'll look into uv_thread_create() then.

**Comment by opensourcegeek** [comment]
Are there any examples to do this using nan with uv_thread_create? I cannot seem to escape GC in V8, my pointer to callback function is always empty as soon as I leave the function which calls uv_thread_create - I was hoping to expose a JS api which looks like addon.DeviceDiscoverer(deviceAddedCallback, deviceRemovedCallback); but I can't seem to persist reference to callback functions.

**Comment by opensourcegeek** [comment]
Is it possible to send NanCallback through to another thread and get it back in main thread again? Below is my code 
```c++
#include <nan.h>
#include <random>

#include <uv.h>

uv_loop_t *loop;
uv_async_t async;

using namespace v8;


struct RequestBaton {
public:
	int size;
	double percentage;
	NanCallback *cb;
	
};


void fake_download(void *arg) {
	RequestBaton *req = (RequestBaton*)arg;
	//int size = req.size;
	int size = 10240;
	// init result baton
	int downloaded = 0;
	double percentage;

	while (downloaded < size) {
		percentage = downloaded*100.0 / size;
		req->percentage = percentage;

		async.data = (void*)&req;
		uv_async_send(&async);

		Sleep(60000);
		downloaded += (200 + rand()) % 1000; // can only download max 1000bytes/sec,
		// but at least a 200;
	}
}


void print_progress(uv_async_t *handle) {
	NanScope();
	RequestBaton *res = (RequestBaton*)handle->data;
	double percentage = res->percentage;
	//Local<Function> *cb = res.callback;

	//fprintf(stderr, "Downloaded %.2f%%\n", percentage);
	Handle<Value> argv[] = {
		NanNew<Number>(percentage)
	};
	//Persistent<Function, CopyablePersistentTraits<Function>> cb = res->callback;
	//Function *fn = static_cast<Function*>(res->fn);
	//Local<Function> callback = Local<Function>::New(isolate, *(res->callback));
	//bool is_empty = res->callback->IsEmpty();
	//bool empty = cb->IsEmpty();
	//fn->Call(isolate->GetCurrentContext()->Global(), 1, argv);
	//fn->Call(isolate->GetCurrentContext()->Global(), 1, argv);
	res->cb->Call(1, argv);
}


NAN_METHOD(DeviceDiscoverer) {
	NanScope();
	int size = 10240;
	
	RequestBaton req;
	req.size = size;
		
	Local<Function> fn = args[0].As<Function>();
	
	NanCallback *callback = new NanCallback(fn);

	Handle<Value> argv[] = {
		NanNew<Number>(24.11)
	};

	callback->Call(1, argv);

	loop = uv_default_loop();
	uv_thread_t download_id;

	req.cb = callback;
	
	//bool is_empty = req.callback->IsEmpty();
	uv_async_init(loop, &async, print_progress);
	////uv_queue_work(loop, &req, fake_download, after);
	uv_thread_create(&download_id, fake_download, &req);

	NanReturnUndefined();
}

NAN_METHOD(SayHello) {
	NanScope();

	NanReturnValue(NanNew<String>
		("No hello -- Booyakasha"));
}

void Init(Handle<Object> exports) {
	exports->Set(NanNew<String>("hello"), 
		NanNew<FunctionTemplate>(SayHello)->GetFunction());

	exports->Set(NanNew<String>("DeviceDiscoverer"),
		NanNew<FunctionTemplate>(DeviceDiscoverer)->GetFunction());
}



NODE_MODULE(simples, Init);
```
I'm wondering how I can pass the function received in NAN_METHOD into print_progress which is called asynchronously by another thread. I can use uv_thread_create approach without using any V8 functions/types. I'm quite new to V8 so any pointers would be very useful. And apologies for using github for asking queries, I couldn't find a mailing list or IRC channel to ping my questions. Thanks.

**Comment by jonjow** [comment]
@opensourcegeek did you develop a solution for this? I have USB detection working on Windows using a hidden CreateWindow and uv_thread_create and libudev on Linux. I would now like to poll these events in with libuv without a thread if possible.

**Comment by opensourcegeek** [comment]
@jonjow https://github.com/Axivity/openmovement-axsys-server/blob/ad6e028286a5c5ea556a7e075f33c9f09566740f/addons/NodeAddonForDeviceFinder.cpp#L238 It was 5 years ago, so I don't remember all the details of it off top of my head but I did get it to work on Windows and Linux.

**Comment by jonjow** [comment]
@opensourcegeek lovely stuff, thanks for the share!
