### ISSUE TITLE
NanAsyncworker and mutex

### ISSUE THREAD

**Issue by mathiask88** [nodejs/nan#377]
I don't know if this is an issue or if it is even related to NAN, but I want to make sure I use NanAsyncWorker and mutex lock right.
```
native_addon_function()
=> native_addon_function()
  ->....
  ->NanAsyncQueueWorker()
=> Worker::Execute()
  ->uv_mutex_lock()
  ->blocking_function_that_cant_be_run_more_than_once_per_instance()
=> Worker::HandleOKCallback()
  ->....
  ->uv_mutex_unlock()
```

This works fine for iojs, 0.12 and 0.10 but SIGABRT on 0.8(and oddly on 0.10 for OSX) at `uv_mutex_lock/unlock`. Any suggestions?

**Comment by bnoordhuis** [comment]
You're locking the mutex on one thread and unlocking it on another?  That's undefined behavior; if it works with newer versions, it's probably more by accident than anything else.

**Comment by mathiask88** [comment]
Ah ok so `Execute` is in the new worker thread and `HandleOkCallback` on the old thread? Ok then this is really wrong. Should be resolved by moving `uv_mutex_unlock()` after `blocking_function_that_cant_be_run_more_than_once_per_instance()`?

**Comment by bnoordhuis** [comment]
Yes, that should work.
