### ISSUE TITLE
Get rid of all uses of Handle

### ISSUE THREAD

**Issue by kkoopa** [nodejs/nan#380]
The `Handle`class is deprecated and should be removed. There are two ways of resolving this: Doing it for all Node versions or only doing it for new versions. I prefer the first option, but it might entail slightly more work, as all faulty APIs in Node and V8 need wrapping and converting. It should, however, result in cleaner code in the end.

**Comment by rvagg** [comment]
What is this going to mean for NAN users? are we going to have to provide a `Nan::Local` that does everything needed in all situations? And is this going to hold up v2 progress?

**Comment by kkoopa** [comment]
Local does everything needed. Just forget Handle ever existed. It need not cause a delay if the documentation is changed and we consider documented API as the real API and not whatever might accidentally compile.

For the past two years I've kept every NAN function outputting Local but accepting Handle as input. The major concern is that this change can cause some minor inconvenience in old versions.

**Comment by kkoopa** [comment]
It will still be necessary to divide into different versions due to all Node APIs using those awful Handles, like the init function of every addon. I don't know what the best solution actually is, but the change has been known and coming for almost two years.

It's actually quite good timing of V8 to start forcing it now, as we have a new major planned, but that is just luck. How come Node hasn't prepared for any of this in the past two years? It seems like there has been a general trend of postponing necessary changes until everything comes at once. I hope the new practice of next and nextnext branches will help alleviate the general issue of waiting until everything is on fire before starting to put out the flames.

https://github.com/nodejs/io.js/pull/2202

**Comment by kkoopa** [comment]
This ought to be (badly) handled by e6c0daf75966332771fe87e8574597945c3e87c0.
Haven't tested on V8 4.5.
