### ISSUE TITLE
NAN_PROPERTY_SETTER signature mismatch

### ISSUE THREAD

**Issue by DuBistKomisch** [nodejs/nan#381]
Hi, I'm developing a native extension in Node 0.12.7 (from NodeSource PPA on Debian Jessie) using nan 0.8.4. I get the following error when trying to use `NAN_PROPERTY_SETTER` with `SetAccessor`:

```
error: invalid conversion from ‘void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<v8::Value>&)’ to ‘v8::AccessorSetterCallback {aka void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)}’ [-fpermissive]
```

The relevant code is:

```
// VideoPlayer.h:
class VideoPlayer : public node::ObjectWrap
[...]
static NAN_PROPERTY_GETTER(GetPosition);
static NAN_PROPERTY_SETTER(SetPosition);

// VideoPlayer.cpp:
Local<FunctionTemplate> tpl = NanNew<FunctionTemplate>(New);
[...]
tpl->InstanceTemplate()->SetAccessor(NanNew<String>("position"), GetPosition, SetPosition);
```

The getter works fine, and I have other properties which only have a getter and no setter which work fine. If I manually define the method signature as the error says, it compiles and works, so this seems to be a bug in nan.

**Comment by kkoopa** [comment]
#382 should be correct.

**Comment by kkoopa** [comment]
Actually, something fishy is going on here. There are so many similarly named things. NAN_PROPERTY_SETTER is a named property setter and the original signature appears correct for that. I need to investigate this some more.

**Comment by kkoopa** [comment]
Your code is wrong (probably due to bad documentation on my part). You should use `NAN_SETTER` and `NAN_GETTER`, they are [accessor callbacks](https://developers.google.com/v8/embed#accesssors), for use with `SetAccessor`.

`NAN_PROPERTY_GETTER` and `NAN_PROPERTY_SETTER` are [named property interceptor callbacks](https://developers.google.com/v8/embed#interceptors), for use with `SetNamedPropertyHandler`.

`NAN_INDEX_GETTER` and `NAN_INDEX_SETTER` are [indexed property interceptor callbacks](https://developers.google.com/v8/embed#interceptors), for use with `SetIndexedPropertyHandler`.

**Comment by DuBistKomisch** [comment]
Ah, that makes a lot of sense. Thanks!

Yeah, I struggled to find many examples of getters and setters, and whatever getter example I found used `NAN_PROPERTY_GETTER` with `SetAccessor`, which "worked" since the signatures happen to be identical. I just extrapolated to `NAN_PROPERTY_SETTER` which as we know didn't work. In hindsight the embedder's guide explains the distinctions pretty well, so even just adding those links to the documentation for those macros should be very helpful.

**Comment by kkoopa** [comment]
The documentation is [getting a rewrite](https://github.com/nodejs/nan/pull/371) for the next major version of NAN. I'll make sure to address this as well. It also comes with [an updated test suite](https://github.com/nodejs/nan/blob/next/test/cpp/accessors.cpp) that should serve as a future example.
