### ISSUE TITLE
Inconsistent use of `inline` vs `NAN_INLINE`

### ISSUE THREAD

**Issue by rvagg** [nodejs/nan#384]
On `next` I'm noticing this inconsistency, perhaps it's intentional, I don't know.

```
$ grep 'NAN_INLINE ' *.h | wc
    268    1395   17343
$ grep 'inline ' *.h | wc
    141     943    9744
```

Doesn't `NAN_INLINE` exist to provide better cross-platform inlining or is it simply for older compilers?

**Comment by kkoopa** [comment]
Micro-optimization which might or might not be good. It's modeled on V8_INLINE. No real difference in practice. @agnat does not like it, so his code does not use it.

**Comment by kkoopa** [comment]
Micro-optimization here and there, can be worse too. There is not much difference.
