### ISSUE TITLE
Question: How to Nan::New v8::Value ?

### ISSUE THREAD

**Issue by saper** [nodejs/nan#401]
Old (nan 1.8) code:
````c++
v8::Handle<v8::Value> val;
v8::Local<v8::Value> returned_value = NanNew(val);
````

I have tried `Nan::New<v8::Value>(val)` but this fails (also when assigning to `Nan::MaybeLocal<v8::Value>`):

````
../src/custom_importer_bridge.cpp:9:41: error: no matching function
      for call to 'New'
  v8::Local<v8::Value> returned_value = Nan::New(val);
                                        ^~~~~~~~
````

Full error message from clang:

https://gist.github.com/8d075b06456b38d2c70d

Original piece of code in node-sass: https://github.com/sass/node-sass/blob/34db870992bcae17de30dd0e1f0fd8ddb4bcc363/src/custom_importer_bridge.cpp#L5-L9

Is there some other way? Or is this totally incorrect and I don't need to introduce in into the local scope so  that this is enough?

````cpp
v8::Local<v8::Value> returned_value = val;
````

**Comment by thejinx0r** [comment]
see #391 

`v8::Local<v8::Value> returned_value = Nan::New(val).ToLocalChecked();`

The `ToLocalChecked` will throw an error if there was problem.

**Comment by saper** [comment]
With

````cpp
v8::Local<v8::Value> returned_value = Nan::New(val).ToLocalChecked();
````

I get

````
../src/custom_importer_bridge.cpp:10:41: error: no matching function
      for call to 'New'
  v8::Local<v8::Value> returned_value = Nan::New(val).ToLocalC...
                                        ^~~~~~~~
````
Sure, this works for `v8::String` but not for v8::Values.

**Comment by kkoopa** [comment]
`v8::Value` is a base class and not directly constructable. Arrays are constructed with `Nan::New<v8::Array>()`. That `v8::Handle` should be a `v8::Local`, then you don't need to convert anything.

**Comment by saper** [comment]
So I do not need to use `New` to bring it into the local scope?

**Comment by kkoopa** [comment]
No, arguments are in the same scope as the function body. Just replace `Handle` with `Local` everywhere applicable. `Handle` is permanently gone.

**Comment by saper** [comment]
Thank you very much for your help!
