### ISSUE TITLE
Any plans for a migration guide?

### ISSUE THREAD

**Issue by JCMais** [nodejs/nan#402]
Updating from NaN 1.x to 2.x is getting more harder than I thought.

**Comment by winfinit** [comment]
converted examples in node-addon-examples may make it a bit easier (pull request is pending, but you can see nan_2.x and nan_1.x here: https://github.com/winfinit/node-addon-examples)

also what helped me a lot is to look through https://github.com/nodejs/nan/tree/master/test

**Comment by kkoopa** [comment]
@rvagg [said he was working on one](https://github.com/nodejs/nan/pull/371#issuecomment-125987422)

**Comment by ivan** [comment]
The converter script in https://github.com/nodejs/nan/issues/376#issuecomment-120838432 was very helpful for me

**Comment by mscdex** [comment]
+1

**Comment by eljefedelrodeodeljefe** [comment]
Good hint @winfinit . Found everything I needed there.

**Comment by lovell** [comment]
The biggest _gotcha_ I've run into between nan v1 and v2 is a change to the Buffer creation methods where ownership of the underlying data is transferred.

In nan v1, the "take ownership" method is `NanBufferUse` which results in `delete[]` being called on the data during GC.

In nan v2, the "take ownership" method is `Nan::NewBuffer` which results in `free()` being called.

**Comment by JCMais** [comment]
@lovell I had a bunch of memory corruption because of this exact change. Took awhile to figure it out.

**Comment by mathiask88** [comment]
So if I use `new` for memory allocation then I need to use `BufferCopy` and cannot use the allocated memory block because it is removed with `free()`?

**Comment by kkoopa** [comment]
Supply a `FreeCallback` that calls `delete`.

**Comment by mathiask88** [comment]
@kkoopa Ah thanks, I read over that one. Is there a nan wrapper for `node::smalloc::FreeCallback` and `node::Buffer::FreeCallback callback`? And what is the `hint` argument?

**Comment by kkoopa** [comment]
https://github.com/nodejs/nan/blob/master/nan.h#L1218
The hint argument is user data.

**Comment by rvagg** [comment]
https://nodesource.com/blog/cpp-addons-for-nodejs-v4 here 'tis

**Comment by JCMais** [comment]
Great!
