### ISSUE TITLE
Cannot compile module with nan (‘NanScope’ was not declared in this scope)

### ISSUE THREAD

**Issue by ishi0** [nodejs/nan#403]
I'm trying to compile a package with nan 2.0.2 on node 0.12.7. I've installed nan and added it to package.json. When running `node-gyp rebuild` from package root, I get errors like:
> error: ‘NanNew’ was not declared in this scope

Complete output and project files are here: https://gist.github.com/ishi0/cc8e104fa046e0155bba
So how do I fix this?

**Comment by kkoopa** [comment]
You need to update to the NAN 2 syntax.

**Comment by fivdi** [comment]
Use the Nan::New rather than NanNew.
