### ISSUE TITLE
August 8 - Nan not found

### ISSUE THREAD

**Issue by wanderer** [nodejs/nan#405]
same a #320

**Comment by kkoopa** [comment]
That does it!
No more releases until npm [gets its shit together](https://github.com/npm/npm/issues/5082). I'm tired of republishing everything twice because of this.

**Comment by reqshark** [comment]
i was getting that nan not found shit so much the other day i almost fucking switched to go.. anyway no i didnt do that, i just haven't looked at nan 2.0 yet..

**Comment by reqshark** [comment]
also for whatever unverified reason when i did:
```python
'include_dirs': [ '<!(node -e "require(\'nan\')")' ]
```
it was working better than fat quote style in the readme. 
```python
"include_dirs" : [
    "<!(node -e \"require('nan')\")"
]
```
it seemed to mitigate nan not founds i was getting, which makes about zero sense. thanks.

**Comment by rvagg** [comment]
if Windows support is important you may want to test your gyp code there, we've had weird cross-platform problems with quoting in gyp.

**Comment by reqshark** [comment]
oh that's good to know, thank you.
