### ISSUE TITLE
Template function that used Local handler not working because of MaybeLocal

### ISSUE THREAD

**Issue by JCMais** [nodejs/nan#410]
I'm having some trouble converting the following template to NAN 2

```cpp
template <typename> struct ResultCanBeNull : std::false_type {};
template <> struct ResultCanBeNull<char*> : std::true_type {};

template<typename TResultType, typename Tv8MappingType>
v8::Local<v8::Value> Curl::GetInfoTmpl( const Curl *obj, int infoId )
{
    NanEscapableScope();

    TResultType result;

    CURLINFO info = (CURLINFO) infoId;
    CURLcode code = curl_easy_getinfo( obj->curl, info, &result );

    v8::Local<v8::Value> retVal = NanUndefined();

    if ( code != CURLE_OK ) {

        Curl::ThrowError( "curl_easy_getinfo failed!", curl_easy_strerror( code ) );

    } else {

        //null pointer
        if ( ResultCanBeNull<TResultType>::value && !result ) {

            retVal = NanNew<v8::String>( "" ); //line:1102

        } else {

            retVal = NanNew<Tv8MappingType>( result ); //line:1106
        }

    }

    return NanEscapeScope( retVal );
}
```

Tv8MappingType can be of type v8::Number or v8::String, as Nan::New\<v8::String\> now returns a MaybeLocal handler, the code is not compiling.

```
..\src\Curl.cc(1102): error C2679: binary '=': no operator found which takes a right-hand operand of type 'Nan::MaybeLocal<v8::String>' (
or there is no acceptable conversion)
..\src\Curl.cc(1106): error C2679: binary '=': no operator found which takes a right-hand operand of type 'Nan::MaybeLocal<v8::String>' (
or there is no acceptable conversion)
```

Changing retVal to MaybeLocal is not going to work, because Nan::New\<v8::Number\> returns a Local handler directly.

Any help would be greatly appreciated. 

Original code at https://github.com/JCMais/node-libcurl/blob/develop/src/Curl.cc#L1078

**Comment by kkoopa** [comment]
For the first one, use `EmptyString` https://github.com/nodejs/nan/blob/master/doc/new.md#api_nan_empty_string.

For the second, you need to convert the `MaybeLocal` to a `Local`, using either `MaybeLocal::ToLocal` or `MaybeLocal::ToLocalChecked`, if you are certain that `String` creation cannot fail.

**Comment by JCMais** [comment]
> For the second, you need to convert the MaybeLocal to a Local, using either MaybeLocal::ToLocal or MaybeLocal::ToLocalChecked, if you are certain that String creation cannot fail.

The issue here is that Tv8MappingType can be v8::Number, which doesn't creates a MaybeLocal.

```
..\src\Curl.cc(1106): error C2039: 'ToLocalChecked': is not a member of 'v8::Local<v8::Number>'
```

**Comment by kkoopa** [comment]
Do partial template specialization of the owner class on Tv8MappingType <==> v8::Number.

On a side note, you can (and should) use and construct the `MaybeLocal` and `Maybe` classes yourself. You could, for instance, wrap the `v8::Local<v8::Number>` in a `MaybeLocal` and return that, if it would be convenient. The idea behind maybes is that they protect against empty handles (null pointers).

**Comment by kkoopa** [comment]
Something like this:
```c++
template <typename T>
class Foo {
  inline Nan::MaybeLocal<T> bar() {
    return getSomeMaybeLocal();
  }
};

class Foo<v8::Number> {
  inline Nan::MaybeLocal<v8::Number> bar() {
    return Nan::MaybeLocal<v8::Number>(getSomeLocalNumber());
  }
};
```

**Comment by kkoopa** [comment]
Another way would be to make an overloaded function `wrap` or `unwrap` and make it idempotent through overloads.

```c++
template<typename T>
Nan::MaybeLocal<T> wrap(v8::Local<T> h) {
  return Nan::MaybeLocal<T>(h);
}

template<typename T>
Nan::MaybeLocal<T> wrap(Nan::MaybeLocal<T> h) {
  return h;
}
```

**Comment by agnat** [comment]
Few thoughts:

* Partial specialization seems like the right thing here. However, _never_ specialize _your client code_ unless you have to. It becomes a maintenance burden because you suddenly have to maintain two classes. You could mitigate that by moving most of the stuff to common base template, but it's a hassle...
* Always try to come up with an external utility first. More like the second approach, but...
* Overloads and _generic, unconstrained_ templates (like above) don't mix well. Overloaded functions are subject to implicit argument conversion, which in combination with a generic template might result in rather unexpected conversion paths. Using a function entry point is a good idea, though, as it cleans up the call site.

Here is scribble that combines the best of both worlds. The Generic NAN Maybefier:

````C++
namespace detail {

template <typename T> struct Maybefier;

template <typename T> struct Maybefier<v8::Local<T> > {
  static Nan::MaybeLocal<T> convert(v8::Local<T> v) {
    return Nan::MaybeLocal<T>(v);
  }
};

template <typename T> struct Maybefier<Nan::MaybeLocal<T> > {
  static Nan::MaybeLocal<T> convert(Nan::MaybeLocal<T> v) {
    return v;
  }
};

} // end of namespace detail

// call this in client code, like so: maybefy(someLocalOrMaybeLocal)
template <typename T, template <typename> class CouldbeMaybe>
Nan::MaybeLocal<T>
maybefy(CouldbeMaybe<T> v) {
  return detail::Maybefier<CouldbeMaybe<T> >::convert(v);
}
````

**Comment by agnat** [comment]
> generic, unconstrained

That's actually not true. The templates are reasonable picky. However, implicit conversion still looms.

**Comment by kkoopa** [comment]
Cool. That is definitely better.

**Comment by agnat** [comment]
Now that I think of it this might be worth adding to nan. Like... _all_ nan based, generic code will face similar issues. So, [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it)? or not?

**Comment by agnat** [comment]
````
template <typename T, template <typename> class CouldbeMaybe>
Nan::MaybeLocal<T>
maybefy(CouldbeMaybe<T> v);
````
The longer I look at it... I'm really pleased with this signature. It seems reasonable weird... lol.

**Comment by kkoopa** [comment]
Make a PR, and I'll include it in 2.1.0, whenever that has accumulated enough 
stuff to be worthy of a new minor release.

**Comment by JCMais** [comment]
Thank you @kkoopa and @agnat, decided to use the overloaded function.

And something like that directly in Nan would be great!

**Comment by agnat** [comment]
> Thank you

You're welcome.

> decided to use the overloaded function

Good luck! :-D

(just kidding, it will work. it's more a robustness thing)

> something like that directly in Nan would be great!

Coming up: #411
