### ISSUE TITLE
warning C4506: no definition for inline function '   v8::Persistent<v8::Object>   v8::Persistent<v8::Object>::New(v8::Handle<v8::Object>)

### ISSUE THREAD

**Issue by saper** [nodejs/nan#413]
When [compiling with Microsoft Studio Visual ++ 2013 iusing AppVeyor](https://ci.appveyor.com/project/sass/node-sass/build/1130/job/628kaine3i4g120n) I am getting the following warning only when building against node v0.10.40:

(wrapped for better readability)
````
create_string.cpp
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xmemory0(611): 
  warning C4506: no definition for inline function '
  v8::Persistent<v8::Object>   v8::Persistent<v8::Object>::New(v8::Handle<v8::Object>)' 
  (..\src\create_string.cpp) [C:\projects\node-sass\build\binding.vcxproj]
````

it does so for all node-sass C++ files, here is [create_string.cpp](https://github.com/sass/node-sass/blob/9cadef6ff236a6552815beacbf72fc931c08e2cd/src/create_string.cpp).

**Comment by kkoopa** [comment]
That's from v8. Nothing to do about it.

**Comment by kkoopa** [comment]
It is possible to disable the warning in binding.gyp or use a pragma.
```c++
#if defined(_MSC_VER)
# pragma warning( disable : 4506 )
#endif
```

**Comment by saper** [comment]
I don't think I understand where it comes from :) But as you say nan is unrelated. Thanks.
