### ISSUE TITLE
Test on OS X with Travis

### ISSUE THREAD

**Issue by kkoopa** [nodejs/nan#415]
http://docs.travis-ci.com/user/multi-os/

@rvagg as you are the owner of the Travis account, perhaps you could send a mail to support@travis-ci.com asking for them to enable it on this repo, since [it requres manual intervention](http://docs.travis-ci.com/user/multi-os/#Manual-intervention-required).

**Comment by rvagg** [comment]
done, will let you know how it goes

**Comment by rvagg** [comment]
@kkoopa apparently it's enabled now so you should be able to add the additional config for it

**Comment by kkoopa** [comment]
Cool. I'll push an updated config and see if it builds.

**Comment by kkoopa** [comment]
First attempt
https://travis-ci.org/nodejs/nan/builds/76010424

**Comment by addaleax** [comment]
Did this for a [project of mine](https://github.com/addaleax/lzma-native) last week, the comments at travis-ci/travis-ci#2311 were pretty helpful

**Comment by springmeyer** [comment]
I recommend roughly the same approach in the node-pre-gyp docs: https://github.com/mapbox/node-pre-gyp#enabling-multi-os

**Comment by kkoopa** [comment]
Quid pro quo anyone? PRs welcome. Make them out against [the osx_test branch](https://github.com/nodejs/nan/tree/osx_test).
