### ISSUE TITLE
AsyncWorker has posix thread conflict issue

### ISSUE THREAD

**Issue by sapsaldog** [nodejs/nan#424]
Hello

Now I'm porting alljoyn IoT Library(allseenalliance.org) to Node.js.

Alljoyn core library use posix thread, so I have some difficulty  with porting it.

Whenever posix thread related things happened, I cannot use AsyncWorker to implement js callback.

I just use raw libuv call, and my codes are disruptive. 

the main problem is that AsyncWorker constructor has v8 calling.

I think we make more super class that do not have persistentHandle member,

do you have any good idea?

**Comment by rvagg** [comment]
you don't have to use `AsyncWorker`, it's just there for convenience for the common case but there are many cases of async work that don't fit within its paradigm so you should program directly against libuv and Node for these things, only make use of NAN where it makes sense like `Nan::MakeCallback()`

**Comment by sapsaldog** [comment]
Thanks you for your rapid answer. 

Don't you think about It's more likely useful to support that I suggested?

It's not helpful to anyone?

**Comment by bnoordhuis** [comment]
I personally don't really see the point.  AsyncWorker's raison d'être is to 1) perform work in the thread pool, and 2) call JS land with the result.  The infrastructure for 2) is what makes up most of the class, take that away and what remains is something you can implement yourself in a few lines of code.

**Comment by kkoopa** [comment]
Agreed, it would be of no use.
