### ISSUE TITLE
Trouble using Nan::NewBuffer

### ISSUE THREAD

**Issue by cstyan** [nodejs/nan#434]
Hi, I apologize if this ends up being a duplicate or dumb issue, but I haven't been able to find the info. I'm looking for.

I'm trying to create a binding for a C library, though I really only need one function from it.  The function I've written in my `.cc` file should return a node Buffer off the output from the C function,  however I can't seem to get `Nan::NewBuffer to work`.

In the `.cc` file I have:
```
unsigned int len;
unsigned int len;
......
if (!RSA_sign(NID_sha1, token, node::Buffer::Length(args[1]), sig, &len, rsa)) {
    Nan::ThrowTypeError("failed to sign token");
    return;
}
args.GetReturnValue().Set(Nan::MaybeLocal<v8::Object> (Nan::NewBuffer((const char*)sig, len)));
```

node-gyp erros on the `Nan::NewBuffer` call with:
```
CXX(target) Release/obj.target/binding/binding/binding.o
../binding/binding.cc:63:58: error: no matching function for call to
      'NewBuffer'
  args.GetReturnValue().Set(Nan::MaybeLocal<v8::Object> (Nan::NewBuffer(...
                                                         ^~~~~~~~~~~~~~
```
Along with some other errors.

Any help would be appreciated :smiley:

**Comment by bnoordhuis** [comment]
`NewBuffer()` returns a `MaybeLocal<v8::Object>` that you have to unwrap first with `.ToLocal()` or `.ToLocalChecked()`.

**Comment by kkoopa** [comment]
```c++
unsigned int len;
unsigned int len;
......
if (!RSA_sign(NID_sha1, token, node::Buffer::Length(args[1]), sig, &len, rsa)) {
    return Nan::ThrowTypeError("failed to sign token");
}
args.GetReturnValue().Set(Nan::NewBuffer(reinterpret_cast<const char*>(sig), len).ToLocalChecked());
```
Note that [`NewBuffer` takes ownership of the pointer and will call `free` on it when garbage collection occurs](https://github.com/nodejs/nan/blob/master/doc/buffers.md#api_nan_new_buffer).

**Comment by cstyan** [comment]
Thanks for the quick responses!

I am still getting the `no matching function for call to 'NewBuffer' error with both of your suggestions.

**Comment by kkoopa** [comment]
Then something is badly wrong in your code or environment. Can't tell from what you posted.

**Comment by kkoopa** [comment]
Ah, now I see what it is. Since `NewBuffer` takes ownership of the pointer, you can't give a const `char *`. Use `CopyBuffer` or a non-const buffer.

**Comment by cstyan** [comment]
What other information do we need to figure out what is wrong?  I think it may be related to the fact that I'm using a module from npm which make use of nan@1.8.4?

I am running node v0.12, and nan@2.0.8.

Here is the entire `.cc` file: 
```
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>

#include <node.h>
#include <v8.h>
#include <nan.h>

#define RSA_verify RSA_verify_mincrypt
#include "rsa.h"
#undef RSA_verify

#include <openssl/evp.h>
#include <openssl/objects.h>
#include <openssl/pem.h>
#include <openssl/rsa.h>
#include <openssl/sha.h>

#include "binding.h"
#include <errno.h>
#include <string.h>
#define MAX_PAYLOAD 4096

void Sign(const Nan::FunctionCallbackInfo<v8::Value>& args) {

  if (args.Length() < 2) {
    Nan::ThrowTypeError("Wrong number of arguments");
    return;
  }

  FILE *fd;
  unsigned int len;
  const char* key_path;
  const unsigned char* token;

  key_path = (const char*)node::Buffer::Data(args[0]);
  token = (unsigned char*)node::Buffer::Data(args[1]);

  unsigned char sig[MAX_PAYLOAD];

  RSA *rsa = RSA_new();
  fd = fopen(key_path, "r");
  if (!fd) {
    Nan::ThrowTypeError("fopen() failed");
    return;
  }
  if (!PEM_read_RSAPrivateKey(fd, &rsa, NULL, NULL)) {
    fclose(fd);
    RSA_free(rsa);
    Nan::ThrowTypeError("couldn't read private key");
    return;
  }
  if (!RSA_sign(NID_sha1, token, node::Buffer::Length(args[1]), sig, &len, rsa)) {
    Nan::ThrowTypeError("failed to sign token");
  }

  args.GetReturnValue().Set(Nan::NewBuffer(reinterpret_cast<const char*>(sig), len).ToLocalChecked());
}

void Init(v8::Local<v8::Object> exports) {
  exports->Set(Nan::New("sign").ToLocalChecked(),
              Nan::New<v8::FunctionTemplate>(Sign)->GetFunction());
}

NODE_MODULE(binding, Init)
```

**Comment by addaleax** [comment]
Yes, you want `CopyBuffer` instead of `NewBuffer`, since you allocated `sig` on the stack and not using a method (like `malloc()`) that requires using `free()`.

**Comment by cstyan** [comment]
Perfect, got it working.  Thanks! :smiley:
