### ISSUE TITLE
Wrong property setter declaration in docs?

### ISSUE THREAD

**Issue by jjrv** [nodejs/nan#436]
[This section in the docs](https://github.com/nodejs/nan/blob/master/doc/methods.md#api_nan_property_setter) says:

```c++
void PropertySetterName(v8::Local<v8::String> property,
                        v8::Local<v8::Value> value,
                        const Nan::PropertyCallbackInfo<v8::Value>& info);
```

I tried passing that to Nan::SetAccessor and it complained that `info` should be `const Nan::PropertyCallbackInfo<void>&`.

**Comment by kkoopa** [comment]
Because [this section in the docs](https://github.com/nodejs/nan/blob/master/doc/methods.md#nansetaccessor) says nothing about `SetAccessor` accepting a property setter.
