### ISSUE TITLE
Templates-based bindings

### ISSUE THREAD

**Issue by jjrv** [nodejs/nan#437]
I just noticed talk about templates-based bindings in #349. I've been working on a package called `nbind` every now and then since last December and now it's pretty much functional for the use case of heavy single-threaded calculations. It investigates C++ class methods using templates and produces NAN bindings. I just finished porting it to NAN 2 and documenting it on [GitHub](https://github.com/charto/nbind) and [npm](https://www.npmjs.com/package/nbind).

The next major ongoing step is to port `nbind` to Emscripten using embind as a reference (the Node.js version of `nbind` is already based on that). That would allow writing bindings once to run in Node.js, Electron and browsers.

I'd be more than happy to collaborate on this or get comments, since I think what's ready is at least a start for a friendlier alternative API to NAN. It's completely functional for my needs already but will never support **everything** NAN can do, especially if feature parity with Emscripten is maintained. The [readme](https://github.com/charto/nbind/blob/master/README.md) and the [tests in the project's repo](https://github.com/charto/nbind/tree/master/test) show what bindings syntax looks like, for example you can have C++:

```c++
class Callback {
public:
    static int callIncrementInt(nbind::cbFunction &incrementInt, int x) {
        // The template argument defines what type to cast the return value to.
        return(incrementInt.call<int>(x));
    }
};

NBIND_CLASS(Callback) {
	construct<>();

	method(callIncrementInt);
}
```

It can be used from JavaScript with:

```javascript
var Callback = require('nbind').module.Callback;

console.log(Callback.callIncrementInt(function(x) {return(x + 1);}, 1));
```

The C++ function takes a JavaScript callback function and an integer, passes the integer to the callback and returns it. It's a pretty simple example, but shows how easy it is to call both ways between the two languages without any glue code, just a list of the classes and methods to bind.
The readme has many more working examples.

**Comment by agnat** [comment]
Hey @jjrv,

this looks interesting. [Here](https://github.com/agnat/n2o) is an old experiment of mine, dating back to 2010... wow. It explores [boost python](http://www.boost.org/doc/libs/1_59_0/libs/python/doc/) like bindings on top of v8. Note the javascriptyness of the binding code:

#### hello.cpp:
````c++
void greet() { std::cerr << "Hello world." << std::endl; }
int  add(int a, int b) { return a + b; }

N2O_MODULE(object exports) {
  exports["greet"] = function(greet);
  exports["add"]   = function(add);
}

````

#### hello.js:
````javascript
const hello = require('hello');

hello.greet();
console.log(hello.add(2, 3));
````

It's not feature complete and won't compile on current node since is doesn't use NAN. It still is an interesting read. Take a look at the [tests](https://github.com/agnat/n2o/tree/master/test) to see what's actually implemented. One interesting feature is the C++ to JavaScript exception translation.

Full disclosure: I like templates.

**Comment by jjrv** [comment]
nbind works pretty nicely now, also as a fallback for node addons when a binary or C++ compiler to produce it are not available. Anyway no reason to keep this issue open...
