### ISSUE TITLE
encharm/nan-example-eol no longer boilerplate NAN example

### ISSUE THREAD

**Issue by andrewrk** [nodejs/nan#438]
There is currently no example linked from the readme that demonstrates how to use node::ObjectWrap. Specifically this upgrade error:

```
../src/file.cc: In static member function ‘static void GNFile::Init()’:
../src/file.cc:25:53: error: no matching function for call to ‘v8::FunctionTemplate::SetClassName(Nan::imp::MaybeFactoryBase<v8::String>::return_t)’
     tpl->SetClassName(Nan::New<String>("GrooveFile"));
```

**Comment by andrewrk** [comment]
Also `NanAssignPersistent` is not mentioned in the Changelog.

**Comment by andrewrk** [comment]
This example is helpful: https://github.com/nodejs/nan/blob/master/test/cpp/objectwraphandle.cpp

**Comment by kkoopa** [comment]
Not related to ObjectWrap. String constructors return MaybeLocals which need unwrapping to Locals. This is stated in the documentation.

**Comment by andrewrk** [comment]
My point is that nan links to that project in the readme and it doesn't compile any more against nan.
