### ISSUE TITLE
`nvm` should not use "master" branch

### ISSUE THREAD

**Issue by ljharb** [nodejs/nan#444]
Per the travis setup line here: https://github.com/nodejs/nan/blob/f14e04a3492ede8ca2aac8f049a60c595d7bfbf2/.travis.yml#L24

This will use the "master" branch of `nvm`, which will not necessarily work. Please use the latest git tag instead - either by using `git tag` with config `tag.sort` set to `version:refname`, or, you could just hardcode the `nvm` version.

**Comment by wadey** [comment]
I fixed this in my repo by adding the following to the nvm setup pipeline:

    (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)

See here: https://github.com/wadey/node-microtime/blob/684254eb0ebc90203c95987b3d6981fd67fe58b5/.travis.yml#L22

**Comment by kkoopa** [comment]
Thanks. Waiting on AppVeyor to get Node 4 working.
https://github.com/nodejs/nan/pull/442

**Comment by mzgol** [comment]
> Thanks. Waiting on AppVeyor to get Node 4 working.
> #442

AppVeyor has Node 4 since yesterday! :)

**Comment by kkoopa** [comment]
Apparently not when using `Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)`. `Install-Product node $env:nodejs_version` appears to work though.

**Comment by mzgol** [comment]
I see. The `Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)` command is very slow, though so I've been using `Install-Product node $env:nodejs_version` exclusively for some time.

I've reported it to them at http://help.appveyor.com/discussions/suggestions/810-nodejs-400-is-out

**Comment by kkoopa** [comment]
IIRC `Update-NodeJsInstallation` is supposed to install the very latest version, which might be newer than what is installed by `Install-Product`, but this might not apply anymore. `Install-Product` seems to work well enough at the moment.

**Comment by mzgol** [comment]
Yeah, I think they have to explicitly add built images to AppVeyor to make `Install-Product` work. I just usually open a new "Suggestion" at http://help.appveyor.com when a new major arrives, they usually react quickly to that. ;)
