### ISSUE TITLE
Release 2.1.0

### ISSUE THREAD

**Issue by kkoopa** [nodejs/nan#446]
Figured I'd get this out some time after Node 4.0.0 was released. Currently waiting on https://github.com/nodejs/node/pull/2698 for no other reason than 'because'. Expect a release this week. It will contain the four PRs scheduled for 2.1. Nothing really significant.

**Comment by rvagg** [comment]
+1 that's a good list for 2.1

**Comment by LinusU** [comment]
@kkoopa That pull request have been merged now, time to cut a release? :+1:

**Comment by kkoopa** [comment]
Yes, I'll get on to it this week.

**Comment by LinusU** [comment]
Thank you!

**Comment by erulabs** [comment]
+1 Thank you! Very much looking forward to it!

**Comment by mikolalysenko** [comment]
So what else is needed for nan v2.1?  If you have any outstanding issues I can take a shot at them and send you some PRs.

**Comment by kkoopa** [comment]
I had two computers die within one week of eachother, which prevented me from doing it this week. Now I am in Barcelona for a week and can't make a release until I'm back. Sorry, but shit happens. If there's a rush, @rvagg can make a release to npm, else I'll deal with it in a week.

**Comment by LinusU** [comment]
That's too bad :(

No stress, hope you get your computer situation sorted. Having your computer die on you is never fun.
