### ISSUE TITLE
Feature Request: ParseEncoding()

### ISSUE THREAD

**Issue by mscdex** [nodejs/nan#453]
It would be great to see `ParseEncoding()` added to nan. The reason is that `Nan::Encode()` and `node::ParseEncoding()` use different encoding types, causing compiler errors (`Nan::Encoding` vs `node::encoding`).

Added it would also mean that addon developers would no longer have to `#ifdef` around `node::ParseEncoding()` just because it takes an isolate post-node v0.10.

**Comment by mscdex** [comment]
Ok, I could have sworn that `node::ParseEncoding()` was exported, but evidently not. :-(

**Comment by bnoordhuis** [comment]
It is in v4 but not in v0.10 and v0.12 (it's declared in node.h but not tagged `NODE_EXTERN`.)

**Comment by kkoopa** [comment]
`Nan::Encoding` can be safely cast to `node::encoding`. They use the same values.

If someone were to backport it all like nan_string_bytes.h, I would merge it.
