### ISSUE TITLE
StringBytes::Encode() optimizations

### ISSUE THREAD

**Issue by mscdex** [nodejs/nan#454]
It looks like nan's `StringBytes::Encode()` implementation is missing out on some optimizations that have existed since node v0.11.3.

I'm specifically looking at the [external string optimization](https://github.com/nodejs/node/commit/642ea2b668c12773c371b333926ccc10070ef2cb). I'm not sure if this optimization can apply at all to node v0.10 or earlier, but I think it should at least be used with node v0.12 and newer.

**Comment by kkoopa** [comment]
I guess @indutny left them out since they don't work on 0.10 and earlier. nan_string_bytes.h is only used for 0.10 and older, newer versions ought to use the builtin routines, as Nan::Encode maps (almost) directly to Node::Encode.

**Comment by indutny** [comment]
cc @trevnorris @nodejs/v8

**Comment by trevnorris** [comment]
I'm unsure of what function I should be looking at. If `Nan::Encode()` maps to node's impl then the performance should be there.
