### ISSUE TITLE
Expose a portable method for reading the bytes out of typedarrays

### ISSUE THREAD

**Issue by mikolalysenko** [nodejs/nan#455]
What are the correct invocations for getting the bytes out of a typedarray?  This broke with migration to v8 version 4 in iojs 3 and up.

Going forward what is the right strategy for reading and writing typedarray data in NAN 2+?

**Comment by kkoopa** [comment]
NAN does not support typed arrays. Use buffers.

**Comment by mikolalysenko** [comment]
@kkoopa what about systems that would need typedarrays, for example numerical computing or WebGL bindings?

**Comment by kkoopa** [comment]
It should be doable with buffers at the C++ level, else write such a method and use it. Typed arrays are not available on all supported platforms and will not be supported by NAN.

**Comment by rvagg** [comment]
@mikolalysenko since TypedArrays are now basically interchangable with Buffer because they share the same underlying implementation you should be able to write such code to work with Buffer exclusively, you can even instantiate a Buffer with a TypedArray now.

If you don't care about older versions of Node that don't support TypedArray then perhaps you shouldn't be concerned about using NAN for those specific instances anyway and just work directly with the V8 APIs that you want in those cases.

**Comment by mikolalysenko** [comment]
@rvagg right, but there are other versions of node that do use typedarrays, for example node 0.10, node 0.12, iojs 1 and iojs 2.  Things changed in iojs 3 and node 4.  Before, you could get the storage of a typedarray using something like the following:

```c++
unsigned int offset = array->Get(NanNew<v8::String>("byteOffset"))->Uint32Value();
void* data = (void*) &((char*) array->GetIndexedPropertiesExternalArrayData())[offset];
```

Starting with v8 version 4, this changed.  Now you need to do the following:

```c+
unsigned int offset = array->ByteOffset();
void* data = (void*)((char*)array->Buffer()->GetContents().Data() + offset);
```

Now you could use preprocessor macros to hack around this, but isn't this the problem NAN is supposed to solve?

**Comment by mikolalysenko** [comment]
Note that for headless-gl, I want to support all versions of node >= 0.10.  It seems reasonable to have an interface that works for all of these cases.

**Comment by mikolalysenko** [comment]
Or illustrated in a different way, we could break down the history of node into 3 epochs:

```
        Before typedarrays        External typedarray API     New typedarray API
     o---------------------------o---------------------------o-------------------> Now
     ^                           ^                           ^
Birth of node                    node 0.8                    v8 v4
```

TypedArrays are an important and useful feature in all versions of node after 0.8, and it would be nice if we could write native code that accesses them in a portable way.

**Comment by kkoopa** [comment]
Those are not typed arrays, those are the external array data API. It has been removed and will never come back. You should use Buffer.

0.8 does not have typed arrays, 0.10 does not really have them either, there exists an incompatible implementation of sorts, but it is not sufficient. Typed arrays were introduced with io.js 1.0, which came before Node 0.12.

Write a PR that backports the latest implementation of typed arrays from V8 4.7 to work on all versions of Node in a seamless fashion and I'll gladly merge it.

**Comment by mikolalysenko** [comment]
Done.  Let me know what else you need to get this merged.
