### ISSUE TITLE
Can Nan::Callback take a MaybeLocal?

### ISSUE THREAD

**Issue by wanderer** [nodejs/nan#460]
Is there any reason Nan::Callback doesn't take MaybeLocal? If it did it would make returning buffers in a callback easier;

from this
```
    MaybeLocal<Object> buf = Nan::NewBuffer(output, t);
    Local<Object> localBuf;
    buf.ToLocal(&localBuf);

    Local<Value> argv[3] = {
      buf,
      ....
    };
    callback->Call(3, argv);
```
to 

```
    MaybeLocal<Value> argv[3] = {
      Nan::NewBuffer(output, t);
       ....
    };
    callback->Call(3, argv);
```

**Comment by kkoopa** [comment]
No, it won't work and does not really make sense. Maybe-types have no representation in JavaScript and they exist solely to force users to deal with empty handles.

**Comment by bnoordhuis** [comment]
To expand on that, think about what `Nan::Callback()` should do when `maybe_handle.IsEmpty() == true`.  There is no good answer, trying to call into JS code with empty handles is an error.
