### ISSUE TITLE
NAN_MODULE_INIT to support second parameter

### ISSUE THREAD

**Issue by noamokman** [nodejs/nan#461]
Hi there!
Could we add a second parameter to the NAN_MODULE_INIT?
It shouldn't break API and would help implement exposing a function

Currently done like so:
```cpp
void Init(Handle<Object> exports, Handle<Object> module) {
  Set(module, New<String>("exports").ToLocalChecked(),
      GetFunction(New<FunctionTemplate>(ExportFunc)).ToLocalChecked());
}
```
Or perhaps adding something else entirely to handle this use case?

**Comment by rvagg** [comment]
The tricky thing about this is that `module` was added 1/2 way through 0.10 so it breaks our ability to support back to 0.8 with it. _But_ perhaps we could come up with a creative way of doing it ..

**Comment by kkoopa** [comment]
What Rod said, and I don't think there's a creative way of doing it. If you don't 
care about 0.8 support, use Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE for 
the first argument, and deal with incompatibilities in extra arguments yourself.

**Comment by noamokman** [comment]
Your right, 0.8 has something like [this](https://github.com/nodejs/node/blob/v0.8.17-release/src/node.h#L205):
```cpp
  void (*register_func) (v8::Handle<v8::Object> target);
```
While current version has [this](https://github.com/nodejs/node/blob/master/src/node.h#L361):
```cpp
typedef void (*addon_register_func)(
    v8::Local<v8::Object> exports,
    v8::Local<v8::Value> module,
    void* priv);
```

So this can't be done?
The alternate method is to handle this in the JavaScript and return an object with one function.

**Comment by kkoopa** [comment]
If you care about 0.8, there's nothing to do. If you ignore 0.8, you can use the two-argument function however you want, for example like this:

```c++
#if NODE_MODULE_VERSION < IOJS_3_0_MODULE_VERSION
  typedef v8::Handle<v8::Value> ADDON_REGISTER_FUNCTION_ARGS2_TYPE;
#else
  typedef v8::Local<v8::Value> ADDON_REGISTER_FUNCTION_ARGS2_TYPE;
#endif

void Init(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE exports, ADDON_REGISTER_FUNCTION_ARGS2_TYPE module) { }
 ```

Said macro won't appear in NAN at least until 0.8-support is dropped for the aforementioned reasons.

**Comment by noamokman** [comment]
Got it. Closed for now, thanks :+1: 
I hope it will come up when 0.8 support is dropped.

**Comment by JCMais** [comment]
Can this be added? 0.8 should be dead for now.

**Comment by kkoopa** [comment]
Since that would entail a breaking change, I do not think it will happen until autumn. 0.8 and 0.10 are so similar that I would like to get rid of both at the same time.

**Comment by JCMais** [comment]
Fair enough.
