### ISSUE TITLE
Getting char* from a String, nan ~2.0.0

### ISSUE THREAD

**Issue by justinmchase** [nodejs/nan#464]
Given nan ~2.0.0, is there a helper method for just getting a char* out of a string property?

For example:
```
Local<Object> obj = info[0].As<Object>();
Local<String> name = Nan::Get(obj, Nan::New<String("name").ToLocalChecked()).ToLocalChecked()->ToString();
v8::String::Utf8Value val(name);
std::string str(*val);
return str.c_str();
```

That's kind of a lot of code so I'm wondering if nan has a helper or easier way of doing this already. I'm looking but not finding it.

Ideally something like:
```
Local<Object> obj = info[0].As<Object>();
char* name = Nan::GetString(obj, "name");
```

**Comment by kkoopa** [comment]
No, it is unnecessary to bloat the API with sugar. It has quite a lot of functions already. Just declare that a function or macro in your own code and use it.

But why are you converting it to a std::string only to return a `char *` which will refer to deallocated memory? If you want it to stick around, it is more effective to keep the `Utf8Value` around and dereference it when necessary. You should also not use `Utf8Value` for that matter. `Nan::Utf8String` is the correct option. The `ToString` conversion should also be unnecessary.

**Comment by justinmchase** [comment]
That code was a work in progress, for what its worth I ended up doing this:
```
Local<Object> obj = info[0].As<Object>();
Local<String> name = Nan::Get(obj, Nan::New<String>("name").ToLocalChecked()).ToLocalChecked()->ToString();
v8::String::Utf8Value val(name);
deviceName = *val;
```

**Comment by kkoopa** [comment]
```c++
Local<String> name = Nan::Get(info[0].As<Object>(), Nan::New("name").ToLocalChecked()).ToLocalChecked();
Nan::Utf8String val(name);
deviceName = *val;
```
should be even better
