### ISSUE TITLE
Feature Request: raw string data accessor

### ISSUE THREAD

**Issue by demmer** [nodejs/nan#465]
Inspired by the discussion on #464, I was wondering if there was any way to have a NaN method that would get at the underlying raw bytes of a v8 String without creating a copy first like `Nan::Utf8String` does.

There have been cases in which I need the contents of a v8 string in C++ land where I end up needing to copy twice, first into a `Utf8String` and then again into a `std::string`.

I don't even know if this kind of thing is supported by the v8 APIs (at least I couldn't find anything relevant from my initial read of the docs) but it seems like something that "should" be doable.

**Comment by bnoordhuis** [comment]
If you mean raw as in V8's internal representation then the answer is no.  (Strings don't have a single representation, by the way.)

The only way of getting at the bytes is by writing (i.e. copying) them out of the JS heap using the APIs that nan provides, or by using an external string where you own the memory.

**Comment by kkoopa** [comment]
No. It cannot be done.

You can however use `String::Write` to copy it directly to a buffer.

**Comment by demmer** [comment]
Alas that was what I was afraid of.
Thanks for the quick feedback.
