### ISSUE TITLE
Nan::Has and Nan::Delete have probably wrong signatures

### ISSUE THREAD

**Issue by royaltm** [nodejs/nan#469]
The Nan::Has (not the integer key version) signature is:

```
Nan::Maybe<bool> Nan::Has(v8::Local<v8::Object> obj, v8::Local<v8::String> key);
```

when V8 signature of [Object::Has](https://v8docs.nodesource.com/io.js-3.0/db/d85/classv8_1_1_object.html#ab3c3d89ea7c2f9afd08965bd7299a41d) has clearly different `key` type:
```
Maybe<bool> Has	(Local< v8::Context>context, v8::Local<v8::Value> key)	
```

The same problem with [Nan::Delete](https://v8docs.nodesource.com/io.js-3.0/db/d85/classv8_1_1_object.html#a2fa0f5a592582434ed1ceceff7d891ef).

It surprises me, since Nan::Get and Nan::Set expects type `Local<Value>` as a key argument.

Is it just a bug or there is a higher purpose behind this inconsistency?

**Comment by royaltm** [comment]
It seems that v8's signatures in 0.10 were `Local<String> key`, but since 0.12 they became `Local<Value> key`. Shouldn't NAN follow v8 Api?

**Comment by kkoopa** [comment]
It does, the lowest common denominator.

**Comment by royaltm** [comment]
really? then e.g. all `Maybe<*>` converters are apparently breaking your rule. Would it really be a problem if Nan::Has and Nan::Delete could also accept Local<Value> as a key?

**Comment by kkoopa** [comment]
They take a Local as the key.

**Comment by royaltm** [comment]
I wrote `Local<Value>` but the parser ate `<Value>`. Couldn't (https://github.com/nodejs/nan/blob/29450ed1670051613ffea9dd3f980f8685feceb4/nan_maybe_43_inl.h#L109[Has] and friends accept `Local<Value> key` as in current api and convert to String for pre 0.12?

**Comment by kkoopa** [comment]
I can't think of a well-defined way of doing that. The code bases are quite different and would probably behave strangely in all cases but Strings. 

https://github.com/nodejs/node/blob/v0.8.28-release/deps/v8/src/api.cc#L3045-L3053
https://github.com/nodejs/node/blob/v4.1.0/deps/v8/src/api.cc#L3846-L3856

Symbols will never be supported, that leaves only strings and raw indices. Both of them are supported, there is nothing more to do.
