### ISSUE TITLE
Nan::NanErrnoException

### ISSUE THREAD

**Issue by heavyk** [nodejs/nan#471]
in the docs it's called `Nan::ErrnoException` in the header, it's `Nan::NanErrnoException`

is that a mistake?

header:
https://github.com/nodejs/nan/blob/f14e04a3492ede8ca2aac8f049a60c595d7bfbf2/nan.h#L837
docs:
https://github.com/nodejs/nan/blob/4ed41d760313b648b4d212d6ff5374668757be4f/doc/errors.md#nanerrnoexception

**Comment by kkoopa** [comment]
Yes, but the mistake is in the header, the documentation is correct. #408
