### ISSUE TITLE
Using Local Vs Handles in Nan

### ISSUE THREAD

**Issue by GayathriKaliyamoorthy** [nodejs/nan#474]
Hi,

Nan 2.x changed all function signatures to use only Local<T> handles, it does not use Handle<T> anymore, is there any specific reason using Local<T> over Handle<T>.

What is the technical difference between Local<T> and Handle<T> other than inheritance relationship, can they be used interchangeably? 

Thanks

**Comment by brodybits** [comment]
One of the changes in the V8 project is that `v8::Handle` was deprecated and completely superseded by `v8::Local`.

**Comment by rvagg** [comment]
^ that

In V8 4.5: https://codereview.chromium.org/1224623004

Uncertain when it'll be removed but you need to prepare for a world without `Handle` so best do it now so you don't have to do it later.

**Comment by kkoopa** [comment]
Do not use Handle, it is outdated. Local is the same but better.
