### ISSUE TITLE
How to get v8::Local object value from Nan::Persistent (?)

### ISSUE THREAD

**Issue by brodybits** [nodejs/nan#475]
Considering that `v8::Persistent` (which has `v8::PersistentBase` in common with `Nan::Persistent`) had stopped deriving from `v8::Handle`, I had been searching for a way to get the `v8::Local` object value and the only solution I could find is in the following response message on the v8-users forum: https://groups.google.com/forum/#!msg/v8-users/6kSAbnUb-rQ/T2BS0O-LuGAJ

Quoted here for reference:
```C++
template<class T>
inline Local<T> ToLocal(Persistent<T>* p_) {
  return *reinterpret_cast<Local<T>*>(p_);
}
```

Should we provide a similar function to get the `v8::Local` object from `Nan::Persistent` or is there a better solution?

**Comment by rvagg** [comment]
`v8::Local<v8::Object> object = Nan::New(persistent);`

I'm noticing this is not mentioned in the docs, perhaps you can suggest a doc update for this?

**Comment by brodybits** [comment]
:+1: Will issue when I get a chance.

**Comment by bfortunato** [comment]
Local<Context> context = persistentContext.Get(isolate)
