### ISSUE TITLE
Npm- cannot find module "are-we-there-yet"

### ISSUE THREAD

**Issue by zonorion** [nodejs/nan#479]
Hi everybody,
I use centos os ver 6.7, when i use npm, i get error "error 'REPLACE_INVALID_UTF8' is not member of V8::String". Then i enter command " npm -g install npm", i get error "Npm- cannot find module "are-we-there-yet"". Who can tell me how to fix it? Thanks so much.

**Comment by rvagg** [comment]
This is an issue for npm, have a look through the issues here: https://github.com/npm/npm/search?q=are-we-there-yet&type=Issues&utf8=%E2%9C%93

Unfortunately I don't think we can give clear advice on this as it seems to be very dependent on exactly what you have installed and the npm folk are best placed to help. The only suggestion I have is to stick with npm v2 for now, `npm install npm@2 -g`, although it's possible your installation is borked now and you need to reinstall node/npm from scratch.

**Comment by zonorion** [comment]
Thanks for reply!
