### ISSUE TITLE
Nan::SetterCallback has the wrong signature.

### ISSUE THREAD

**Issue by 2Pacalypse-** [nodejs/nan#482]
It's either wrong in the code:
https://github.com/nodejs/nan/blob/505803bbd83dbd43c06e179b78b690e52e17d317/nan_callbacks.h#L22

or in the docs (under Example):
https://github.com/nodejs/nan/blob/master/doc/methods.md#api_nan_setter

Going by the [v8 docs on Accessors](https://developers.google.com/v8/embed#accesssors), it seems like it's wrong in the code, ie. third parameter should be `const PropertyCallbackInfo<v8::Value>&` instead of `const PropertyCallbackInfo<void>&`.

**Comment by kkoopa** [comment]
No, it is correct.

**Comment by 2Pacalypse-** [comment]
Is it wrong in the docs (under Example) then?

**Comment by kkoopa** [comment]
Ah, now I see what you mean (easier from a desktop browser). It's the example in the documentation that is wrong.

**Comment by 2Pacalypse-** [comment]
Thank you for confirming. Took me longer than I'd like to admit debugging before I noticed it either.

If you don't mind me asking, why exactly is `void` used there instead of `v8::Value` anyway?

**Comment by kkoopa** [comment]
Because a setter, as accessor, does not return a value. Named and indexed property _interceptor_ setters, return a value, because the specification says so (probably). It is customary to return the value that was passed in, as this is how it works (automatically) in JavaScript.

**Comment by 2Pacalypse-** [comment]
Thanks, that makes sense.
