### ISSUE TITLE
Nam::ThrowError will not accept Local<Object>

### ISSUE THREAD

**Issue by tobiashm** [nodejs/nan#483]
There are two signatures for `Nan::ThrowError` that will either accept a `v8::Local<v8::Value>` or a `v8::Local<v8::String>`. When passed a `v8::Local<v8::Object>` it should hit the `Nan::ThrowError(v8::Local<v8::Value> error)` method, since it's a subclass of `Value` but not of `String`. But instead it throws `error: call to 'ThrowError' is ambiguous`.

For an example, see https://github.com/apiaryio/protagonist/pull/90#issuecomment-144548443 where we're trying to upgrade from Nan 1 to 2.
In the code, `NanThrowError` was simply replaced with `Nan::ThrowError`, and the former had no problems with accepting the error as a `v8::Local<v8::Object>`.

**Comment by bnoordhuis** [comment]
Sounds like https://github.com/nodejs/nan/issues/390.  We have automated tests that cover this part of the API (and they pass) so you're probably hitting a bug in your compiler.

**Comment by kkoopa** [comment]
Seems so. Closing this, as it is beyond our control.
