### ISSUE TITLE
Trying to know if info object has an element

### ISSUE THREAD

**Issue by jmtovarf** [nodejs/nan#484]
I have a function that recieves a `const Nan::FunctionCallbackInfo<v8::Value>& args`

Local<v8::Object> obj = args[0]->ToObject();

when I try to compile the code, It retrieves the following message `error: no matching member function for call to 'Has'`

if(obj->Has(Nan::New<v8::String>("key")))

If there are another methods to know if object has an element, please let me know.

**Comment by kkoopa** [comment]
https://github.com/nodejs/nan/blob/master/doc/maybe_types.md#api_nan_has

**Comment by jmtovarf** [comment]
I tryed to validate it with Nan::Maybe<bool> Nan::Has into if conditional and I got 
`error: value of type 'Nan::Maybe<bool>' (aka 'v8::Maybe<bool>') is not contextually convertible to 'bool'`

**Comment by kkoopa** [comment]
https://github.com/nodejs/nan/blob/master/doc/maybe_types.md#api_nan_maybe
