### ISSUE TITLE
Documentation suggestion - Better links to examples

### ISSUE THREAD

**Issue by metabench** [nodejs/nan#487]
The nan project does not link to comprehensive examples.

I suggest including a link to these examples somewhere near the top: https://github.com/nodejs/node-addon-examples

Alternatively I suggest that the project itself contains more comprehensive examples that are self-contained and demonstrate the use of a variety of features.

I can help with putting together examples and documentation of them but I want to know if / how that would fit into this repo (or related ones).

**Comment by kkoopa** [comment]
The tests are rather comprehensive. https://github.com/nodejs/nan/tree/master/test/cpp

**Comment by metabench** [comment]
I am reading that:

    A helper macro NAN_METHOD(methodname) exists, compatible with NAN v1 method declarations.

Is it generally best practise to use the helper macro? I have not seen the non-macro way of doing it in the examples or tests, so I am curious about if there are advantages to not using the macro and if it's worth having more fully-fledged examples of their usage.

Anyway, thanks for pointing me towards the tests. I've now got some code running, and have a better understanding of how I can use the new TypedArrayContents feature.

**Comment by kkoopa** [comment]
It's a matter of personal preference. I say they are equally good, but use the 
macros because they involve less typing, and I know what they do. The reason 
they are there today is more about legacy and they would not be added today if 
they were not already present, but it is not like they are slated for removal 
either. Those macros are there to stay.

**Comment by agnat** [comment]
I added links to both, the node-addon-examples and the C++ test suite to the README in 50e157d54b88bac850df0c955cf775c4e887465e and b19ed7b20fad1f173dc62dc83b96f9bda3819063. Closing.
