### ISSUE TITLE
How to best access TypedArrayContents data as an array?

### ISSUE THREAD

**Issue by metabench** [nodejs/nan#488]
I have made use of the test code for TypedArrayContents. I notice that the data is accessed through a pointer. In code I have written to add one to each item in a typed array, I have:

    (*data)[i] = (*data)[i] + 1;

How can I efficiently cast the data from the TypedArrayContents<double> to an array of doubles?

This does not work:

    double* data2 = static_cast<double*>(data);

Is there an equivalent that would work (if it's clear what I am trying to achieve)?

**Comment by kkoopa** [comment]
*data returns a pointer to the underlying buffer

**Comment by agnat** [comment]
How about `double* data2 = *data;` ... or even `++((*data)[i]);`

**Comment by agnat** [comment]
Ah... what @kkoopa says... ;)

**Comment by metabench** [comment]
@agnat Thanks, `double* data2 = *data;` looks like it does the job.
