### ISSUE TITLE
feature: Non-deferred Function calls

### ISSUE THREAD

**Issue by joshperry** [nodejs/nan#495]
The current `Function::Call` is [soon to be deprecated](https://v8docs.nodesource.com/io.js-3.0/d4/da0/v8_8h_source.html#l03086) and directs embedders to the new overload that takes a `Context` (usually retrieved from the current isolate?) and returns a `MaybeLocal`. 

Nan currently provides a way to make deferred calls to JS functions in a V8/node version independent manner (through `Nan::Callback` which uses `node::MakeCallback`).

It would be nice for Nan to have a primitive for making non-deferred js function calls for when the original `Call` overload is finally deprecated and removed.

**Comment by joshperry** [comment]
See the discussion that I improperly started in #284

**Comment by kkoopa** [comment]
The old Function::Call is already removed. #496

**Comment by joshperry** [comment]
@kkoopa Ah cool. Thanks for that!

Hope starting that conversation over there didn't cause too much confusion :/ kind of new in this neck of the woods.

**Comment by kkoopa** [comment]
No problem. However, you'll want to patch your own code until this is released, which will be when there are enough new features to warrant a new release, maybe in a month or two.

**Comment by joshperry** [comment]
Not a prob. Was just hoping to make the future better for everyone!

Thank you again for your help.

**Comment by kkoopa** [comment]
Good, thanks for reporting this. I had completely missed it.
