### ISSUE TITLE
Receiver parameter for CallAsFunction should be Local<Value>

### ISSUE THREAD

**Issue by cscott** [nodejs/nan#497]
The receiver can be null, so the receiver parameter for `Nan::CallAsFunction` should be `Local<Value>` not `Local<Object>`.  The parameter is declared as `Local<Value>` in v8, it's just Nan which has the overly-restrictive type.

**Comment by kkoopa** [comment]
[No.](https://github.com/nodejs/node-v0.x-archive/blob/v0.8.28/deps/v8/include/v8.h#L1686-L1688)

**Comment by cscott** [comment]
Hm.  JavaScript has changed since the node 0.8.x days.

**Comment by kkoopa** [comment]
Try telling that to the holdouts who refuse to upgrade. Here I am, seemingly stuck with supporting outdated software until the heat death of the universe. [The same goes for 0.10.](https://github.com/nodejs/node/blob/v0.10.40/deps/v8/include/v8.h#L1716-L1718)

**Comment by bnoordhuis** [comment]
It would be possible to emulate it for older versions with something like this:

```c++
Local<Value> recv = /* ... */;
Local<Object> recv_obj;
if (recv->IsUndefined() || recv->IsNull()) {
  recv_obj = Context::Global();
} else {
  recv_obj = recv->ToObject();
}
```

The IsUndefined() and IsNull() checks are cheap, probably cheaper than putting in an extra `if (recv->IsObject())` for the common case.

**Comment by kkoopa** [comment]
Interesting. Would this apply to all the other function-related stuff which has 
the same problem?

**Comment by bnoordhuis** [comment]
What function-related stuff is that?  My comment was mostly in the context of Function::Call().

**Comment by kkoopa** [comment]
I seem to remember a couple other places where there has been a change from Object to Value. Some in V8 some in Node. Maybe MakeCallback? I think there was a bunch of stuff that eventually boiled down to Function::Call.

**Comment by bnoordhuis** [comment]
Oh, like that.  Yes, for consistency the nan wrapper for node::MakeCallback() should get the same treatment.

**Comment by kkoopa** [comment]
After grepping for `v8::Object` it seems these are the ones that need updating:
`CallAsFunction`
`MakeCallback`
`Callback::Call`
`Callback::operator()`
`Call` #496

**Comment by cscott** [comment]
It would be nice to ensure that `(5).toString()` works as well -- I'm not sure if `ToObject` (as @bnoordhuis wrote above) does the full object conversion for primitives.

**Comment by kkoopa** [comment]
`Primitive` is-a `Value` which is where `ToObject` is defined. It's a v8 bug if it does not work.

**Comment by bnoordhuis** [comment]
> I'm not sure if ToObject (as @bnoordhuis wrote above) does the full object conversion for primitives.

It does (or should - like @kkoopa said, it's a V8 bug if it doesn't.)

**Comment by kkoopa** [comment]
http://www.ecma-international.org/ecma-262/5.1/#sec-9.9

**Comment by kkoopa** [comment]
Could not come up with a way to handle the differences between strict and sloppy mode correctly, so this cannot be done until 0.10 support is dropped.
