### ISSUE TITLE
Rethink C++ 11 requirement

### ISSUE THREAD

**Issue by cjbj** [nodejs/nan#500]
Requiring a C++ 11 compatible compiler is problematic for the widely used RHEL 6 and related platforms, e.g. Oracle Linux 6, Centos 6 etc.  

Is this a purely NAN requirement?  If so, can it be rethought?

https://github.com/nodejs/nan/blob/master/nan.h#L41

**Comment by bnoordhuis** [comment]
It's a node.js and V8 requirement.  v8.h for example won't compile with a compiler that doesn't understand C++11.

Closing, nothing we can about it.

**Comment by cjbj** [comment]
@bnoordhuis thanks for the confirmation.

**Comment by kkoopa** [comment]
Yup, but we do not however require C++11 for io.js 2 and older.

**Comment by cjbj** [comment]
@kkoopa that does help the upgrade path.  

Node 4 users will just have to install a newer compiler, e.g. from a Software Collections Library https://docs.oracle.com/cd/E37670_01/E59096/E59096.pdf

**Comment by wyattbiker** [comment]
I am node 4 and 5 user on RHEL. I need to update to C++11. Will the Software Collections Library from oracle work on RHEL 6?. Unfortunately I don't have access to the RHELs devtools repository.

**Comment by rvagg** [comment]
Why are you using RHEL if you don't have access to devtools? Perhaps you should be using CentOS instead.

Regardless, I believe you should be able to just use CERNs devtoolset versions, try 2.0 for EL 6: http://linux.web.cern.ch/linux/devtoolset/, this is what we use to build and test on CentOS 5 & 6.
