### ISSUE TITLE
Memory leak when using asynch

### ISSUE THREAD

**Issue by oferh** [nodejs/nan#501]
I've created a minimal asynchronous addon based on async_pi_estimate and ran it in a loop. It appears that there is a memory leak when using it because the code itself doesn't allocate dynamic memory but after running 200K iterations the memory footprint is as follows:
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                          
29684 ofer      20   0  813.3m 161.8m   7.1m S   0.0  2.0   0:03.29 node   

The code is available [in this gist](https://gist.github.com/oferh/bdde17c52f5bc97fdd42)

Node version: 0.12.7

**Comment by kkoopa** [comment]
Nothing there indicates a leak.

**Comment by oferh** [comment]
It looks as if there is no reuse of resources it's strange that the RES memory reaches 150M for it, but it might be my misunderstanding of how node/V8 allocates memory.
 
Changed the test to make 2 iterations of 2K calls each and the memory consumption goes higher between each iteration.

``` 
var addon = require('../');

for (var i=0; i<2000; i++){
  addon.asynctest(function(){});
}
global.gc();

for (var i=0; i<2000; i++){
  addon.asynctest(function(){});
}

global.gc();
```

This is the output after the first iteration:
```
==28951== LEAK SUMMARY:
==28951==    definitely lost: 288 bytes in 1 blocks
==28951==    indirectly lost: 0 bytes in 0 blocks
==28951==      possibly lost: 7,241 bytes in 51 blocks
==28951==    still reachable: 1,084,994 bytes in 222 blocks
==28951==         suppressed: 0 bytes in 0 blocks
```

And this is the output after the 2nd one:
```
==28966== LEAK SUMMARY:
==28966==    definitely lost: 288 bytes in 1 blocks
==28966==    indirectly lost: 0 bytes in 0 blocks
==28966==      possibly lost: 7,241 bytes in 51 blocks
==28966==    still reachable: 1,249,474 bytes in 238 blocks
==28966==         suppressed: 0 bytes in 0 blocks
```

**Comment by kkoopa** [comment]
You have not mentioned which version of Node this is, but I'll assume it's 4. Does not really matter, though, since I would not expect RSS to decrease here. https://github.com/nodejs/node/issues/2631#issuecomment-136599492
> small chunks are allocated using sbrk and are not returned to the system (rss does not decrease)

You can also run node with --trace-gc to see when garbage collection happens. For reference, [last time we had an actual leak](https://github.com/nodejs/nan/issues/389), the system ran out of memory in 15 to 30 minutes.

**Comment by oferh** [comment]
Tried the same loop as in nodejs/node#2631 and it crashes after ~15 sec `FATAL ERROR:CALL_AND_RETRY_LAST Allocation failed - process out of memory`

**Comment by oferh** [comment]
Looks like it's a nodejs issue not NAN http://stackoverflow.com/questions/33346385/how-can-i-use-uv-queue-work-multiple-times
