### ISSUE TITLE
what version of g++ on ubuntu?

### ISSUE THREAD

**Issue by zzo** [nodejs/nan#506]
On ubuntu 14.04 LTS g++ 4.7 and 4.8 identify themselves as 199711 but NAN wants 201103 - what g++ compiler on ubuntu satisfies that??  thanks!!

**Comment by bnoordhuis** [comment]
g++ 4.8 should be good although you may need 4.8.2 for it to be entirely reliable.  You need to compile with `-std=c++11` for `__cplusplus >= 201103` but you get that for free when you target node.js >= 4.

**Comment by mzgol** [comment]
I see node-sass is also upgrading gcc in addition to g++ but most packages just upgrade g++. Is upgrading g++ enough in general?

**Comment by bnoordhuis** [comment]
You don't need gcc for nan, just g++.  Is node-sass part C library?

**Comment by mzgol** [comment]
> Is node-sass part C library?

Directly - I don't think so, but [libsass](https://github.com/sass/libsass) that's wrapped by `node-sass` [does have some C code](https://github.com/sass/libsass/blob/4cf371cdc6723d52ad32c1c5533af1be350db4e0/src/cencode.c).

**Comment by mzgol** [comment]
The g++-4.8 package that's included in the `ubuntu-toolchain-r-test` package is 4.8.1 so not 4.8.2+ but it still seems to compile stuff correctly as opposed to older versions: https://travis-ci.org/karma-runner/karma/jobs/88390153

I see the newest version is 5.1, would that be OK? What are the problems with 4.8.1?

Sorry for asking so many questions...

**Comment by bnoordhuis** [comment]
4.8.0 and 4.81 had some minor bugs.  If it builds and runs fine, don't worry about it.  5.1 is OK too.
