### ISSUE TITLE
memory leaks in examples/async_pi_estimate/async.cc ?

### ISSUE THREAD

**Issue by nickdesaulniers** [nodejs/nan#509]
Hi, I'm curious, looking at the [async pi example](https://github.com/nodejs/nan/blob/master/examples/async_pi_estimate/async.cc), who calls `delete` on the [callback](https://github.com/nodejs/nan/blob/master/examples/async_pi_estimate/async.cc#L61) and the [PiWorker](https://github.com/nodejs/nan/blob/master/examples/async_pi_estimate/async.cc#L63)?

I'm trying to track down what looks to me like a memory leak in https://github.com/MayhemYDG/iltorb/issues/3, but the logs I'm getting from valgrind are tough to decipher.

**Comment by nickdesaulniers** [comment]
ok, looks like deletion of the callback: https://github.com/nodejs/nan/blob/9f42b4cf3126f5c732c5556193e3ac70b566ba64/nan.h#L1491-L1496

and of the worker

https://github.com/nodejs/nan/blob/9f42b4cf3126f5c732c5556193e3ac70b566ba64/nan.h#L1696-L1699
https://github.com/nodejs/nan/blob/9f42b4cf3126f5c732c5556193e3ac70b566ba64/nan.h#L1502-L1511
https://github.com/nodejs/nan/blob/9f42b4cf3126f5c732c5556193e3ac70b566ba64/nan.h#L1552-L1554
https://github.com/nodejs/nan/blob/9f42b4cf3126f5c732c5556193e3ac70b566ba64/nan.h#L1491-L1500

hmm, everything looks ok from here.  I'll look elsewhere.

**Comment by kkoopa** [comment]
Yup, they need to be heap allocated to stay alive long enough. The pattern is somewhat strange, but they do get cleaned up in the end.

**Comment by nickdesaulniers** [comment]
Thanks, can you think of any tricks to help me debug out-of-v8-heap leaks?  I used node-debug to take a heap snapshot, but the heap was only 9.8 MB, so I don't think I'm leaking memory allocated on v8's heap.

**Comment by kkoopa** [comment]
Valgrind.

**Comment by kkoopa** [comment]
These definitely leak, since the persistent handle is never reset. Why are there no destructors defined anywhere?
https://github.com/MayhemYDG/iltorb/blob/master/src/dec/stream_decode.cc#L21
https://github.com/MayhemYDG/iltorb/blob/master/src/enc/stream_encode.cc#L22

**Comment by nickdesaulniers** [comment]
check branch mem

**Comment by thejinx0r** [comment]
@kkoopa 
Can you clarify why you think it would leak?
Maybe the lines have changed, but why would not resetting the template constructor leak?
For the destructor, do you mean the C++ one or is there a v8 destructor in objectwrap?  

I'm trying to track down some memory leaks as well in [https://github.com/c4milo/fusejs](https://github.com/c4milo/fusejs/blob/master/src/file_info.cc), and I see the patterns are the same for the class definition.

**Comment by kkoopa** [comment]
It was a false alarm. They are declared static, so they don't leak.
