### ISSUE TITLE
Unable to call Pass for Nan::Global under v0.10.x

### ISSUE THREAD

**Issue by mikemorris** [nodejs/nan#517]
Only seeing the error below compiling against Node.js v0.10.x, not when compiling against Node.js v4.x:

```
../node_modules/nan/nan_persistent_pre_12_inl.h:213:38: error: member
      reference type 'Nan::Global<v8::Object> *' is a pointer; maybe you meant
      to use '->'?
    : PersistentBase<T>(rvalue.object.persistent) {
                        ~~~~~~~~~~~~~^
                                     ->
../node_modules/nan/nan_persistent_pre_12_inl.h:234:26: note: in instantiation
      of member function 'Nan::Global<v8::Object>::Global' requested here
  Global Pass() { return Global(RValue(this)); }
                         ^
```
Refs #470

**Comment by kkoopa** [comment]
I can't take a closer look at it right now, but I know there is no test for Global::Pass or much anything for Global, sincenobody really uses it (yet). There are some known issues with the current implementstion. Anyway, try doing as the compiler says and change the offending line to pointer member access and see if it works.
