### ISSUE TITLE
Persistent smart pointer operations inaccessible

### ISSUE THREAD

**Issue by heaths** [nodejs/nan#522]
I was pointed to NAN via node-gyp, but unfortunately I see that `Persistent<T, M>` still has the `*` operator marked as private, which is the problem I'm having in Node 4. Other sample code that was built against Node 0.x was able to access the prototype and instance templates in cases like this:

``` c++
Persistent<FunctionTemplate> constructor = Persistent<FunctionTemplate>::New(FunctionTemplate::New(MyWrapper::New));
constructor->InstanceTemplate()->SetInternalFieldCount(1);
// ...
```

(I realize in newer code I must pass an `Isolate*`, but that doesn't change what's accessible.)

Unfortunately, I see in your `Persistent<T, M>` that it's still private. To support version-agnostic code, shouldn't this be public?

**Comment by bnoordhuis** [comment]
You don't directly dereference the persistent handle, instead you create new local handle from it:
```c++
v8::Local<v8::Value> local_handle = Nan::New(persistent_handle);
```
