### ISSUE TITLE
Strange callback behavior

### ISSUE THREAD

**Issue by Izzatbek** [nodejs/nan#523]
I have a wrapped object which calls callbacks in the main thread asynchronously when a certain event occurs. Please tell me what's wrong. I noticed the following behavior:

I call callbacks using Call of `Nan::Callback`. Everything is working. However, if the object must be garbage collected, I noticed that its destructor is called right before the callback must be called. And sometimes there is a Seg Fault. I guess this behavior is not normal? Is it because the callback is being called in the next tick and the destructor is called first?

The interesting thing is that the object's destructor is not being called when I do not use callbacks (Is it normal?). Maybe it's because the GC was not triggered somehow.

**Comment by agnat** [comment]
> I guess this behavior is not normal?

No, not normal. But it is virtually impossible to debug this without looking at the source. TBH, it does not sound like an error in NAN but more like a programing error on your end. Note, that it is not safe to use `Nan::Callback` across thread boundaries. You have to do your own synchronization and lifetime management.

I'm going to close this. If you want to follow up with a more specific question, feel free to reopen, though.
