### ISSUE TITLE
nan header errors when building for Node Webkit v0.8.6 using Node v0.10

### ISSUE THREAD

**Issue by jpcharlesworth** [nodejs/nan#525]
I am reporting this issue here because it appears that there may be a problem with one of the files in this repository.
 
I have been building the node sqlite3 module (from source) for different combinations of versions of Node and Node Webkit

I am running Windows 10 and using Visual Studio Express 2013. In order to get the builds to run I had to work from the developer console of the Visual Studio 2013 Tools

Using Node versions 0.12.9 or 4.2.3, I have been able to build for Node Webkit v0.12.3 with only two warnings and no errors.

However, if I try to build for Node Webkit v0.8.6 using Node versions 0.10.26 or 0.10.41, I always get three compile errors arising from the file nan_implementation_pre_12_inl.h. It appears that successful builds do not use this header, using nan_implementation_12_inl.h instead.

Since my intention is to migrate from Node Webkit v0.8.6 to v0.12.3 this outcome is satisfactory but I thought it worth reporting the problem, for the record. Details of the compile errors can be found in the attached file.
[nan_errors.txt](https://github.com/nodejs/nan/files/62437/nan_errors.txt)

**Comment by agnat** [comment]
Heh, thanks for the report. However, I'm pretty sure it is a Node Webkit issue. Apparently Node Webkit, namely `nw-gyp` downloads its header files from here: http://node-webkit.s3.amazonaws.com/v0.8.6/nw-headers-v0.8.6.tar.gz

These headers indeed have two signatures for `v8::FunctionTemplate::New(...)`: 
````
  V8_DEPRECATED(static Local<FunctionTemplate> New(
      InvocationCallback callback,
      Handle<Value> data = Handle<Value>(),
      Handle<Signature> signature = Handle<Signature>(),
      int length = 0));
  static Local<FunctionTemplate> New(
      FunctionCallback callback = 0,
      Handle<Value> data = Handle<Value>(),
      Handle<Signature> signature = Handle<Signature>(),
      int length = 0);
````

That looks odd. IIRC, the change from `InvocationCallback` to `FunctionCallback` was a hard switch. And indeed the vanilla v8 headers shipping with node v0.10.41 only have:
````
  static Local<FunctionTemplate> New(
      InvocationCallback callback = 0,
      Handle<Value> data = Handle<Value>(),
      Handle<Signature> signature = Handle<Signature>());
````
... while later versions only have `FunctionCallback`. So, it looks a bit like the Node Webkit people tampered with the v8 header files and botched it... back in the day. They probably (hopefully!) stopped doing that. ;)

Closing.

**Comment by agnat** [comment]
We probably could nudge our code to compile under these conditions. But it's obscure and I'd rather not unless it is a real world issue...

**Comment by jpcharlesworth** [comment]
@agnat 

Many thanks for your prompt reply and explanation. I hadn't realised that the headers had likely been modified by Node Webkit but I will draw your information to their attention.
