### ISSUE TITLE
Can AsyncWorker declared in another thread?

### ISSUE THREAD

**Issue by XadillaX** [nodejs/nan#526]
For some reason (closed source SDK), I must run some code in another thread because that thread is packaged.

And here's my code:

```c++
Action ONSListenerV8::consume(Message message, ConsumeContext context)
{
    Message* m = new Message(message);
    ThreadConsumeWorker* worker = new ThreadConsumeWorker(
            parent->GetListenerFunc(),
            *parent,
            m);

    // Nan::AsyncQueueWorker(new ThreadConsumeWorker(
    //             parent->GetListenerFunc(),
    //             *parent,
    //             new Message(message)));

    return CommitMessage;
}
```

`consume` is called in a new thread via the SDK, and this code throwed a segmentfault.

So I'm confused can `AsyncWorker` run in another thread?

**Comment by bnoordhuis** [comment]
No, `Nan::AsyncQueueWorker()` is supposed to be called from the main thread.

If you want to wake up the main thread from another thread, you'll have to jury-rig something using `uv_async_send()`.  Note that the `uv_async_t` handle should be initialized on the main thread first.  Good luck.

**Comment by XadillaX** [comment]
@bnoordhuis So how can I get the loop? Use `uv_default_loop`? Or via other function of Node.js?

**Comment by fivdi** [comment]
@XadillaX although it's probably not perfect maybe you can get some ideas from https://github.com/fivdi/epoll/blob/v0.1.16/src/epoll.cc. Search for all occurrences of `async_g` to see what's going on.

**Comment by bnoordhuis** [comment]
@XadillaX `uv_default_loop()` yes, from the main thread.

**Comment by XadillaX** [comment]
@bnoordhuis Thanks!
