### ISSUE TITLE
Error: Cannot find module 'nan'

### ISSUE THREAD

**Issue by yarax** [nodejs/nan#528]
Hi!
I'm working on native addon https://github.com/yarax/multi_request  and following nan docs I included nan into binding.gyp like:
`"include_dirs" : [
 	 			"<!(node -e \"require('nan')\")"
			]`
Also nan is in npm dependencies.
But when I install the package inside the another one (https://github.com/yarax/stress/blob/master/package.json) node-gyp is failed with error
```
> nnb@1.0.2 install /Users/Shopgate/sandbox/stress/node_modules/nnb
> node-gyp rebuild

module.js:338
    throw err;
          ^
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)
    at startup (node.js:90:7)
gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
```

**Comment by grahambinns** [comment]
I'm also seeing this when trying to install xpc-connection on OSX.

**Comment by rvagg** [comment]
are you still having this problem @yarax? can you tell us _how_ you are installing one inside the other and how you are using `npm` to do this? it's possible that it's not installing at the right level and completely removing `node_modules` and doing an `npm install` from scratch may fix it all up for you.

**Comment by yarax** [comment]
Hi @rvagg 
Not anymore. Probably it was my fault

**Comment by sempasha** [comment]
Hi!
I've came into this issue while [bunyan-syslog](https://github.com/mcavage/node-bunyan-syslog) package installation. bunyan-syslog is a second level dependency for my app.

```bash
$ npm -v
2.14.12

$ node -v
v4.3.0

$ npm install
...

> bunyan-syslog@0.3.1 install /app/node_modules/bunyan-syslog
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.3
gyp info using node@4.3.0 | linux | x64
gyp info spawn python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/app/node_modules/bunyan-syslog/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/4.3.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/4.3.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/app/node_modules/bunyan-syslog',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
module.js:328
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:410:26)
    at node.js:578:27
    at nextTickCallbackWith0Args (node.js:419:9)
gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-coreos-r2
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/bunyan-syslog
gyp ERR! node -v v4.3.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

...

**Comment by rvagg** [comment]
@sempasha can you `rm -rf node_modules` and `npm install` again and see if that makes a difference? If not, when what does `node -e "require('nan')"` show you when you `cd` to `/app/node_modules/bunyan-syslog`? And do you see `nan` in `/app/node_modules/bunyan-syslog/node_modules` or `/app/node_modules/` (the latter unlikely with npm v2 but v3 would do this).

**Comment by sempasha** [comment]
@rvagg `rm -rf ./node_modules` is the only way I had resolved an issue.
I can't remember what exactly, but there was some symlinks, that was the reason.
Sorry for long reply.

**Comment by baboundu81** [comment]
Hi, I'm having the same issue but rm -rf ./node_modules don't solve the issue. Moreover, if I run the command 

`node -e "require('nan')"`

I get the following result :

`application-path/node_modules/nan`

So I get no error, but the path to the nan module in the directory of my application.
But if I run the same dommand from the directory of node-gyp.js I get an error.

Does anyone know what I'm doing wrong ?

Thanks in advance.

**Comment by rk-lakshmanan** [comment]
Hi, maybe you can try replacing node -e "require('nan')" with nodejs -e "require('nan')" in the binding.gyp file.

**Comment by lukuilian** [comment]
It is fixed by run 'yarn add nan'
