### ISSUE TITLE
Typedarray to double*

### ISSUE THREAD

**Issue by amatosc** [nodejs/nan#530]
I try to convert a Array from JS to array in C. I pass the array but when I try to read the elements in the new array there are invalid. This is a bit of my code.

JS file

 `var AA = util.toArray(A); // This function return a Float32Array`
  `addon.test(AA, 5, 3);`
AA output :

` {'0': 9,
  '1': 8,
  '2': 9,
  '3': 4,
  '4': 1,
  '5': 6,
  '6': 3,
  '7': 2,
  '8': 7,
  '9': 4,
  '10': 4,
  '11': 3,
  '12': 1,
  '13': 0,
  '14': 0 }`

C file

` // m = 5;
 // n = 3;
double * A = (double *) malloc(sizeof(double) * (m * n));
TypedArrayContents<double> data_A(argv[0]);
A = *data_A;`

A output :

`Position -> 0, value -> 131072.031769.  
Position -> 1, value -> 512.000124.  
Position -> 2, value -> 8192.001938.  
Position -> 3, value -> 2.000000.  
Position -> 4, value -> 512.000124.  
Position -> 5, value -> 32.000008.  
Position -> 6, value -> 0.000000.  
Position -> 7, value -> 0.000000.  
Position -> 8, value -> 0.000000.  
Position -> 9, value -> 0.000000.  
Position -> 10, value -> 0.000000.  
Position -> 11, value -> 0.000000.  
Position -> 12, value -> 0.000000.  
Position -> 13, value -> 0.000000. 
Position -> 14, value -> 0.000000.`

http://stackoverflow.com/questions/34655518/nan-typedarray-to-double-c

**Comment by kkoopa** [comment]
You are doing it wrong. What you do now is allocate a block of memory and ensure it 
will leak by getting rid of the only pointer to it, without actually using it. A pointer 
assignment is not the same as a memory copy.

What you want is something like this:

double *A = new double[m * n];
TypedArrayContents<double> data_A(argv[0]);
std::memcpy(A, *data_A, m * n * sizeof (double));
...
delete[] A;

**Comment by amatosc** [comment]
I fixed the problem, I changed `Float64Array` in instance of `Float32Array` and it worked. I note my problem with malloc as well I just comment this line for fix it.
