### ISSUE TITLE
Should I delete an object created in another thread manually?

### ISSUE THREAD

**Issue by XadillaX** [nodejs/nan#534]
Here's an other thread's function:

```javascript
Action ONSListenerV8::consume(Message message, ConsumeContext context)
{
    ONSConsumerACKV8* ack = new ONSConsumerACKV8();

    Message* m = new Message(message);
    MessageHandlerParam* param = new MessageHandlerParam();
    param->message = m;
    param->ons = parent;
    param->ack = ack;
    async->data = (void*)param;
    uv_async_send(async);

    printf(">>>>> wait: 0x%X\n", ack);
    Action result = ack->WaitResult();
    printf(">>>>> refs: 0x%x %d <<<<<\n", ack, ack->refs_);

    return result;
}
```

The `ONSConsumerACKV8` extends from `Nan::ObjectWrap`.

And here's v8 loop (reciever of `uv_async_send`):

```javascript
void ONSConsumerV8::HandleMessage(uv_async_t* handle)
{
    Nan::HandleScope scope;

    MessageHandlerParam* param = (MessageHandlerParam*)handle->data;

    Message* message = param->message;
    ONSConsumerV8* ons = param->ons;
    ONSConsumerACKV8* ack = param->ack;

    // create ack object
    v8::Local<v8::ObjectTemplate> ack_templ = Nan::New<v8::ObjectTemplate>();
    ack_templ->SetInternalFieldCount(1);
    Nan::SetMethod<v8::Local<v8::ObjectTemplate>>(ack_templ, "done", ONSConsumerACKV8::Done);
    v8::Local<v8::Object> ack_obj = ack_templ->NewInstance();
    ack->Wrap(ack_obj);

    v8::Local<v8::Object> result = Nan::New<v8::Object>();
    result->Set(
            Nan::New<v8::String>("topic").ToLocalChecked(),
            Nan::New<v8::String>(message->getTopic()).ToLocalChecked());
    result->Set(
            Nan::New<v8::String>("tag").ToLocalChecked(),
            Nan::New<v8::String>(message->getTag()).ToLocalChecked());
    result->Set(
            Nan::New<v8::String>("key").ToLocalChecked(),
            Nan::New<v8::String>(message->getKey()).ToLocalChecked());
    result->Set(
            Nan::New<v8::String>("msgId").ToLocalChecked(),
            Nan::New<v8::String>(message->getMsgID()).ToLocalChecked());
    result->Set(
            Nan::New<v8::String>("startDeliverTime").ToLocalChecked(),
            Nan::New<v8::Number>(message->getStartDeliverTime()));
    result->Set(
            Nan::New<v8::String>("body").ToLocalChecked(),
            Nan::New<v8::String>(message->getBody()).ToLocalChecked());
    result->Set(
            Nan::New<v8::String>("reconsumeTimes").ToLocalChecked(),
            Nan::New<v8::Number>(message->getReconsumeTimes()));

    printf(">>>> refs: 0x%x %d\n", ack, ack->refs_);
    v8::Local<v8::Value> argv[3] = { Nan::Undefined(), result, ack_obj };
    Nan::Callback* callback = ons->GetListenerFunc();
    callback->Call(3, argv);

    delete param->message;
    delete param;
}
```

The question is:

> Should I delete an object created in another thread manully?

**Comment by XadillaX** [comment]
The situation is:

An closed-source C++ SDK created another thread to receive messages outside.

`HandleMessage` will be called when a message received and this function must return ACK information (YES or NO).

I created an ACK object for Javascript `callback` (`v8::Local<v8::Value> argv[3] = { Nan::Undefined(), result, ack_obj };`, the 3rd object) and export `done` to Javascript `callback`.

The other thread wait for develop call `done` in `callback`.

At last, what shall I do with `ONSConsumerV8` object? Delete it manully or just leave it and wait for GC?

**Comment by bnoordhuis** [comment]
> The ONSConsumerACKV8 extends from Nan::ObjectWrap.

If that is the case, you shouldn't create the object on a different thread.  It probably works now by accident but it's not sound and may start failing in the future.

> Should I delete an object created in another thread manully?

If you Wrap() the object, nan will take care of destroying it but caveat emptor: the object is eligible for garbage collection only when there are no references to it.

The collector may not run between creation of the object and program exit.  If it's paramount that the object is deallocated, do it manually.

**Comment by XadillaX** [comment]
@bnoordhuis But the problem is I must create it on another thread because that thread is not created by me, it was created by the closed-source SDK.

**Comment by XadillaX** [comment]
@bnoordhuis So could I create it on another thread and add ref manually?

And after all work done, unref it by myself.

**Comment by bnoordhuis** [comment]
I'd change `ONSConsumerACKV8` so it no longer inherits from `Nan::ObjectWrap`.  You can always wrap it in a `Nan::ObjectWrap`-derived class on the main thread.

**Comment by XadillaX** [comment]
@bnoordhuis 

> I'd change ONSConsumerACKV8 so it no longer inherits from Nan::ObjectWrap. You can always wrap it in a Nan::ObjectWrap-derived class on the main thread.

So what shall I do after all work done and then I should delete `ONSConsumerACKV8` in a different thread if I use this solution?

**Comment by bnoordhuis** [comment]
Are you saying `ONSConsumerACKV8` needs to be deleted on the same thread that created it?

**Comment by XadillaX** [comment]
@bnoordhuis Thx, I've solved it now!

I passed `ONSConsumerACK` into `Nan::ObjectWrap` as a member variable and after works done, I set that member to `NULL` and then delete `ONSConsumerACK` object manually.
