### ISSUE TITLE
Make while loop non blocking / asyncronous

### ISSUE THREAD

**Issue by MarshallOfSound** [nodejs/nan#543]
So I'm I am trying to make a node module for low level keyboard hooks.  I have got to the point where keycodes are being passed back into node.js though a callback.  But the keyboard hook is blocking (relies on a while loop to stay alive)

Can someone point me in the right direction for implementing this functionality inside an AsyncWorker or something similar?

What I have so far:
https://gist.github.com/MarshallOfSound/e9af90430832d2fbc370

**Comment by MarshallOfSound** [comment]
If I get rid of the while loop, all key presses are just absorbed and you have to force kill the process to get key input back again

**Comment by kkoopa** [comment]
Depending on what you desire, the answer is one of `uv_timer_t`, `uv_check_t` or `uv_async_t`.

**Comment by seanzer** [comment]
From what I understand, you can move that code into the body of Execute in an AsyncProgressWorker, but I'm having the challenge of figuring out how to pump GetMessage when nodejs is about to return... You still need to have a stop function or call process.exit

**Comment by MarshallOfSound** [comment]
For reference I got this working with `uv_async` and such

https://github.com/MarshallOfSound/node-lowlevel-keyboard-hook-win/blob/master/ll_keyboard_hooks.cc
