### ISSUE TITLE
Changes for Nodejs v6?

### ISSUE THREAD

**Issue by iWuzHere** [nodejs/nan#546]
Hi,

I would like to get involved with contributing to this project and Nodejs v6 should be around the corner (scheduled to release in april).
Is there any work to be done to update nan for compatibility with v6?

**Comment by rvagg** [comment]
I believe we're sailing pretty smooth toward v6, check out https://docs.google.com/document/d/1g8JFi8T_oAE_7uAri7Njtig7fKaPDfotU6huOa1alds for what V8 are doing and also try compiling against nodejs/node master or a v6.0.0 nightly from https://nodejs.org/download/nightly/ which comes off master. We are only up to v4.9 in master at the moment but will hopefully hit v5.0 by v6.0.0 but it'll be tight.

If you have time to spare you could try seeing how popular downstream users of nan fare when compiling against node master (`--nodedir` will come in handy when rebuilding with npm or node-gyp).
