### ISSUE TITLE
 error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’

### ISSUE THREAD

**Issue by koocotte** [nodejs/nan#551]
Trying to use nan (build scrypt-hash), I have this error:

    In file included from ../node_scrypt.cc:3:0:
    ../node_modules/nan/nan.h:316:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
    static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;

Refering to this code: 

    310   // v8::String::REPLACE_INVALID_UTF8 was introduced
    311   // in node.js v0.10.29 and v0.8.27.
    312 #if NODE_MAJOR_VERSION > 0 || \
    313     NODE_MINOR_VERSION > 10 || \
    314     NODE_MINOR_VERSION == 10 && NODE_PATCH_VERSION >= 29 || \
    315     NODE_MINOR_VERSION == 8 && NODE_PATCH_VERSION >= 27
    316   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
    317 #else
    318   static const unsigned kReplaceInvalidUtf8 = 0;
    319 #endif

I'm on debian jessie, with 0.10.29~dfsg-2 and I can't find REPLACE_INVALID_UTF8 anywhere.

**Comment by fivdi** [comment]
See [this comment](https://github.com/nodejs/nan/issues/394#issuecomment-135793288) and the responses following it.

**Comment by kkoopa** [comment]
That sums it up. Broken builds are not supported. [Get a proper build](https://github.com/nodesource/distributions).

**Comment by koocotte** [comment]
Thanks

**Comment by ScottChapman** [comment]
Sorry for being dense, but from the distro page, which version do I need exactly?

**Comment by kkoopa** [comment]
Try updating  `node-gyp` by `npm update -g node-gyp`.

**Comment by ScottChapman** [comment]
I'm on current Rasperrby Pi Jessie (installed/updated today).

**Comment by ScottChapman** [comment]
I just man-handled the header file to include the flag, rebuilding now..
