### ISSUE TITLE
ReturnValue<T>::Set(uint32_t i) does not preserve unsignedness on 0.10

### ISSUE THREAD

**Issue by smilingthax** [nodejs/nan#552]
One would expect this code:

     info.GetReturnValue().Set((uint32_t)0xffffffff);

to produce the same result as

    info.GetReturnValue().Set(Nan::New((uint32_t)0xffffffff));

on nodejs 0.10, but it does not. In the first case the returned value is -1, in the second case it's 4294967295.
Nodejs 5.0 returns the positive value in both cases.

In `nan_implementation_pre_12_inl.h` we see (the code in `nan_implementation_12_inl.h` is essentially the same):
```
Factory<v8::Uint32>::return_t
Factory<v8::Uint32>::New(uint32_t value) {
  return To<v8::Uint32>(v8::Uint32::NewFromUnsigned(value));
}
```

But the Implementation of `ReturnType<T>` in `nan_callbacks_pre_12_inl.h`:
```
  inline void Set(uint32_t i) {
    TYPE_CHECK(T, v8::Integer);
    value_->Dispose();
    *value_ = v8::Persistent<T>::New(v8::Uint32::New(i));
  }
```
does not use `v8::Uint32::NewFromUnsigned`, but straight `v8::Uint32::New`.
Changing `New` to `NewFromUnsigned` **fixes** the behavior. 

`nan_callbacks_12_inl.h` just forwards to v8:
https://github.com/v8/v8/blob/master/include/v8.h#L7708
which uses `Integer::NewFromUnsigned` (in this latest version).

There has been one noteworthy change to v8's `ReturnValue::Set(uint32_t)` since it's introduction: https://github.com/v8/v8/commit/3c8a79cabadeaa8c356b7789a8b621464d643b2d - but I'm not sure of its implications.

**Comment by kkoopa** [comment]
You seem to be correct. Would you like to submit a patch and a test case?
