### ISSUE TITLE
AsyncProgressWorker.Destroy causes node to hang

### ISSUE THREAD

**Issue by seanzer** [nodejs/nan#556]
Following the code in [asyncprogressworker.cpp](https://github.com/nodejs/nan/blob/master/test/cpp/asyncprogressworker.cpp), but it seems like nodejs never quits after executing the callback. This is on Windows. Is this expected? How do I get nodejs to return after `Execute()` and `Destroy()` return?

**Comment by bnoordhuis** [comment]
Can you provide more details or even better, a way to reproduce what you're describing?

**Comment by seanzer** [comment]
I've updated the title, but I was able to figure out that having a Destroy implementation causes the process to stick around. Is there an example of what Destroy should do?

**Comment by kkoopa** [comment]
https://github.com/nodejs/nan/blob/master/nan.h#L1558-1560

**Comment by seanzer** [comment]
Thanks, that should have been obvious. My mistake
