### ISSUE TITLE
Object going out of scope during the execution of it's Async method

### ISSUE THREAD

**Issue by SudershanReddy** [nodejs/nan#567]
Our application creates an object and executes an Async method on it. This works fine with less load. But if we run the application with huge concurrent load using ab tool then we have seen crashes. After some investigation we found that the Object is garbage collected even before Async call finished which results a crash.

Please suggest how to solve this problem ?.
We are having an idea of keeping a persistent reference to the object in the driver while executing an Async method. is this fine or any better solutions exist ?

**Comment by SudershanReddy** [comment]
[sample.zip](https://github.com/nodejs/nan/files/252094/sample.zip)
Steps to reproduce the issue:
unzip sample.zip
Add node-gyp and node in the PATH
set the NODE_PATH to work_dir/lib
npm install
node examples/webapp.js
ab -c 30 -n 100000 http://localhost:8133/

**Comment by Flarna** [comment]
I think keeping a persistent handle of nanSampleSub in nanSampleSubBaton is the way to go here.
If you look at Nan::AsyncWorker helper you will see it offers SaveToPersistent() apis to support you in this.

**Comment by pvenkatraman** [comment]
But why the object is going out of scope here.  The async method is being executed and all of suddenly the object is gone out-of-scope does not sound right.  Any theories? Thx

**Comment by kkoopa** [comment]
The garbage collector destroys it, since there are no references to it.

**Comment by Flarna** [comment]
The object returned in the callback of ns.getnanSampleSub() is used in JS code only to call PrintHello(). JS has no need to keep the object until until PrintHello() returns as it's not used/referenced anymore.
But it's still used in native but there is only a persistent reference to the callback stored not to the object which holds the async uv operation.
