### ISSUE TITLE
How to convert argument into std::vector<double>, std::string, double, etc

### ISSUE THREAD

**Issue by JerryYangJin** [nodejs/nan#575]
Hello, I'm using `nan 2.2.1`, `node 4.4.5`

I need to convert argument `info[n]` into different c++ types, like `double`, `std:string`, `std::vector<double>`

e.g.
`js array [1.0,1.1,1.2,1.3,1.4,1.5]` -> `std::vector<double>`
`js number 3.14` -> `double 3.14`
`js string` -> `std:string`

How to do the type conversion using nan? thanks!

**Comment by bnoordhuis** [comment]
Before I answer your question, have you read the documentation?  Were parts unclear and if so, why?

**Comment by JerryYangJin** [comment]
hello @bnoordhuis, I read document, I know how to do `info[n]->ToNumber` or `ToString`, and just found `Nan::Maybe<double> Nan::To<double>(v8::Local<v8::Value> val);`
How about `Array` to `std::vector` and `String` to `std::string` ? thanks!

**Comment by bnoordhuis** [comment]
> Array to std::vector

You get the elements with `nan::Get(array, index)` and put them in your std::vector.  `Get()` returns a `nan::MaybeLocal<v8::Value>` so you may have to unwrap the return value first.

> String to std::string

`nan::Utf8String` and then you create a std::string from that.

**Comment by JerryYangJin** [comment]
@bnoordhuis  thanks a lot!
