### ISSUE TITLE
Assertion failed: length <= kMaxLength, file src\node_buffer.cc, line 400

### ISSUE THREAD

**Issue by s-a** [nodejs/nan#583]
![image](https://cloud.githubusercontent.com/assets/1270662/16011614/8af19080-3186-11e6-9415-8d7fb7a50ef6.png)

I do not know C++ .  I use an existing lib coded by a co worker. Any chance to get stacktrace info to figure out where the problem might be in my source?

**Comment by kkoopa** [comment]
Without knowing C++ and having access to a debugger, not too easily. The problem stems from creating a too large `Buffer` as part of a native function. Go through the calls you make to said library and find where the problem is.
