### ISSUE TITLE
Node silent crash

### ISSUE THREAD

**Issue by s-a** [nodejs/nan#585]
I am stumbling on a crash behavior in my native module where I think I missed something important to do in C++ code but have no idea what is wrong. I orientated my code on examples at https://github.com/nodejs/nan/tree/master/examples/async_pi_estimate. 

I created a minimalistic reproducable example at https://github.com/s-a/node-native-async-test/blob/master/test.js where the expected console output is [```YEAAAAAH```](https://github.com/s-a/node-native-async-test/blob/master/test.js#L13) but the node instance crash silently :cry: 

 - [ ] Can anyone point me to the right direction what I am doing wrong there? 
 - [x] How to catch errors in asnc native modules to force node to exit through ```uncaughtException```?

**Comment by Flarna** [comment]
I would expect that the Buffer you pass from JS to native gets garbage collected soon after returning from the `addon.calculateAsync()` call as there are no references left (visible to V8).
Your worker has still a pointer to this memory area (member points) but it is not allowed to access this after it was freed.

Issues like this will never result in a JS exception as the process gets terminated immediately - a classic crash.

To get JS exceptions from native you have to create and pass them explicit via API calls (e.a. `Nan::ThrowError()`).

**Comment by s-a** [comment]
My worker returns a buffer a few times. So in generell there might be access permission outside. Do you know how handle Input output buffers with nan? I am   missing an example online which fits my needs.

**Comment by fivdi** [comment]
[This](https://github.com/nodejs/nan/blob/master/test/cpp/bufferworkerpersistent.cpp) may help.

**Comment by s-a** [comment]
By the way this is a pretty cool code directory. The sample looks promising. Thanks.

**Comment by s-a** [comment]
In fact working with ```SaveToPersistent``` and ```GetFromPersistent``` makes the code pretty stable but since I cannot use ```v8::``` methods in ```Execute()``` it is a mistery for me how to access change and save buffer data back to persistent.


This is what I need to do: 


    void Execute () {
    
      char *inputBuffer;
      char outputBuffer[MAX_BUF_SIZE] = {0};

      // set inputBuffer from persistent
      // need to convert from v8::Local<v8::Object> inputBufferHandle to char *inputBuffer
      compute(inputBuffer, outputBuffer); // call existing compute methode
      // save outputBuffer back to persistent to return it back in HandleOKCallback
      // need to convert from char outputBuffer[MAX_BUF_SIZE] to v8::Local<v8::Value> outputBufferHandle;
      SaveToPersistent("buffer", outputBufferHandle);

    }

Is this possible to do with such a logic?

**Comment by s-a** [comment]
I tried this code for testing purpose which compiles but it crashes while execute 

```
  void Execute () {
	iRet = compute(inputBufferHandle, inputBufferLength, outputBuffer, outputBufferLength, iip, (int)clientSocket);

	v8::Local<v8::Value> outputBufferHandle = Nan::NewBuffer("", 0).ToLocalChecked();
  	SaveToPersistent("buffer", outputBufferHandle);
  }
```

**Comment by fivdi** [comment]
The async function [here](https://github.com/fivdi/i2c-bus/blob/master/src/readblock.cc#L55-L86) and the async worker [here](https://github.com/fivdi/i2c-bus/blob/master/src/readblock.cc#L12-L53) shown how I've being using buffers in worker threads. Note how `bufferData` is passed to the [`ReadBlockWorker`](https://github.com/fivdi/i2c-bus/blob/master/src/readblock.cc#L83) constructor and used in the [`Execute`](https://github.com/fivdi/i2c-bus/blob/master/src/readblock.cc#L27) method.

**Comment by s-a** [comment]
Thanks for the efforts and helpful resources.

Just resolved my problem was the garbage collector. I passed a ```FreeCallback``` method to my output buffer instance. The last thing I wonder is when and how should I free resources I skipped while garbage collecting? Because I think with this solution I created a memory leak. But I monitored my node app and memory usage seems to be constant.

    
    static void FreeCallback(char* data, void* message) {
    	//printf("GARBAGE COLLECTOR ATTACK 4----------------------------------------------\n");
       	//free(message);
    }

    void HandleOKCallback () {
    
	    Nan::HandleScope scope;
	    
	    v8::Local<v8::Value> out = Nan::NewBuffer(outputBuffer, iRet, FreeCallback, outputBuffer).ToLocalChecked();
	    SaveToPersistent("buffer", out);
	    
	    v8::Local<v8::Value> outputBufferHandle = GetFromPersistent("buffer");
	    callback->Call(1, &outputBufferHandle);
    
    }

**Comment by kkoopa** [comment]
```diff
diff --git a/async.cc b/async.cc
index 14dd77f..afd431d 100644
--- a/async.cc
+++ b/async.cc
@@ -12,19 +12,38 @@
 using v8::Function;
 using v8::Local;
 using v8::Number;
+using v8::Object;
 using v8::Value;
 using Nan::AsyncQueueWorker;
 using Nan::AsyncWorker;
 using Nan::Callback;
+using Nan::Error;
 using Nan::HandleScope;
 using Nan::New;
-using Nan::Null;
+using Nan::NewBuffer;
 using Nan::To;
+using Nan::Undefined;
+
+void compute(char *in, size_t size, char *out) {
+  for (size_t i = 0; i < size; ++i) {
+    out[2 * i] = in[i] ^ 7;
+    out[2 * i + 1] = in[i] ^ 13;
+  }
+}
+
+void fcb(char *data, void*) {
+  delete[] data;
+}
 
 class PiWorker : public AsyncWorker {
  public:
-  PiWorker(Callback *callback, char *points)
-    : AsyncWorker(callback), points(points), estimate(0) {}
+  PiWorker(Callback *callback, Local<Object> buffer)
+      : AsyncWorker(callback)
+      , in(node::Buffer::Data(buffer))
+      , size(node::Buffer::Length(buffer))
+      , out(new char[2 * size]) {
+    SaveToPersistent(kBufferIndex, buffer);
+  }
   ~PiWorker() {}
 
   // Executed inside the worker-thread.
@@ -32,7 +51,7 @@ class PiWorker : public AsyncWorker {
   // here, so everything we need for input and output
   // should go on `this`.
   void Execute () {
-    estimate = 0.1;//Estimate(points);
+    compute(in, size, out);
   }
 
   // Executed when the async work is complete
@@ -40,29 +59,29 @@ class PiWorker : public AsyncWorker {
   // so it is safe to use V8 again
   void HandleOKCallback () {
     HandleScope scope;
-    Nan::MaybeLocal<v8::Object> res = Nan::NewBuffer(points, sizeof(points));
-    Local<Value> argv[] = {
-        Null()
-      , res.ToLocalChecked()
-    };
 
-    callback->Call(2, argv);
+    Local<Object> buf;
+
+    bool good = NewBuffer(out, 2 * size, fcb, 0).ToLocal(&buf);
+
+    if (good) {
+      Local<Value> argv[] = { Undefined(), buf };
+      callback->Call(sizeof (argv) / sizeof (*argv), argv);
+    } else {
+      Local<Value> error = Error("bad alloc");
+      callback->Call(1, &error);
+    }
   }
 
  private:
-  char *points;
-  double estimate;
+  char *in;
+  const size_t size;
+  char *out;
+  const uint32_t kBufferIndex = 0;
 };
 
 // Asynchronous access to the `Estimate()` function
 NAN_METHOD(CalculateAsync) {
-//  int points = To<int>(info[0]).FromJust();
   Callback *callback = new Callback(info[1].As<Function>());
-
-
-
-    v8::Local<v8::Object> bufferObj = info[0]->ToObject();
-    char* msg = node::Buffer::Data(bufferObj);
-
-  AsyncQueueWorker(new PiWorker(callback, msg));
+  AsyncQueueWorker(new PiWorker(callback, info[0].As<Object>()));
 }
```
