### ISSUE TITLE
Wrap v8::Object::GetPrivate

### ISSUE THREAD

**Issue by cscott** [nodejs/nan#587]
v8 renamed `v8::Object::SetHiddenValue`/`GetHiddenValue`/`DeleteHiddenValue` to `v8::Object::GetPrivate`/`SetPrivate`/`DeletePrivate` (and added `HasPrivate`) and changed the return types from `Local` to `MaybeLocal`.  Seems like this is a good candidate for wrapping with `nan`, especially since the very latest versions of v8 seem to have deleted the old `SetHiddenValue` versions, which will break a lot of my modules.  (This change hasn't quite made it into node yet AFAICT.)

**Comment by kkoopa** [comment]
Since that change will break ABI compatibility, Node will not use it until v7, which is scheduled for some time in autumn. This will be taken care of then.

**Comment by maxkorp** [comment]
So unfortunately electron (as of 1.3) has already jumped to v8 5.2.x.y, in which this is broken, and also seems to have a different signature (key/value, instead of context/key/value).

**Comment by maxkorp** [comment]
Obviously, this is not set up using the global exported version constants and is not out in it's own file or anything of the sort, but the gist of what we've ended up with in nodegit to fix this is as such

```cpp
#if (NODE_MODULE_VERSION > 48)
  v8::Local<v8::Value> GetPrivate(v8::Local<v8::Object> object,
                                      v8::Local<v8::String> key) {
    v8::Isolate* isolate = v8::Isolate::GetCurrent();
    v8::Local<v8::Context> context = isolate->GetCurrentContext();
    v8::Local<v8::Private> privateKey = v8::Private::ForApi(isolate, key);
    v8::Local<v8::Value> value;
    v8::Maybe<bool> result = object->HasPrivate(context, privateKey);
    if (!(result.IsJust() && result.FromJust()))
      return v8::Local<v8::Value>();
    if (object->GetPrivate(context, privateKey).ToLocal(&value))
      return value;
    return v8::Local<v8::Value>();
  }

  void SetPrivate(v8::Local<v8::Object> object,
                      v8::Local<v8::String> key,
                      v8::Local<v8::Value> value) {
    if (value.IsEmpty())
      return;
    v8::Isolate* isolate = v8::Isolate::GetCurrent();
    v8::Local<v8::Context> context = isolate->GetCurrentContext();
    v8::Local<v8::Private> privateKey = v8::Private::ForApi(isolate, key);
    object->SetPrivate(context, privateKey, value);
  }
#else
  v8::Local<v8::Value> GetPrivate(v8::Local<v8::Object> object,
                                      v8::Local<v8::String> key) {
    return object->GetHiddenValue(key);
  }

  void SetPrivate(v8::Local<v8::Object> object,
                      v8::Local<v8::String> key,
                      v8::Local<v8::Value> value) {
    object->SetHiddenValue(key, value);
  }
#endif
```

called like 
```cpp
Local<v8::Value> checkValue = Nan::GetPrivate(nodeObj, Nan::New("BlahBlah").ToLocalChecked());
```

**Comment by bnoordhuis** [comment]
I wouldn't reject patches for 5.2 out of hand but there is no way for us to tes them (I think.  Perhaps building against Electron could be tested but running the suite on the CI?  Probably not.)

**Comment by maxkorp** [comment]
So, I'm aware of how to build the module cleanly for electron, I'll take a look at how the tests for this run and see if I can work up an electron solution for the short term :+1:

**Comment by saper** [comment]
New methods could be used already for [node 6.x, running V8 v5.0.x](https://github.com/nodejs/nan/pull/599#issuecomment-240882054).
