### ISSUE TITLE
nan_new.h(214) warning of conversion form 'size_t' to 'int'

### ISSUE THREAD

**Issue by octokyle** [nodejs/nan#589]
On Windows, below warning occurs when building. 

nan\nan_new.h(214): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data 

'v8::MaybeLocal<v8::String> Nan::New<v8::String,const _E
  lem*,unsigned __int64>(A0,A1)' being compiled
          with
          [
              _Elem=char
  ,            A0=const char *
  ,            A1=unsigned __int64
          ]

**Comment by orangemocha** [comment]
Thanks for the report. We'll investigate.

**Comment by kkoopa** [comment]
`size_t` is not an `int`. You should not pass `size_t` to a function expecting an `int`.
