### ISSUE TITLE
Helper for creating new Isolate and Context.

### ISSUE THREAD

**Issue by royalpinto** [nodejs/nan#590]
Any helper available for creating new Isolate and Context ?
Ex: Some versions use `Isolate::New(create_params)` signature to create new Isolate where as some versions use `Isolate::New()`.
For now I am using my own helper like below:
```
#if NODE_MODULE_VERSION >= NODE_4_0_MODULE_VERSION
 ArrayBufferAllocator allocator;
 Isolate::CreateParams create_params;
 create_params.array_buffer_allocator = &allocator;
 thread->isolate= Isolate::New(create_params);
#else
 thread->isolate= Isolate::New();
#endif
```

Thanks

**Comment by kkoopa** [comment]
`New<Context>` creates a new `Context`. `Isolate`s are not and can not be supported.

**Comment by royalpinto** [comment]
Okay thanks :)
