### ISSUE TITLE
Update readme file

### ISSUE THREAD

**Issue by Schrims** [nodejs/nan#591]
Hi all,
under https://github.com/nodejs/nan#usage in your README file you mentioned to add nan as a dependency. Nan is written in bold and with capital letters - but in npm you have to use nan with small letters. This may lead to some irritations and should be changed.

**Comment by rvagg** [comment]
It's quite normal for a project to have one name but publish to npm under another. There are clear instructions on the README about what to pull from npm.
Thanks anyway.
