### ISSUE TITLE
nan : "c" library callback implementation  

### ISSUE THREAD

**Issue by Rishu** [nodejs/nan#593]
Hi,

We need to integrate c library with node-webkit application. We are working to prepare addon which allow us to invoke c library function from javascript. We are able to invoke c library function, but we are facing issue with implementing asynchronous callback function pointer which is accepting callback function in format: 

DSPEC_C typedef  void (STDCALL *func)(const char *parameter1, int parameter2);

Can you please help me to implement  callbacks functionality inside nan based addon.

Thanks in advance.

Regards,
Rishu

**Comment by bnoordhuis** [comment]
You might want to start with explaining what exactly doesn't work and what you have tried so far.

**Comment by Rishu** [comment]
Hey @bnoordhuis,

Thanks for reply. As of now, we are trying to implement this using by creating a subclass of 'AsyncWorker' and override function 'execute' function where we are calling 'C' library function. But we are unable to pass function pointer into "c" library function as above mentioned function format.

Please let me know any workaround if this approach is correct.

**Comment by bnoordhuis** [comment]
> But we are unable to pass function pointer into "c" library function as above mentioned function format.

Unable why?  And how exactly is that an issue with nan?

**Comment by Rishu** [comment]
Thanks for your question. I have created in function in below mentioned format inside inherited class from 'AsyncWorker':

void func(const char *parameter1, int parameter2);

Which cause compiler error "&classname::func" or "&func". If we declare function as 'static' function, compiler will be able to compile it. But in this case 'callback' parameter will not be accessible inside the 'Static function' which is passed to class as constructor as below:

Worker(Callback *callback)  : AsyncWorker(callback) {}

Please let me know in case of any workaround for this issue.

**Comment by Venemo** [comment]
Perhaps you could take a look at the example: https://github.com/nodejs/nan/blob/master/examples/async_pi_estimate/async.cc

**Comment by bnoordhuis** [comment]
> If we declare function as 'static' function, compiler will be able to compile it. But in this case 'callback' parameter will not be accessible inside the 'Static function' which is passed to class as constructor as below:

With all due respect, that is more of a general C++ question and not specific to nan.  Please consult the examples and if you still have (nan-specific) questions afterwards, please comment.

**Comment by Rishu** [comment]
@bnoordhuis It's not an c++ concern. If it is c++ concern, then it will surly accept callback in format &classname::func and will force to provide as static function. 

Also, there are no example illustrated on nan example section which is related to my concern that's why i have raised issue: 
https://github.com/nodejs/nan/tree/master/examples/async_pi_estimate

Please let me know if you have any workaround or example available on Nan repository.

**Comment by bnoordhuis** [comment]
Your original comment mentions integrating with a library that takes a STDCALL function pointer.  That is not coming from nan and if your question is how to integrate nan with it, please consult your library's vendor; this is not the right place to ask that question.

**Comment by Rishu** [comment]
@bnoordhuis Thanks for your suggestion. I have created a simple C Class which accept argument without STDCALL. In this case, it will also required to static function to compile it. 

Look forward to hear your suggestion.

**Comment by Rishu** [comment]
I have resolved my issue with test example - https://github.com/nodejs/nan/blob/master/test/cpp/asyncprogressworkerstream.cpp as i was receiving callback not in main thread.
