### ISSUE TITLE
Can't use Nan::New with new object types

### ISSUE THREAD

**Issue by ranisalt** [nodejs/nan#594]
I'm trying to instantiate new containers, namely `v8::Map` and `v8::Set`, but they can't be overloaded with `Nan::New`. I'm trying with the following code:

```
auto limits = Nan::New<v8::Map>();
```

And it gives me compilation errors about not being able to find the template instantiation to use. `v8::Map` has the same `::New` signature of `v8::Object` and the latter works properly:

```
auto limits = Nan::New<v8::Object>();
```

Is this the case of an unavailable overload or I'm missing something?

Currently running nan 2.4.0 with node 6.3.1

**Comment by kkoopa** [comment]
There are no template specializations for those types, since they do not exist in all supported versions of Node.

**Comment by ranisalt** [comment]
Good, but since they are now available and probably will for future version, is there any intention to specializate for them?

**Comment by kkoopa** [comment]
Only when support for all older versions has been dropped. The point is to offer a consistent API for all supported versions, not to have things that may or may not work depending on versions of various libraries, extra patches and the phase of the moon.

If you commit to only using versions of Node that support said classes, you can always use the V8 functions directly or specialize the correct factories for Nan::New, check out nan_new.h

**Comment by ranisalt** [comment]
That's probably what I'll do, then I will PR as soon as those classes are to be adopted :)
