### ISSUE TITLE
Dependencies node-gyp

### ISSUE THREAD

**Issue by RickBitter** [nodejs/nan#596]
hi:

node-gyp broke with visual studio 2015, to use node-gyp with version 3.4. (https://github.com/nodejs/node-gyp/issues/980)

the dependencies for nan specify an older version of node-gyp and i can't get this package to build w/VS 2015. i'm trying to build raw-socket which uses nan and the nan version pulled down uses a node-gyp version 3.3.1 and this doesn't work with VS 2015.

is there any way we can up-rev the dependency on node-gyp without breaking nan?

**Comment by kkoopa** [comment]
I have not looked into it, but I do not think bumping it should be a problem. However, NAN has no dependencies. Node-gyp is only a dev-dependency, which is only used for running the test suite on the CI server. You should not have to install anything extra.
