### ISSUE TITLE
Nan::New<v8::Function> Memory Leak

### ISSUE THREAD

**Issue by cbratschi** [nodejs/nan#598]
I just found the following memory leak. All other created v8::Value instances are handled by the active scope but this call leaks memory:
```c++
Nan::Set(obj, Nan::New<v8::String>("nativeListener").ToLocalChecked(), Nan::New<v8::Function>(PropertyUpdated));
```
If this line is called thousand of times many MB of memory are leaking. It seems the created function template is never freed.

PropertyUpdated is defined as NAN_METHOD(PropertyUpdated).

This is line 253 of https://github.com/cbratschi/aminogfx-gl/blob/master/src/base_js.cpp.

Is there another way to set a function reference or is this a Nan bug?

**Comment by bnoordhuis** [comment]
With what node.js version are you seeing that?

**Comment by cbratschi** [comment]
Node.js 4.x.

**Comment by bnoordhuis** [comment]
Sorry, missed your reply.  v4 is okay, older versions had some known issues w.r.t. creating functions.

It's not a nan bug but you could argue it's a V8 bug. `v8::Function::New()` creates new code stubs in the code space.  The code space is not frequently (sometimes never) garbage collected, making it easy to "leak" memory.

I put "leak" between scare quotes because it's not a memory leak in the traditional sense.  The memory is reclaimable except it never happens.

> Is there another way to set a function reference

Instantiate it once and cache the result in a persistent handle.

**Comment by cbratschi** [comment]
That's what I already implemented as a workaround and memory consumption is now stable. It was "leaking" memory before until the app was crashing with an out of memory error.

So there is no way to free this reference by force? I can imagine situations where you need to create many dynamic callbacks which leads to memory issues especially in long running processes like Node.js apps.

I did not see any similar issues with other data types created through Nan::New() calls. And my stress test calls global.gc() every second. So in my opinion this is a bug. At least there should be a warning somewhere to strictly use (bad by design) singletons.

**Comment by bnoordhuis** [comment]
> So there is no way to free this reference by force?

No.

> I can imagine situations where you need to create many dynamic callbacks

In my experience such situations pretty much don't exist.  When you don't pass in a data argument, you're just creating the same function object over and over again, so what's the point?

> And my stress test calls global.gc()

`gc()` doesn't sweep the code space, only data spaces.

> At least there should be a warning somewhere to strictly use (bad by design) singletons.

Spare me from ideological puritanism!  I think we're open to documentation pull requests but where exactly would you put it?
