### ISSUE TITLE
is it possible to declare NAN_METHOD outside of its class?

### ISSUE THREAD

**Issue by sulliwane** [nodejs/nan#604]
Hello,

I'm trying to do this:
```cpp
class MyClass;
MyClass::NAN_METHOD(method);
```
But as I expected it doesn't work. Is it possible to separate NAN_METHOD definition to its implementation?

Many thanks for your answers :)

**Comment by addaleax** [comment]
You’re not asking whether you can do something like
```c++
class MyClass {
  public:
     static NAN_METHOD(Method);
};

NAN_METHOD(MyClass::Method) {
  …
}
```

… right? Because that should totally work.

**Comment by sulliwane** [comment]
Ok it works with your example, that was obvious indeed....my mistake! many thanks for your prompt reply :)
