### ISSUE TITLE
Nan::Callback::Call() returns empty(?) Local<Value>

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/nan#605]
I'm getting a segfault when I attempt to check whether the return value of my callback is a uint32. I have

``` C++
  Local<Value> returnValue =
      (((CallbackInfo *)context)->callback)->Call(2, jsCallbackArguments);
  if (!returnValue->IsUint32()) {
    Nan::ThrowTypeError("Callback return value must satisfy IsUint32");
    return;
  }
```

However `IsUint32()` segfaults when attempting to process `returnValue`. Indeed, if I print `returnValue` with gdb, I get

```
$1 = {val_ = 0x0}
```

Strangely, `returnValue.IsEmpty()` returns `false`.

I haven't seen this prior to node 4.5.0. Is there some canonical way of handling such a value, short of looking at `val_` and making sure it's not null? I assume the latter way is not very portable. Is such a value ever supposed to appear as the result of a callback into JS?

**Comment by gabrielschulhof** [comment]
P.S.

I do have a ```Nan::HandleScope scope;``` declaration at the top, since this is in a native callback.

**Comment by Kamil93** [comment]
I have same problem with any action of returned value from callback.

**Comment by gabrielschulhof** [comment]
If the callback throws an exception then control returns to C++, but the
value the callback would have returned is empty. So, wrap your callback in
a try/catch block:

```C++
    Nan::TryCatch tryCatch;
    jsReturnValue = jsCallback->Call(context, argumentCount, arguments);
    if (tryCatch.HasCaught()) {

      // At this point jsReturnValue is empty, so don't try to use it
      tryCatch.ReThrow();
      return somethingForTheNativeCallback;
    }

    // At this point, jsReturnValue is not empty, so using it won't segfault
    return Nan::To<int>(jsReturnValue).FromJust();
```
