### ISSUE TITLE
AsyncWorker and OpenSSL HMAC

### ISSUE THREAD

**Issue by jorangreef** [nodejs/nan#612]
I would like to write an addon to do asynchronous HMAC running in the thread pool.

I have tried to work through as many examples as possible (e.g. async_pi_estimate, bufferworkerpersistent).

Would anyone be able to provide some sample boilerplate to do HMAC in the thread pool?

**Comment by agnat** [comment]
async_pi_estimate seems like the perfect boilerplate for this type of thing. The rest is plain old programming. So, not sure what you are asking...

**Comment by jorangreef** [comment]
How can one pass a buffer from Node to the Execute function, without copying and without getting a segfault or being vulnerable to memory moved by the GC? The current examples don't really show that.

**Comment by jorangreef** [comment]
It's probably quite simple, but perhaps someone could actually just paste the boilerplate for that here? I'm sure it would help alot of people.

**Comment by jorangreef** [comment]
Also, would including Openssl via `#include <openssl/evp.h>` use Node's version of Openssl? I'm new to C++.

**Comment by agnat** [comment]
> How can one pass a buffer from Node to the Execute function

You can't. v8 objects live on the node thread.

**Comment by jorangreef** [comment]
Really? Can't you save a persistent reference to the buffer in the worker constructor and then pass a pointer to the underlying buffer data in the heap?

**Comment by agnat** [comment]
Really.

**Comment by addaleax** [comment]
You can always keep references to the buffer alive in JS by attaching it to some object until the work is done, and extract the pointer/size properties in the worker constructor so you can work with them asynchronously?

**Comment by agnat** [comment]
I'm afraid but it really is not possible. v8 has a compacting garbage collector. It copies all live objects from one hemi-heap to the other at collection time. Then it goes ahead and changes all `Persistent<>` to the new addresses. The foreign thread does not know this. _Boom_ segfault...

**Comment by addaleax** [comment]
@agnat That does *not* change the pointer to the underlying memory for a buffer. Keeping the buffer object alive via a reference is what Node core does itself for async operations.

**Comment by agnat** [comment]
Oh, you're right! With a buffer grabbing the _underlying_ memory is an option.

**Comment by agnat** [comment]
@jorangreef: Apologies for not paying attention when answering your ticket. My bad.

So yes. Exactly like you described. Hold the buffer using a persistent, grab pointer and size and pass that to the worker thread. Store your result using that pointer.

**Comment by fivdi** [comment]
There's an example [here](https://github.com/fivdi/i2c-bus/blob/master/src/writei2cblock.cc#L87-L94) that works for me. See how `bufferData` and `bufferHandle` are used. The `bufferData` passed to the constructor ends up being used in the async [Execute method](https://github.com/fivdi/i2c-bus/blob/master/src/writei2cblock.cc#L28) (`block`).

**Comment by jorangreef** [comment]
Thanks @agnat , @addaleax for clarifying. Do you think V8 would ever change the GC behavior to move the underlying buffer memory?

Would including OpenSSL in an addon via `#include <openssl/evp.h>` use Node's version of OpenSSL?

Thanks @fivdi for the example, that's exactly what I was looking for.

**Comment by bnoordhuis** [comment]
> Do you think V8 would ever change the GC behavior to move the underlying buffer memory?

Not in node.js because V8 doesn't own the pointer.  Other embedders should be started with `--typed_array_max_size_in_heap=0`, otherwise small typed arrays and array buffers are allocated on the JS heap and get moved around.

> Would including OpenSSL in an addon via `#include <openssl/evp.h>` use Node's version of OpenSSL?

Yes, that should work.

**Comment by jorangreef** [comment]
Thanks @bnoordhuis
