### ISSUE TITLE
Example of passing V8 string as char* to async worker

### ISSUE THREAD

**Issue by jorangreef** [nodejs/nan#614]
I am new to C++ and NAN.

Would anyone be able to provide an example of passing a V8 string to an async worker as a char*?

Do you need to save a persistent reference to the string handle?

**Comment by bnoordhuis** [comment]
You can't reference a V8 object from another thread so you first need to serialize and store the string.  A quick and easy way is to copy it to a std::string:
```c++
v8::Local<v8::String> v8_string = /* ... */;
Nan::Utf8Value nan_string(v8_string);
std::string cc_string(*nan_string);
```
You could also use nan_string directly from the worker thread but Nan::Utf8Value is immovable (doesn't have copy or move semantics) so it may be less convenient to work with.

**Comment by jorangreef** [comment]
Thanks Ben, would copying it to a std::string avoid any issues with GC, i.e. no need to save a persistent reference in the async worker?

**Comment by jorangreef** [comment]
Did you mean `Nan::Utf8String` instead of `Nan::Utf8Value`?

**Comment by bnoordhuis** [comment]
Sorry, yes.  And correct, no need to keep references around.

**Comment by jorangreef** [comment]
Sorry, I am getting a segfault:

I am copying the string and converting to char* as follows:

```
Nan::Utf8String nan_string(info[0]);
std::string name(*nan_string);
const char* digest = name.c_str();
```

I then pass `digest` as an argument to the async worker as follows:

```
class HashWorker : public Nan::AsyncWorker {
 public:
  HashWorker(
    const char* digest,
    [...]
    Nan::Callback *end
  ) : Nan::AsyncWorker(end),
      digest(digest),
```

Within Execute:

```
void Execute () {
    printf("digest: %s\n", digest);
    OpenSSL_add_all_digests();
    const EVP_MD* md = EVP_get_digestbyname(digest);
    if (md == nullptr) {
      printf("\nbad digest name");
    }
```

This returns "SHA256" as the value of the digest, and then "bad digest name" since OpenSSL does not accept the `digest` name.

Whereas this works:

```
void Execute () {
    std::string other("SHA256");
    const char* otherDigest = other.c_str();
    OpenSSL_add_all_digests();
    const EVP_MD* md = EVP_get_digestbyname(otherDigest);
```

**Comment by jorangreef** [comment]
Somehow OpenSSL does not accept `digest`=SHA256 when passed via the async worker constructor but it does when created directly within `Execute`?

**Comment by bnoordhuis** [comment]
This is invalid:
```c++
const char* digest = name.c_str();
```
`name` goes out of scope, turning `digest` into a dangling pointer.

**Comment by jorangreef** [comment]
Should I do `name.c_str()` within the async worker constructor? I tried that, and `printf` within `Execute` still shows "SHA256" yet OpenSSL rejects the digest name.

**Comment by addaleax** [comment]
Yeah, you’ll need to store the `std::string` instance itself as a property of `HashWorker`, not what was returned by `.c_str()`.

`.c_str()` gives you a `const char*`, but the memory allocated for the string itself is released as soon as the `std::string` itself is no longer in scope.

**Comment by jorangreef** [comment]
Thanks very much @bnoordhuis and @addaleax , I understand and it's working.
