### ISSUE TITLE
Query regarding destruction of Async worker's callback

### ISSUE THREAD

**Issue by harrydevnull** [nodejs/nan#615]
I'm pretty new to nan; pardon my naiveness; I had query regarding the life cycle of Asyncworker.
https://github.com/nodejs/nan/blob/master/doc/asyncworker.md#api_nan_async_worker

In the constructor we are initiating a callback class; but in all examples available I don't see that getting cleaned up in the destructor. Is it left out intentionally ?
eg : https://github.com/nodejs/nan/blob/master/examples/async_pi_estimate/async.cc

```
class PiWorker : public AsyncWorker {
 public:
  PiWorker(Callback *callback, int points)
    : AsyncWorker(callback), points(points), estimate(0) {}
  ~PiWorker() {}
```
shouldn't it be something like this 

```
class PiWorker : public AsyncWorker {
 public:
  PiWorker(Callback *callback, int points)
    : AsyncWorker(callback), points(points), estimate(0) {}
  ~PiWorker() {
     delete callback;
}
```

**Comment by bnoordhuis** [comment]
PiWorker also inherits AsyncWorker's destructor which calls `delete callback`.  Constructors in C++ are called in least derived -> most derived order, destructors the other way around.  Hope that clears it up.

**Comment by harrydevnull** [comment]
thank you 👍
