### ISSUE TITLE
Query regarding cpp11 features unique_ptr

### ISSUE THREAD

**Issue by harrydevnull** [nodejs/nan#616]
I believe node-gyp uses cpp11 under the hood. but when i use std::unique_ptr or any smart pointers for that matter; node-gyp fails to compile.
is this something do with nan ?

**Comment by bnoordhuis** [comment]
No, and neither with node-gyp.  std::unique_ptr is a stdlib function.  You can have a C++11-capable compiler but a pre-C++11 stdlib.  (Example: OS X <= 10.9, "it depends" when on 10.10 and newer.)
