### ISSUE TITLE
libstdc++ to libc++

### ISSUE THREAD

**Issue by davidgatti** [nodejs/nan#617]
Hello :) 

After updating to macOS Sierra, when I build a project I get the following warning 
```
> node-gyp rebuild

  CXX(target) Release/obj.target/strings/main.o
  SOLINK_MODULE(target) Release/strings.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
```

My `.gyp` file looks like this 
```javascript
{
  "targets": [
    {
      "target_name": "strings",
      "sources": ["main.cpp"],
      "cflags": ["-Wall", "-Wextra", "-ansi", "-O3"],
      "include_dirs" : ["<!(node -e \"require('nan')\")"]
    }
  ]
}
```
Nothing fancy, and so my question is this: this warning is related to Nan or something that I'm doing wrong?

**Comment by bnoordhuis** [comment]
Nothing to worry about.  Node is linked to libstdc++, therefore add-ons are linked to libstdc++.  You _can_ override it but you shouldn't without good reason; there is much that can go wrong.

**Comment by davidgatti** [comment]
OK, cool. good to know, and thank you for the explanation 👍 😄
