### ISSUE TITLE
New buffer

### ISSUE THREAD

**Issue by zwj741** [nodejs/nan#618]

**Comment by addaleax** [comment]
Could you be more specific?

**Comment by jabyrd3** [comment]
Not sure if this is the issue @zwj741 was posting about, but I'm getting this error (i believe from nan 2.3.2 included by ketyar, but it's hard to find the actual trace).

```
DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
```

**Comment by jabyrd3** [comment]
Update: manually copied over 2.4.0 (latest) to the keytar dir, still getting the above deprecation notice under node 7.0.0
