### ISSUE TITLE
Free copied buffer 

### ISSUE THREAD

**Issue by zwj741** [nodejs/nan#619]
I am currently writing a addon for node , which read media file(.mp4) as source ,output .ts file as result. (A small hls server ) Everything went well, I believe everything are correctly freed in C++ part. I am using async worker to output buffer response to express. In C++ part I used CopyBuffer(NewBuffer could not work) to create correct result for buffer. The problem is following, when the request was canceled before the response, the buffer could not be free at all, it.contiuesly grows. It result in memory leak. So I am wondering, is it a way to free those copied buffer by nodejs if the request is canceled.

**Comment by addaleax** [comment]
This sounds like something that would better be asked at https://github.com/nodejs/help, and maybe with some code samples to better understand what exactly your code currently does.
