### ISSUE TITLE
Library not loaded... Reason: image not found

### ISSUE THREAD

**Issue by davidgatti** [nodejs/nan#621]
Hello Epic people 😎.

A while back I had to use a C library in a company project, and thanks to Nan and 1 book, and some trial and error, I managed to make it all work 👍. 

Since I like to write articles I decided to write down what I learned.

Strangely enough, I'm having an issue making NodeJS, C++ and C work nicely together, and I'm not sure what is going on since I repeated all the steps from my work project. The only difference is that I decided to create a C library myself. When I try to run JavaScript I get the following:

```
> library@1.0.0 start /Users/davidgatti/Documents/GitHub/MrWhite/NodeJS-to-C-through-CPP/library
> LD_LIBRARY_PATH=c_library node index.js

module.js:583
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: dlopen(/Users/davidgatti/Documents/GitHub/MrWhite/NodeJS-to-C-through-CPP/library/build/Release/c_library.node, 1): Library not loaded: libdavid_sum.so
  Referenced from: /Users/davidgatti/Documents/GitHub/MrWhite/NodeJS-to-C-through-CPP/library/build/Release/c_library.node
  Reason: image not found
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/davidgatti/Documents/GitHub/MrWhite/NodeJS-to-C-through-CPP/library/index.js:6:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
```

If I put the `libdavid_sum.so` (copy not move), in the root directory of the project, I get this error despite keeping the paths to the library directory untouched.

```
> library@1.0.0 start /Users/davidgatti/Documents/GitHub/MrWhite/NodeJS-to-C-through-CPP/library
> LD_LIBRARY_PATH=c_library node index.js

module.js:583
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/davidgatti/Documents/GitHub/MrWhite/NodeJS-to-C-through-CPP/library/index.js:6:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
```

# The source code 

The source code can be found [hear](https://github.com/davidgatti/NodeJS-to-C-through-CPP/tree/master/library). To make it all not work 😅, you need to:

1. In the `c_library` folder type `make` to create the library and test app that shows that the library works.
1. in the library folder type `npm install` 
1. in the library folder type `npm start` 

# My questions...

I have no idea what I'm missing. Is there an issue locating the library? Or maybe I'm making the library the wrong way? 

# Tech specs

- NodeJS v6.4.0
- Nan: 2.4.0
- node-gyp: 3.4.0

**Comment by bnoordhuis** [comment]
LD_LIBRARY_PATH looks wrong to me.  It should be the (preferably absolute) path to the directory containing the .so.

Also, if you use OS X, it's DYLD_LIBRARY_PATH, not LD_LIBRARY_PATH.

**Comment by davidgatti** [comment]
@bnoordhuis good point I'm on macOS. I replaced `LD_LIBRARY_PATH` with `DYLD_LIBRARY_PATH` and now I'm getting this. 

```
> library@1.0.0 start /Users/davidgatti/Documents/GitHub/MrWhite/NodeJS-to-C-through-CPP/library
> DYLD_LIBRARY_PATH=/Users/davidgatti/Documents/GitHub/MrWhite/NodeJS-to-C-through-CPP/library/c_library node index.js

module.js:583
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/davidgatti/Documents/GitHub/MrWhite/NodeJS-to-C-through-CPP/library/index.js:6:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
```

Meaning your observation did put me in the right directions and the issue was with the path. But even if I use the absolute path. There is no difference, the error is the same. 

# Question

Now that we figure out the paths. Is it possible that I'm making the library incorrectly 🤔?

**Comment by bnoordhuis** [comment]
What does `otool -L /Users/davidgatti/Documents/GitHub/MrWhite/NodeJS-to-C-through-CPP/library/c_library/libdavid_sum.so` print?  Are you sure it ends in .so and not .dylib?

**Comment by davidgatti** [comment]
@bnoordhuis I thought something might be wrong hear :) nice cats. when I cut the library that I used, the header is way different them what I have. So this is what happens when I cut my library 

```
���
(libdavid_sum.so"�0 @ EXT���__unwind_info__TEXT�H�H__LINKEDIT`
                      PhC��*0��8GX=[$



*
 8�/usr/lib/libSystem.B.dylib) UH��}�u�u�u��]��44�4
 _david_sumdyld_stub_binder
```

And it seams you are right at the end there is `dylib`, if this is the issue, how can I create a true .so library? Because everywhere I look I find this gcc command: `gcc -shared -o libdavid_sum.so -fPIC david_sum.c`.

**Comment by davidgatti** [comment]
@bnoordhuis I also found this http://stackoverflow.com/a/29226313/1049894, and I'm using `-shared` to create the `.so`, so what could be issue?

**Comment by bnoordhuis** [comment]
How are you building your shared library?  If you use gyp (i.e., when you add a target to your binding.gyp of type shared_library) it takes care of the details and you'll end up with a .dylib you can load.  This is a bit off-topic for the nan bug tracker though.

**Comment by cjbj** [comment]
Watch out for SIP on recent OS X releases.  It stops DYLD_LIBRARY_PATH doing what you expect.  You may need to link with rpath, or put libraries in ~/lib.  See https://github.com/oracle/node-oracledb/issues/149#issuecomment-170747121 Note subsequent to all that discussion, a new set of dependent libraries was built and the add-on was changed to use rpath https://github.com/oracle/node-oracledb/blob/master/binding.gyp#L54 Together these resolved the problems for this add-on.  YMMV.

**Comment by davidgatti** [comment]
@cjbj 😮 interesting. I shall try run this on Linux and see if that works.

**Comment by davidgatti** [comment]
Well, @bnoordhuis thank you for your help finding the problem, and @cjbj to show that the issue is bigger on the macOS then anticipated :). After moving to Debian, everything works :) 

🙇
