### ISSUE TITLE
Need support for node.js v7

### ISSUE THREAD

**Issue by andreiz** [nodejs/nan#622]
What the title states

**Comment by brodybits** [comment]
Can you please be specific about what is wrong, along with any error messages you may encounter, which platform, etc.?

I ran the nan test suite on Node v7.0.0, on macOS (Sierra) with no trouble. I also ran the node-webworker-threads test suite OK with nan 2.3.3 and 2.4.0 on Node 7.

**Comment by kkoopa** [comment]
Voila, Node 7 supported: 0a2a6f66dab73352dc3a519e4e063f9ef632d043

**Comment by andreiz** [comment]
Apparently it wasn't as easy as this. I ran into an error building my module:

`../protobuf_for_node.cc:142:22: error: no member named 'SetHiddenValue' in 'v8::Function'
        constructor->SetHiddenValue(Nan::New<String>("type").ToLocalChecked(), self);
        ~~~~~~~~~~~  ^`

There seems to be a related issue: #587
