### ISSUE TITLE
How should one prevent GC from collecting third-party ObjectWrap?

### ISSUE THREAD

**Issue by mcheshkov** [nodejs/nan#629]
I want to use third-party wrapped object ([opencv](https://github.com/peterbraden/node-opencv/) Matrix) in my C++ code, unwrap it and use in AsyncWorker.
What bothers me, is that after one unwrap it there's no sign for GC to prevent collecting it. I thought I could use `Ref()` ans `Unref()` on wrapped object, like this:

```C++
    // before AsyncQueueWorker
    node_opencv::Matrix* mat_obj = Nan::ObjectWrap::Unwrap<node_opencv::Matrix>(
      To<Object>(info[0]).ToLocalChecked()
    );
    mat_obj->Ref();
    // save mat_obj in AsyncWorker subclass instance

    // in HandleOKCallback
    mat_obj->Unref();
```

But these methods are protected, and one can't call it from outside. Why so?
How should one prevent GC from collecting such objects? Create new persistent handle from `persistent()`?

**Comment by bnoordhuis** [comment]
> Create new persistent handle from persistent()?

Almost.  Create a new persistent handle from handle().

**Comment by mcheshkov** [comment]
Oh, there's `SaveToPersistent` `GetFromPersistent` methods on AsyncWorker, which I never looked at, and they seem exactly for that purpose.
If so, can I call `GetFromPersistent` and `Unwrap` in worker thread, or just use `SaveToPersistent` as a persistent handle and don't mess concurrently with JS objects?

**Comment by bnoordhuis** [comment]
> can I call GetFromPersistent and Unwrap in worker thread

Emphatically no. :-)

> just use SaveToPersistent as a persistent handle and don't mess concurrently with JS objects?

That should work.

**Comment by mcheshkov** [comment]
Nice, thanks for quick response!
