### ISSUE TITLE
Fatal Error C1060 when compiling with Visual Studio 2012

### ISSUE THREAD

**Issue by ageblade** [nodejs/nan#636]
`..\node_modules\nan\nan.h(72) : fatal error C1060: compiler is out of heap space (..\hello.cc)`

I get this one when trying to compile a sample code with the following parameters:

`node-gyp rebuild --arch=ia32 --msvs_version=2012`

Anyone with a similar issue or know how to solve this ?

**Comment by yunnysunny** [comment]
#639

**Comment by bnoordhuis** [comment]
What @yunnysunny hints at, you need a newer version of VS or Build Tools.

**Comment by ageblade** [comment]
Yeah I understood that... but I have a constraint that forces me to compile it with VS2012.
I guess the other project needs to be upgraded...

**Comment by eljefedelrodeodeljefe** [comment]
Yes. Please be aware that supporting old Windows toolchains is quite a burden for the Node maintainers. There is also no way back to supporting it. Thx.
