### ISSUE TITLE
Question: is there a leak in async_pi_estimate and how to correctly release callback

### ISSUE THREAD

**Issue by fuzing** [nodejs/nan#638]
It looks like the async_pi_estimate has a couple of memory leaks:

the Callback and PiWorker are allocated on the heap but never released/deleted (not a big deal for this example), however how would one go about deleting the Callback from an AsyncWorker subclass? (or is this handled by the AsyncWorker itself?)

thanks.

**Comment by mathiask88** [comment]
The worker deletes himself and the given callback after the work is completed. If you use a Nan::Callback without the worker u need to handle the deallocation by yourself.

**Comment by fuzing** [comment]
That makes sense - thanks for your quick response.

I also noted that AsyncQueueWorker() appears to clean up the worker upon completion, which makes sense.
