### ISSUE TITLE
Question: Building with others languages (C, assembly)

### ISSUE THREAD

**Issue by helio-frota** [nodejs/nan#641]
Possible to use/link/compile other libraries like `something.o` or `something.s (asm)` or `something.c` with nan ? Using the binding.gyp ?

**Comment by helio-frota** [comment]
I mean, JS call C++ and C++ call C or C++ call assembly.

**Comment by bmeck** [comment]
https://gyp.gsrc.io/docs/InputFormatReference.md#Dependencies-and-Dependents should help with what to do when linking dependencies. This question is more for `gyp` than `nan`

**Comment by helio-frota** [comment]
Thanks! 
I'll close this issue.
