### ISSUE TITLE
Wrappers for zero-arg v8::Value::BooleanValue(), etc.?

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/nan#643]
In upstream V8 it's no longer possible to call the zero-arg (no-context) `value->BooleanValue()`, `value->ToBoolean()`, `value->NumberValue()`, etc. methods without getting deprecation warnings.  Time to add wrappers for them?

Strawman proposal:
```c++
inline Maybe<bool> BooleanValue(v8::Local<v8::Value> value) {
  if (value.IsEmpty()) return Maybe<bool>();
  return value->BooleanValue(v8::Isolate::GetCurrent()->GetCurrentContext());
}
```

**Comment by kkoopa** [comment]
Already handled for the past two years or so. Nan::To<T> does conversion both ways.

**Comment by bnoordhuis** [comment]
Oh, right you are.  Greppability isn't great but I suppose there is no substitute for reading the documentation.  I'll close, thanks.
