### ISSUE TITLE
AsyncProgressWorker Error : ExecutionProgress is private explicit ExecutionProgress(AsyncProgressWorkerBase *that) : that_(that) {}

### ISSUE THREAD

**Issue by sulliwane** [nodejs/nan#646]
I'd like to let my **RPC interface** inherit Nan::AsyncProgressWorker, so that it can queue data and send it to node/JS when HandleProgressCallback is fired. But **Nan::AsyncProgressWorker::ExecutionProgress** is private...

Here is the code:
```cpp
// worker.h
class MyWorker : public Nan::AsyncProgressWorker, public RpcSpi
{
	public:
		MyWorker(Nan::Callback *callback, Nan::Callback *progress_callback, Nan::Callback *error_callback);
		~MyWorker();

		void HandleErrorCallback();
	        void HandleOKCallback();
                void HandleProgressCallback(const char *data, size_t size);
		void Execute(const Nan::AsyncProgressWorker::ExecutionProgress& progress);

                // RPC Callback, runs in its own thread managed by the RPC framework
		virtual void OnData(const Message msg); 

                // local queue to write RPC data received in the OnData callback.
                // Flush it in HandleProgressCallback.
		PCQueue<Message> toNode; 
	protected:
                // write RPC messages to the queue
		void writeToNode(const Nan::AsyncProgressWorker::ExecutionProgress& progress, const Message & msg);

		Nan::Callback *progress_callback;
		Nan::Callback *error_callback;

	private:
		const Nan::AsyncProgressWorker::ExecutionProgress progress;
};
```
And here is the implementation:
```cpp
// worker.cpp
MyWorker::MyWorker(Nan::Callback *callback, Nan::Callback *progress_callback, Nan::Callback *error_callback
) : 
     Nan::AsyncProgressWorker(callback), progress_callback(progress), error_callback(error_callback),
     progress(this) // ERROR here !!
// ../node_modules/nan/nan.h:1656:14: error: ‘Nan::AsyncProgressWorkerBase<T>::ExecutionProgress::ExecutionProgress(Nan::AsyncProgressWorkerBase<T>*) [with T = char]’
// is private explicit ExecutionProgress(AsyncProgressWorkerBase *that) : that_(that) {}
{ }

void MyWorker::writeToNode(const Nan::AsyncProgressWorker::ExecutionProgress& progress, const Message & msg) {
	toNode.write(msg);
	progress.Send(reinterpret_cast<const char*>(&toNode), sizeof(toNode)); 
}

void MyWorker::HandleProgressCallback(const char *data, size_t size) {
	Nan::HandleScope scope;
	// drain the queue - since we might only get called once for many writes
	std::deque<Message> contents;
	toNode.readAll(contents);

	for(Message & msg : contents) {
			v8::Local<v8::Value> argv[] = {
				Nan::New<v8::String>(msg.name.c_str()).ToLocalChecked(),
				Nan::New<v8::String>(msg.data.c_str()).ToLocalChecked()
			};
			progress->Call(2, argv);
	}
}

void MyWorker::OnData(const Message msg) {
       writeToNode(progress, msg);
};
```
How to make the instance of **ExecutionProgress** available in my RPC interface ? Making the **ExecutionProgress** constructor public in **nan.h** works fine, but I'm sure there is a "correct" way of doing this...

Many thanks for your help ! :)

**Comment by kkoopa** [comment]
Hmm.. You might need an upcast from `MyWorker*` to `AsyncProgressWorker*`.
`AsyncProgressWorker` [is a friend](https://github.com/nodejs/nan/blob/master/nan.h#L1645) of `ExecutionProgress`.

The reason `ExecutionProgress` is so locked down is to make it difficult to misuse.

**Comment by kkoopa** [comment]
Nevermind the previous answer, you are not supposed to use it like that. You do not ever get to instantiate ExecutionProgress. It is only available as the argument of the `Execute` method. https://github.com/nodejs/nan/blob/master/nan.h#L1669-1672

**Comment by sulliwane** [comment]
I see. So what do you recommend for my use case? Directly use libuv API ? Or maybe you know any "not too hacky" workaround that could use NaN for that ?
Thanks !

**Comment by kkoopa** [comment]
I am not entirely sure what your use case is. If AsyncProgressWorker does not suit your use case, you could always make something else that extends AsyncWorker. Do note that you need to ensure thread safety.

What you might want to do is to have `MyWorker::OnData` enque messages in the `toNode` queue.
Then in `MyWorker::Execute` you could drain the queue and send progress messages, since `ExecutionProgress` is accessible from this method.

**Comment by sulliwane** [comment]
Thank you for the examples. I understand that ```ExecutionProgress``` should not be instantiated by me, and is only available in the ```execute``` function. But I actually need to fire ```progress.send()``` in my ```MyWorker::OnData()``` callback, to notify that new data has been stacked in the ```toNode``` queue, and that at least one ```HandleProgressCallback``` should be fired. 

So the solution is probably to put a loop in the ```execute``` function (```while(true)```) that contiuously check if there is new data in ```toNode```, and if yes, then call ```progress.send()``` ? 

If yes, then I just need to figure out how to do this in a "thread safe manner" (I'm not really used to work with threads :)

**Comment by kkoopa** [comment]
Yes, something like that, but it should block/sleep inside the loop, and you will need a control variable to terminate the loop at some point when you need to kill the thread. I am not familiar with the `PCQueue` data structure, but if it is a Producer/Consumer queue, it likely has some blocking read operation available. It should also say that the consume operation is thread safe.

```c++
class MyWorker : public AsyncProgressWorkerBase<Message> {
  void Execute(ExecutionProgress &ep) {
    while (m_alive) {
      ep.Send(toNode.consume(), sizeof (Message));
    }
  }

  m_alive;
}
```

**Comment by sulliwane** [comment]
Got it! closing for now then. Many thanks for your help :)
