### ISSUE TITLE
Error while setting  v8::object value using  info.GetReturnValue.Set 

### ISSUE THREAD

**Issue by Manjunathbj** [nodejs/nan#648]
Please help to solve the below error
**Error -** 

**error: no matching function for call to ‘Nan::imp::Factory<v8::Object>::New(v8::Local<v8::Object>&)’    return imp::Factory<T>::New(arg0);**

**Code -** 
   v8::Local<v8::Object> xypair_obj = Nan::New<v8::Object>();
    xypair_obj->Set(Nan::New("x").ToLocalChecked(),Nan::New<String>(x.c_str()).ToLocalChecked());
    xypair_obj->Set(Nan::New("y").ToLocalChecked(),Nan::New<String>(y.c_str()).ToLocalChecked());
    xypair_obj->Set(Nan::New("status").ToLocalChecked(),Nan::New<String>(status.c_str()).ToLocalChecked());

    **info.GetReturnValue().Set(Nan::New<v8::Object>(xypair_obj)); -- Issue**

Below two cases i tried but didn't work
**Case 1 -** I tried by typecasting   info.GetReturnValue().Set(Nan::New<v8::Object>(Nan::To<v8::Object>(xypair_obj))); but return type of Nan::To is  Nan::MaybeLocal, it is not supported in New<T>.

**Case 2 -** I tried Nan::MaybeLocal<v8::Object> xypair_obj instead of v8::Local<v8::Object> xypair_obj .
But problem is i can't call  xypair_obj->Set because if we use MaybeLocal then no pointer object

Pls suggest how to solve this issue?

**Comment by kkoopa** [comment]
The `v8::Object` constructor does not take any actual arguments. You cannot counstruct a `v8::Object` from another `v8::Object`. Just set `xypair_obj` as the return value.

**Comment by Manjunathbj** [comment]
Thank you.
