### ISSUE TITLE
How to resolve v8 deprecated warnings 

### ISSUE THREAD

**Issue by Manjunathbj** [nodejs/nan#649]
Installed Node version - v - 7.7.1

warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /root/.node-gyp/7.7.1/include/node/v8.h:3657): Use maybe version [-Wdeprecated-declarations]  info.GetReturnValue().Set(cons->NewInstance(argc, argv));

Code -
 v8::Local<v8::Value> argv[argc] = { info[0] };
 v8::Local<v8::Function> cons = Nan::New<v8::Function>(constructor);
 info.GetReturnValue().Set(cons->NewInstance(argc, argv));

if we use Nan wrapper Nan::MaybeLocal instead of v8::Local <T> can't call cons->NewInstance function.

Pls suggest how to resolve this

**Comment by Manjunathbj** [comment]
Its resolved by using  info.GetReturnValue().Set(Nan::NewInstance(cons, argc, argv).ToLocalChecked());

**Comment by xudafeng** [comment]
work for me
