### ISSUE TITLE
Compile errors with v8

### ISSUE THREAD

**Issue by daveharmon** [nodejs/nan#656]
Hey guys,

I'm running into a bunch of errors when using nan 2.5.1 as a dependency to the [xpc-connection](https://github.com/sandeepmistry/node-xpc-connection) binding.  I was hoping it might be a version issue and I was hoping you guys could tell me what version of each I need to be using.  When I use node version: v7.7.3, and npm version: 4.1.2 I get these errors:

node-gyp rebuild

  CXX(target) Release/obj.target/binding/src/XpcConnection.o
In file included from ../src/XpcConnection.cpp:1:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/queue:169:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/deque:158:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__split_buffer:7:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:626:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:79:9: error: no member named 'strcoll' in the global namespace
using ::strcoll;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:80:9: error: no member named 'strxfrm' in the global namespace
using ::strxfrm;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:109:9: error: no member named 'strerror' in the global namespace
using ::strerror;
      ~~^
In file included from ../src/XpcConnection.cpp:1:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/queue:169:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/deque:158:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__split_buffer:7:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:628:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:606:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:346:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:90:
In file included from /usr/include/wchar.h:70:
/usr/include/_types.h:42:9: error: unknown type name '__uint32_t'
typedef __uint32_t      __darwin_wctype_t;
        ^
In file included from ../src/XpcConnection.cpp:1:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/queue:169:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/deque:158:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__split_buffer:7:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:628:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:606:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:346:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:90:
In file included from /usr/include/wchar.h:76:
/usr/include/sys/_types/_mbstate_t.h:31:9: error: unknown type name '__darwin_mbstate_t'; did you mean '__darwin_wctrans_t'?
typedef __darwin_mbstate_t mbstate_t;
        ^
/usr/include/_types.h:40:14: note: '__darwin_wctrans_t' declared here
typedef int             __darwin_wctrans_t;
                        ^
In file included from ../src/XpcConnection.cpp:1:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/queue:169:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/deque:158:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__split_buffer:7:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:628:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:606:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:346:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:90:
In file included from /usr/include/wchar.h:77:
/usr/include/sys/_types/_ct_rune_t.h:31:9: error: unknown type name '__darwin_ct_rune_t'; did you mean '__darwin_wctrans_t'?
typedef __darwin_ct_rune_t ct_rune_t;
        ^
/usr/include/_types.h:40:14: note: '__darwin_wctrans_t' declared here
typedef int             __darwin_wctrans_t;
                        ^
In file included from ../src/XpcConnection.cpp:1:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/queue:169:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/deque:158:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__split_buffer:7:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:628:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:606:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:346:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:90:
In file included from /usr/include/wchar.h:78:
/usr/include/sys/_types/_rune_t.h:30:9: error: unknown type name '__darwin_rune_t'; did you mean '__darwin_wctrans_t'?
typedef __darwin_rune_t rune_t;
        ^
/usr/include/_types.h:40:14: note: '__darwin_wctrans_t' declared here
typedef int             __darwin_wctrans_t;
                        ^
In file included from ../src/XpcConnection.cpp:1:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/queue:169:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/deque:158:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__split_buffer:7:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:628:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:606:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:346:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:90:
In file included from /usr/include/wchar.h:92:
In file included from /usr/include/_wctype.h:45:
/usr/include/sys/_types/_wint_t.h:31:9: error: unknown type name '__darwin_wint_t'; did you mean '__darwin_wctrans_t'?
typedef __darwin_wint_t wint_t;
        ^
/usr/include/_types.h:40:14: note: '__darwin_wctrans_t' declared here
typedef int             __darwin_wctrans_t;
                        ^
In file included from ../src/XpcConnection.cpp:1:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/queue:169:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/deque:158:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__split_buffer:7:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:628:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:606:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:346:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:90:
In file included from /usr/include/wchar.h:92:
/usr/include/_wctype.h:65:1: error: unknown type name '__header_inline'
__DARWIN_WCTYPE_TOP_inline int
^
/usr/include/_wctype.h:54:36: note: expanded from macro '__DARWIN_WCTYPE_TOP_inline'
#define __DARWIN_WCTYPE_TOP_inline __header_inline
                                   ^
/usr/include/_wctype.h:65:28: error: expected unqualified-id
__DARWIN_WCTYPE_TOP_inline int
                           ^
/usr/include/_wctype.h:71:1: error: unknown type name '__header_inline'
__DARWIN_WCTYPE_TOP_inline int
^
/usr/include/_wctype.h:54:36: note: expanded from macro '__DARWIN_WCTYPE_TOP_inline'
#define __DARWIN_WCTYPE_TOP_inline __header_inline
                                   ^
/usr/include/_wctype.h:71:28: error: expected unqualified-id
__DARWIN_WCTYPE_TOP_inline int
                           ^
/usr/include/_wctype.h:77:1: error: unknown type name '__header_inline'
__DARWIN_WCTYPE_TOP_inline int
^
/usr/include/_wctype.h:54:36: note: expanded from macro '__DARWIN_WCTYPE_TOP_inline'
#define __DARWIN_WCTYPE_TOP_inline __header_inline
                                   ^
/usr/include/_wctype.h:77:28: error: expected unqualified-id
__DARWIN_WCTYPE_TOP_inline int
                           ^
/usr/include/_wctype.h:83:1: error: unknown type name '__header_inline'
__DARWIN_WCTYPE_TOP_inline int
^
/usr/include/_wctype.h:54:36: note: expanded from macro '__DARWIN_WCTYPE_TOP_inline'
#define __DARWIN_WCTYPE_TOP_inline __header_inline
                                   ^
/usr/include/_wctype.h:83:28: error: expected unqualified-id
__DARWIN_WCTYPE_TOP_inline int
                           ^
/usr/include/_wctype.h:89:1: error: unknown type name '__header_inline'
__DARWIN_WCTYPE_TOP_inline int
^
/usr/include/_wctype.h:54:36: note: expanded from macro '__DARWIN_WCTYPE_TOP_inline'
#define __DARWIN_WCTYPE_TOP_inline __header_inline
                                   ^
/usr/include/_wctype.h:89:28: error: expected unqualified-id
__DARWIN_WCTYPE_TOP_inline int
                           ^
/usr/include/_wctype.h:95:1: error: unknown type name '__header_inline'
__DARWIN_WCTYPE_TOP_inline int
^
/usr/include/_wctype.h:54:36: note: expanded from macro '__DARWIN_WCTYPE_TOP_inline'
#define __DARWIN_WCTYPE_TOP_inline __header_inline
                                   ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]

Then when I build with node v4, 6, .10, or .12.  I see these errors (here, xpc-connection is still using namespace v8)

node-gyp rebuild

  CXX(target) Release/obj.target/binding/src/XpcConnection.o
In file included from ../src/XpcConnection.cpp:1:
In file included from /usr/include/c++/4.2.1/queue:65:
In file included from /usr/include/c++/4.2.1/bits/c++config.h:41:
In file included from /usr/include/c++/4.2.1/bits/os_defines.h:61:
In file included from /usr/include/unistd.h:71:
/usr/include/_types.h:42:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
typedef __uint32_t      __darwin_wctype_t;
        ^
note: '__uint128_t' declared here
In file included from ../src/XpcConnection.cpp:1:
In file included from /usr/include/c++/4.2.1/queue:65:
In file included from /usr/include/c++/4.2.1/bits/c++config.h:41:
In file included from /usr/include/c++/4.2.1/bits/os_defines.h:61:
In file included from /usr/include/unistd.h:74:
/usr/include/sys/_types/_gid_t.h:30:9: error: unknown type name '__darwin_gid_t'
typedef __darwin_gid_t  gid_t;
        ^
In file included from ../src/XpcConnection.cpp:1:
In file included from /usr/include/c++/4.2.1/queue:65:
In file included from /usr/include/c++/4.2.1/bits/c++config.h:41:
In file included from /usr/include/c++/4.2.1/bits/os_defines.h:61:
In file included from /usr/include/unistd.h:76:
/usr/include/sys/_types/_off_t.h:30:9: error: unknown type name '__darwin_off_t'
typedef __darwin_off_t          off_t;
        ^
In file included from ../src/XpcConnection.cpp:1:
In file included from /usr/include/c++/4.2.1/queue:65:
In file included from /usr/include/c++/4.2.1/bits/c++config.h:41:
In file included from /usr/include/c++/4.2.1/bits/os_defines.h:61:
In file included from /usr/include/unistd.h:77:
/usr/include/sys/_types/_pid_t.h:30:9: error: unknown type name '__darwin_pid_t'
typedef __darwin_pid_t        pid_t;
        ^
In file included from ../src/XpcConnection.cpp:1:
In file included from /usr/include/c++/4.2.1/queue:65:
In file included from /usr/include/c++/4.2.1/bits/c++config.h:41:
In file included from /usr/include/c++/4.2.1/bits/os_defines.h:61:
In file included from /usr/include/unistd.h:82:
/usr/include/sys/_types/_uid_t.h:30:9: error: unknown type name '__darwin_uid_t'
typedef __darwin_uid_t        uid_t;
        ^
In file included from ../src/XpcConnection.cpp:1:
In file included from /usr/include/c++/4.2.1/queue:65:
In file included from /usr/include/c++/4.2.1/bits/c++config.h:41:
In file included from /usr/include/c++/4.2.1/bits/os_defines.h:61:
In file included from /usr/include/unistd.h:83:
/usr/include/sys/_types/_useconds_t.h:30:9: error: unknown type name '__darwin_useconds_t'
typedef __darwin_useconds_t     useconds_t;
        ^
In file included from ../src/XpcConnection.cpp:1:
In file included from /usr/include/c++/4.2.1/queue:65:
In file included from /usr/include/c++/4.2.1/bits/c++config.h:41:
In file included from /usr/include/c++/4.2.1/bits/os_defines.h:61:
/usr/include/unistd.h:429:18: error: expected function body after function declarator
void     _exit(int) __dead2;
                    ^
/usr/include/unistd.h:436:17: error: expected function body after function declarator
int      close(int) __DARWIN_ALIAS_C(close);
                    ^
/usr/include/unistd.h:467:18: error: expected function body after function declarator
int      pause(void) __DARWIN_ALIAS_C(pause);
                     ^
/usr/include/unistd.h:471:36: error: expected function body after function declarator
ssize_t  read(int, void *, size_t) __DARWIN_ALIAS_C(read);
                                   ^
/usr/include/unistd.h:480:23: error: expected function body after function declarator
         sleep(unsigned int) __DARWIN_ALIAS_C(sleep);
                             ^
/usr/include/unistd.h:495:62: error: expected function body after function declarator
ssize_t  write(int __fd, const void * __buf, size_t __nbyte) __DARWIN_ALIAS_C(write);
                                                             ^
In file included from ../src/XpcConnection.cpp:1:
In file included from /usr/include/c++/4.2.1/queue:65:
In file included from /usr/include/c++/4.2.1/bits/c++config.h:41:
In file included from /usr/include/c++/4.2.1/bits/os_defines.h:61:
In file included from /usr/include/unistd.h:638:
In file included from /usr/include/sys/select.h:77:
/usr/include/sys/_types/_timeval.h:33:2: error: unknown type name '__darwin_suseconds_t'
        __darwin_suseconds_t    tv_usec;        /* and microseconds */
        ^
In file included from ../src/XpcConnection.cpp:1:
In file included from /usr/include/c++/4.2.1/queue:65:
In file included from /usr/include/c++/4.2.1/bits/c++config.h:41:
In file included from /usr/include/c++/4.2.1/bits/os_defines.h:61:
In file included from /usr/include/unistd.h:638:
In file included from /usr/include/sys/select.h:85:
/usr/include/sys/_types/_suseconds_t.h:30:9: error: unknown type name '__darwin_suseconds_t'
typedef __darwin_suseconds_t    suseconds_t;
        ^
In file included from ../src/XpcConnection.cpp:1:
In file included from /usr/include/c++/4.2.1/queue:65:
In file included from /usr/include/c++/4.2.1/bits/c++config.h:41:
In file included from /usr/include/c++/4.2.1/bits/os_defines.h:61:
In file included from /usr/include/unistd.h:638:
In file included from /usr/include/sys/select.h:86:
/usr/include/sys/_types/_sigset_t.h:30:9: error: unknown type name '__darwin_sigset_t'; did you mean '__darwin_size_t'?
typedef __darwin_sigset_t               sigset_t;
        ^
/usr/include/i386/_types.h:92:24: note: '__darwin_size_t' declared here
typedef __SIZE_TYPE__           __darwin_size_t;        /* sizeof() */
                                ^
In file included from ../src/XpcConnection.cpp:1:
In file included from /usr/include/c++/4.2.1/queue:65:
In file included from /usr/include/c++/4.2.1/bits/c++config.h:41:
In file included from /usr/include/c++/4.2.1/bits/os_defines.h:61:
In file included from /usr/include/unistd.h:638:
/usr/include/sys/select.h:121:3: error: expected function body after function declarator
                __DARWIN_1050(pselect)
                ^
In file included from ../src/XpcConnection.cpp:1:
In file included from /usr/include/c++/4.2.1/queue:65:
In file included from /usr/include/c++/4.2.1/bits/c++config.h:41:
In file included from /usr/include/c++/4.2.1/bits/os_defines.h:61:
In file included from /usr/include/unistd.h:638:
In file included from /usr/include/sys/select.h:129:
/usr/include/sys/_select.h:45:3: error: expected function body after function declarator
                __DARWIN_1050(select)
                ^
In file included from ../src/XpcConnection.cpp:1:
In file included from /usr/include/c++/4.2.1/queue:65:
In file included from /usr/include/c++/4.2.1/bits/c++config.h:41:
In file included from /usr/include/c++/4.2.1/bits/os_defines.h:61:
In file included from /usr/include/unistd.h:640:
/usr/include/sys/_types/_dev_t.h:30:9: error: unknown type name '__darwin_dev_t'
typedef __darwin_dev_t        dev_t;    /* device number */
        ^
In file included from ../src/XpcConnection.cpp:1:
In file included from /usr/include/c++/4.2.1/queue:65:
In file included from /usr/include/c++/4.2.1/bits/c++config.h:41:
In file included from /usr/include/c++/4.2.1/bits/os_defines.h:61:
In file included from /usr/include/unistd.h:641:
/usr/include/sys/_types/_mode_t.h:30:9: error: unknown type name '__darwin_mode_t'
typedef __darwin_mode_t         mode_t;
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]

Any thoughts?

**Comment by springmeyer** [comment]
@daveharmon I think this is a problem with your compiler/xcode setup. I'm also on OS X and I'm able to compile `xpc-connection` without issue on both node v4 and v7.1.0. Perhaps try `xcode-select --install` to ensure xcode is setup correctly?

**Comment by daveharmon** [comment]
I have tried that a couple times, what version of xcode do you have?  I have:

g++ -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

as my default g++.

I tried a few other versions of xcode, none seemed to change anything.

**Comment by bnoordhuis** [comment]
The first line should be something like:
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
```
Note the `MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk`.

**Comment by daveharmon** [comment]
Thanks for your help.  I had seen that suggestion elsewhere but couldn't find a solution to it.  What I ended up finding was setting the path to the sdk using the environment variable:

`export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/`
