### ISSUE TITLE
nan_json.h(113): error C2660: 'v8::JSON::Stringify': function does not take 3 arguments

### ISSUE THREAD

**Issue by seanzer** [nodejs/nan#658]
It appears nan 2.6 is incompatible with code written against 2.5.1. Why wasn't this a major release bump?

**Comment by mkrufky** [comment]
It's just a bug and we can fix it.  What version of node did you build against when you saw this error?

**Comment by mkrufky** [comment]
I see this could happen using v8 headers from version 5.2 ... Node 7.x uses v8 headers from version 5.4.x ...  A simple version check can fix this, so I'm putting up a new PR.  Meanwhile, it would be great to know exactly which version of node you are building against @seanzer .

**Comment by craxal** [comment]
Building an Electron (v1.3.1) app with Node 6.9.1. It looks like this change broke my team via `keytar` somehow.

**Comment by mkrufky** [comment]
OK, thanks for the report.  I'm pretty sure my PR #659 will fix this.  Hopefully somebody with merge rights can take a look at it and publish the fix ASAP.

**Comment by JakeRad** [comment]
Hey @mkrufky @kkoopa 
Is there any way we can get this merged in and a build kicked off? We're really struggling to find a way to work around this for an app based on Electron V1.3.1. Honestly we're not even sure why it's picking up the latest version when all of our dependencies (key tar) specify a specific version. 

We'd really appreciate an expedited release or a suggested work-around. We're using Electron V1.3.1 with electron-rebuild to build keytar.

**Comment by JakeRad** [comment]
Sorry to scream fire/wolf. We found a work-around. We were using keytar 3.0.0 instead of 3.0.2 and 3.0.2 specifies a specific version.

Thanks for looking into it @mkrufky
