### ISSUE TITLE
node version 6.9.x should be explicitly tested in CI

### ISSUE THREAD

**Issue by mkrufky** [nodejs/nan#661]
Apparently the current CI tests for node version `6` pull down node version `6.10.x` , but we've come to the realization last night / this morning that there is an ABI breakage between the `V8` headers used between those versions of node.

Let's try to avoid this in the future by also testing node version `6.9` explicitly on both Travis and Appveyor

**Comment by bnoordhuis** [comment]
> there is an ABI breakage between the V8 headers used between those versions of node

That sounds implausible.  What in particular are you referring to?

**Comment by mkrufky** [comment]
Maybe I am describing the problem incorrectly, but I am referring to the breakage last night when `nan 2.6.0` was published:  https://github.com/nodejs/nan/issues/658

Apparently there is a version of node just before version `7.0.0` that used `V8` headers from `5.2` whose `v8::JSON::Stringify` did not take the third `gap` argument.

We fixed `nan` by making sure we're on node 7 or later, inclusive (instead of simply testing for "later than node 6") and that's why `nan 2.6.1` got published today.

Meanwhile, now we know that `node 6` and `node 6.9` use different versions of the `V8` headers, so I think they should be explicitly tested.

**Comment by kkoopa** [comment]
If the issue only affected Electron, it is because Electron is non-compliant.

**Comment by kkoopa** [comment]
First appearance of `JSON::Stringify`
https://github.com/nodejs/node/blob/v7.0.0/deps/v8/include/v8.h#L1662

It is not present in either https://github.com/nodejs/node/blob/v6.9.0/deps/v8/include/v8.h#L1672 or https://github.com/nodejs/node/blob/v6.10.0/deps/v8/include/v8.h#L1672

**Comment by bnoordhuis** [comment]
Ah, Electron.  Testing node.js v6.9.x won't help then because that was never the issue.

FWIW, the diff between v6.9.5 and v6.10.0 is this and only this:
```diff
diff --git a/deps/v8/include/v8-version.h b/deps/v8/include/v8-version.h
index fb83ab5..e670d56 100644
--- a/deps/v8/include/v8-version.h
+++ b/deps/v8/include/v8-version.h
@@ -11,7 +11,7 @@
 #define V8_MAJOR_VERSION 5
 #define V8_MINOR_VERSION 1
 #define V8_BUILD_NUMBER 281
-#define V8_PATCH_LEVEL 89
+#define V8_PATCH_LEVEL 93
 
 // Use 1 for candidates and 0 otherwise.
 // (Boolean macro values are not supported by all preprocessors.)
```

**Comment by mkrufky** [comment]
Yes, and now I also see that arbitrarily testing `6.9.x` doesn't win us anything.   This breakage was entirely due to electron being non-compliant , as you said.   Let's not merge this.

**Comment by kkoopa** [comment]
Alright, good to have that sorted out. As far as non-compliant node-derivatives go (that includes Debian's nodejs package), we'll accommodate their quirks when reasonable, but they are not officially supported and do not get any testing.

**Comment by mkrufky** [comment]
I wanted to expose the 2 argument version of `v8::JSON::Stringify` directly to those electron users and use the javascript global `JSON` object to expose the 3 argument version, but perhaps I am just thinking too much.  It seems that I would have to test the `V8` header version itself instead of the node version in order to do this properly.

**Comment by kkoopa** [comment]
Yes, some years ago @bnoordhuis finally managed to convince the V8 team to include version information in the header. However, there is still the issue of missing floating patches and such. If you do cook something up, I will merge it at some point, but it will not be released until something else warrants a release.
