### ISSUE TITLE
win: _get_osfhandle crashes when getting the handle for an fd

### ISSUE THREAD

**Issue by jorangreef** [nodejs/nan#671]
This is specific to Windows.

It might be more of a libuv issue (see https://github.com/joyent/libuv/issues/1493) but when writing bindings using NAN is there any NAN wrapper that could expose libuv's _get_osfhandle to get the Handle for an fd?

I think the problem for bindings is that the fd is opened by the code compiled as part of Node, but _get_osfhandle can't lookup that fd when called from code compiled as part of a binding.

I think at present there is no way to resolve an fd to a Handle on Windows from a native add-on binding (i.e. any bindings that do fs work can't accept fds on Windows)?

**Comment by jorangreef** [comment]
Just to be clear _get_osfhandle is part of the Windows API, but we need a way for bindings to have access to the same _get_osfhandle linked by libuv.

**Comment by addaleax** [comment]
FYI: https://github.com/nodejs/node/issues/6369 & https://github.com/libuv/libuv/pull/1323

**Comment by jorangreef** [comment]
Thanks

**Comment by bnoordhuis** [comment]
Closing, https://github.com/libuv/libuv/pull/1323 happened.
