### ISSUE TITLE
question: why aren't you specifying `engines` in package.json

### ISSUE THREAD

**Issue by refack** [nodejs/nan#672]
As `npm i` fails if using an incompatible `node` version?
Ref: https://travis-ci.org/ProjectMirador/mirador/jobs/237638277#L146

**Comment by bnoordhuis** [comment]
There is no such as an incompatible node version: nan supports everything from v0.10.x onwards.

**Comment by refack** [comment]
Just figured that out 🤦‍♂️

**Comment by bnoordhuis** [comment]
Ah, I see your comment in the other issue.  For posterity: https://github.com/nodejs/node-gyp/issues/1211 - but that was a travis configuration issue, not anything to do with nan.

**Comment by refack** [comment]
Updated "For posterity" https://github.com/nodejs/node-gyp/issues/1211#issuecomment-304984565

**Comment by Ibe-Sarah** [comment]
I've been faced with similar issues but right now, I'm stuck with determining what node-gyp version is compatible with node version 8.17.0 and node-sass 4.5.3. Any help please? Thank you
