### ISSUE TITLE
Node.js 8 support?

### ISSUE THREAD

**Issue by unbornchikken** [nodejs/nan#674]
Hi,

Will there be a release for supporting Node.js 8, or should we rewrite everything in N-API?

**Comment by bnoordhuis** [comment]
Node 8 should work out of the box.  Doesn't it for you?

**Comment by unbornchikken** [comment]
It didn't, but turned out that was my fault, I've accidentally referenced an older version nan. Anyway, keep up the good work, N-API would be the most important thing since io.js in this platform!

**Comment by mateodelnorte** [comment]
Hi fellas. Just want to be explicit here - Is the recommended path still to write addons using NAN, and NAN will also cover compatibility between pre Node 8 versions and moving to N-API?

Cheers!

**Comment by kkoopa** [comment]
Yes, you should still use NAN for production use. It covers every relevant version of Node.js. Also note that N-API is not intended for end users. You should eventually use https://github.com/nodejs/node-addon-api.
