### ISSUE TITLE
How to return a pointer ?

### ISSUE THREAD

**Issue by xmkevin** [nodejs/nan#677]
Hi,  I want to open a slide(file) and return the handle, which will be hold on js, how can I do this ?

`Nan::EscapableHandleScope scope;
  long osr = (long)openslide_open(fileName.c_str());
  Handle<v8::Value> retval = Nan::New(To<int64_t>(osr));
  info.GetReturnValue().Set(scope.Escape(retval));`

**Comment by xmkevin** [comment]
I am new to C++ and Nan, should I use NAN or N-API ?

**Comment by mkrufky** [comment]
Stick with _NAN_. You're going to want to wrap the pointer with an `ObjectWrap` as described in the "Passing wrapped objects around" section here:  [Object Wrappers](https://github.com/nodejs/nan/blob/master/doc/object_wrappers.md)

If you're new to C++ and working with _NAN_ bindings, you may want to take a look here as well: [Node.js Addon Examples](https://github.com/nodejs/node-addon-examples)

I'd recommend going through the _NAN_ example given in each section of that tutorial.

**Comment by xmkevin** [comment]
Tks

**Comment by ORESoftware** [comment]
Still stick with NAN? I thought NAPI was the newer version to use?
