### ISSUE TITLE
why NAN_METHOD no need to insert a HandleScope?

### ISSUE THREAD

**Issue by yunnysunny** [nodejs/nan#678]
> Allocate a new Nan::HandleScope whenever you are creating new V8 JavaScript objects. Note that an implicit HandleScope is created for you on JavaScript-accessible methods so you do not need to insert one yourself.

> Example:
>
```c++
// new object is created, it needs a new scope:
void Pointless() {
  Nan::HandleScope scope;
  v8::Local<v8::Object> obj = Nan::New<v8::Object>();
}

// JavaScript-accessible method already has a HandleScope
NAN_METHOD(Pointless2) {
  v8::Local<v8::Object> obj = Nan::New<v8::Object>();
}
```
>
And the macro of `NAN_METHOD`  is defined as follows:

```c++
#define NAN_METHOD(name)                                                       \
    Nan::NAN_METHOD_RETURN_TYPE name(Nan::NAN_METHOD_ARGS_TYPE info)
```
I did not find `an implicit HandleScope ` in the definition, if it is created by V8 internal?
I read the addons  document supplied via offical, it need a isolate variable which can be use for creating of handle scope:
```
void Method(const FunctionCallbackInfo<Value>& args) {
  Isolate* isolate = args.GetIsolate();
  args.GetReturnValue().Set(String::NewFromUtf8(isolate, "world"));
}

void init(Local<Object> exports) {
  NODE_SET_METHOD(exports, "hello", Method);
}

NODE_MODULE(addon, init)
```

**Comment by XadillaX** [comment]
because it's already declared in the outter scope.

**Comment by yunnysunny** [comment]
@XadillaX The behaviour of  `declaring in the outter scope`  is done by V8 or Nan? Where can I find it?

**Comment by addaleax** [comment]
@yunnysunny It’s done by V8, and if I’m not mistaken it’s this HandleScope that you’re looking for: https://github.com/nodejs/node/blob/a8979a605434b0a07395c9764caafef362f3875e/deps/v8/src/builtins/builtins-api.cc#L129

**Comment by kkoopa** [comment]
Node.js sets up a handle scope before calling your V8 callback, libuv does not set up a handle scope when calling its callbacks.

**Comment by yunnysunny** [comment]
In official's [document](https://nodejs.org/dist/latest-v6.x/docs/api/addons.html), it need a isolate:
```
void Method(const FunctionCallbackInfo<Value>& args) {
  Isolate* isolate = args.GetIsolate();
  args.GetReturnValue().Set(String::NewFromUtf8(isolate, "world"));
}
```
In Nan , we can just write such code : 
```
NAN_METHOD(Method) {
  info.GetReturnValue().Set(Nan::New<String>("world").ToLocalChecked());
}
```
If the `isolate` is not used for creating HandleScope , why does the official's code need it? And how does nan do to create string without  `isolate`?

**Comment by addaleax** [comment]
> If the `isolate` is not used for creating HandleScope , why does the official's code need it?

For creating the string, but you already seem to have figured that out. :)

> And how does nan do to create string without  `isolate`?

It uses `v8::Isolate::GetCurrent()` every time you create a new string, which comes with a small bit of overhead.

**Comment by yunnysunny** [comment]
I check the code of [nan_implementation_12_inl.h](https://github.com/nodejs/nan/blob/master/nan_implementation_12_inl.h#L281) and find  Nan's implementation the method of `Nan::New<String>`.

**Comment by XadillaX** [comment]
@yunnysunny I'm writting a book about writting a c++ native addon for Node.js.
