### ISSUE TITLE
create window in the nodejs addon

### ISSUE THREAD

**Issue by fshang** [nodejs/nan#679]
i made a nodejs addon for electron.and i created a window with win32 api Createwindow(...).but the mouse cursor is loading status when i called the addon. until the call is end. how can i reslove it ? please help me ,thank you!

**Comment by bnoordhuis** [comment]
Not a good question for this bug tracker.  Maybe try https://github.com/nodejs/help/issues although you'll probably have better luck in a Windows developer forum.
