### ISSUE TITLE
Get process argc/argv without using js process.argv

### ISSUE THREAD

**Issue by ctubio** [nodejs/nan#681]
sorry is there any way to get the current process argc/argv?
(i mean the arguments passed by the user in the command line while executing the nodejs app)

currently im getting from js the [process.argv](https://nodejs.org/docs/latest/api/process.html#process_process_argv) array and im passing the array from js to c++, is there any way to avoid this and get the args directly from the c++ addon code?

many thanks for your time''' (i search hard but couldnt find it :sob:)

**Comment by bnoordhuis** [comment]
There isn't.  Not in nan, not in the node.js C++ API.

**Comment by ctubio** [comment]
ok many thanks
