### ISSUE TITLE
Resolve return array

### ISSUE THREAD

**Issue by bernex** [nodejs/nan#685]
```
Local<v8::Int32> argv[] = {
     Nan::New(estimate), Nan::New(1212222)
};

auto res = GetFromPersistent("resolver").As<v8::Promise::Resolver>();
res->Resolve(Nan::New<v8::Context>(), argv);
```

But second parameter must be `Local<Value>`

How return?

**Comment by kkoopa** [comment]
You seem to be passing an array where a single element is expected.

**Comment by bernex** [comment]
My code is not working (

**Comment by kkoopa** [comment]
The only way of resolving a `v8::Promise` with an array is constructing a `v8::Array`. However, this issue has nothing with NAN to do, so I will close this.
