### ISSUE TITLE
NAN_EXPORT integer property

### ISSUE THREAD

**Issue by jorangreef** [nodejs/nan#696]
I have gone through the docs and tried a few things (property getters etc.) but have not been able to get this working.

Is there a way to export a integer property from a nan module, e.g.:

```
uint32_t FLAGS = 32;
NAN_EXPORT(target, FLAGS);
```

Then in Node, the user could do:

```
console.log(typeof require('./binding.node').FLAGS == 'number');
```

**Comment by agnat** [comment]
Not in Nan. But there is a utility in Node proper: [`NODE_DEFINE_CONSTANT`](https://github.com/nodejs/node/blob/master/src/node.h#L235)

**Comment by jorangreef** [comment]
Thanks alot!
