### ISSUE TITLE
How to unset a property ?

### ISSUE THREAD

**Issue by MatthD** [nodejs/nan#710]
Hi everyone,

How to unset a set property ? I want to delete it, not just empty the array.

```jsons
  v8::Local<v8::Array> anArray = Nan::New<v8::Array>();
  // Do something with the array & set it
  info.Holder()->Set(Nan::New<v8::String>("aSublimeArray").ToLocalChecked(), anArray);

 // Now I want to delete this property , how to do ?
```

**Comment by kkoopa** [comment]
https://github.com/nodejs/nan/blob/master/doc/maybe_types.md#api_nan_delete

**Comment by MatthD** [comment]
Hi thanks for the doc, I just did something like : 

`info.Holder()>Set(Nan::Deletev8::Local<v8::Object>info.Holder().ToLocalChecked(),"validationError");`

But It's not this , I have difficulty to find the right syntax because no IDE  can do NAN correctly :s

**Comment by kkoopa** [comment]
```c++
v8::Local<v8::Array> anArray = Nan::New<v8::Array>();
info.Holder()->Set(Nan::New<v8::String>("aSublimeArray").ToLocalChecked(), anArray);
bool deleted = Nan::Delete(info.Holder(), Nan::New<v8::String>("aSublimeArray").ToLocalChecked())).FromMaybe(false);
```
