### ISSUE TITLE
Invite mkrufky to workgroup

### ISSUE THREAD

**Issue by kkoopa** [nodejs/nan#712]
I am not sure how this is supposed to work nowadays, but I would believe it falls under the self-governance part of workgroups. He is actively making solid contributions and has done so for a long time now. I have not been proactive in regards to workgroup maintenance, but figured it is never too late to make amends.

cc @mkrufky

**Comment by bnoordhuis** [comment]
+1 from me.

**Comment by agnat** [comment]
+1.

**Comment by kkoopa** [comment]
Okay, I found the charter in the README and it says we need consensus amongst existing WG members who post in the issue, and a simple majority amongst all WG members. Since there are 7 members, we need one more. Perhaps @rvagg can chime in?

**Comment by rvagg** [comment]
+1

**Comment by mkrufky** [comment]
It was very nice to see this as I was scrolling through my github news feed today.  It really makes me feel appreciated.  Thanks :-)

**Comment by kkoopa** [comment]
Alrighty, they yays have it. (I vote yes, for the record.) I believe I have sent out the invite now. You can update the readme and add yourself to the list and your optional twitter handle if you have one.
