### ISSUE TITLE
2.8.0 Bug for sodium package

### ISSUE THREAD

**Issue by vekexasia** [nodejs/nan#716]
Hello guys,

apparently `sodium` package which depends on `nan` cannot be compiled anymore due to `2.8.0`.

Here is the issue i've opened there. https://github.com/paixaop/node-sodium/issues/124

**Comment by bnoordhuis** [comment]
They're just warnings, not errors.  Closing, not a valid (or good) bug report.

**Comment by vekexasia** [comment]
Actually it does not compile. 

```
Error: make nodesodium exited with code null
    at ChildProcess.<anonymous> (/home/andrea/node_modules/sodium/install.js:288:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
```

**Comment by kkoopa** [comment]
That is a separate issue which is not relevant here.

**Comment by anibali** [comment]
A minor release that breaks things for dependants (and hence potentially violates semver) should at least be investigated as a valid bug, right?

**Comment by bnoordhuis** [comment]
There is nothing here that suggests it's actually an issue with nan.

**Comment by anibali** [comment]
So it is expected that a minor version bump to `nan` may break dependant packages that have not themselves changed in any way?

**Comment by agnat** [comment]
No, of course not.

 But if you look carefully _nothing_ in the upstream bug report indicates a nan related error. It's just a warning. So, the thing pasted in the upstream bug is not what caused the build to fail. Hence, there is no indication that this actually nan's fault. If we get to see the _actual_ error we'll certainly investigate.

> Closing, not a valid (or good) bug report.

See what @bnoordhuis means?

**Comment by anibali** [comment]
I'm not trying to argue that this was a well-reported bug, just that there does seem to be a bug there :)

The issue was never the warnings, but the fact that part of the node-sodium install code (https://github.com/paixaop/node-sodium/blob/2ba53357c1e1458c156b0e2933509eebdcc8a1fa/install.js#L286-L292) started failing with nan 2.8.0, making node-sodium impossible to install. As far as I can tell from my own sleuthing, all that chunk of code does is run `nodegyp rebuild` as a child process (via `make`), which worked for nan < 2.8.0 but now gets terminated by signal (indicated by the null return code).

**Comment by bnoordhuis** [comment]
What's the signal?  What gets printed to the screen?

> just that there does seem to be a bug there

It's unlikely.  Nan is widely used, any actual breaking change would have us swamped in bug reports.  Odds are better than even it's a node-sodium bug.

**Comment by anibali** [comment]
What gets printed to screen is exactly what the original reporter linked, which admittedly isn't very useful, but also isn't "just warnings":

```
/home/aiden/Projects/Node/node-sodium/install.js:289
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make nodesodium exited with code null
    at ChildProcess.<anonymous> (/home/aiden/Projects/Node/node-sodium/install.js:289:19)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.1 install: `node install.js --install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@2.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aiden/.npm/_logs/2017-11-24T01_05_00_019Z-debug.log
```

After some poking around I found that the signal was SIGTERM. So perhaps the upgrade to nan 2.8.0 somehow causes `node-gyp rebuild` to end via SIGTERM? Using nan 2.7.0 works fine, no signal.

**Comment by anibali** [comment]
After even more investigation, I think I've figured it out. [child_process.exec](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) was killing the node-gyp child process due to `maxBuffer` being reached, since upgrading to nan 2.8.0 causes a lot more warnings to be printed out.

So I suppose that the bug is invalid after all, but you have to admit---it's a pretty odd situation! Technically the upgrade to nan 2.8.0 _did_ cause node-sodium to stop building ;)

**Comment by agnat** [comment]
How is a broken build script an odd situation?

**Comment by agnat** [comment]
But congrats for solving it!

**Comment by victortony** [comment]
i encountered this problem, too. The version of nan is 2.6.2

Build node-sodium module
node-gyp rebuild
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: unexpected end of file
gyp ERR! stack     at Gunzip.zlibOnError (zlib.js:152:15)
gyp ERR! System Linux 4.9.49-moby
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /src/server/node_modules/sodium
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
make: *** [Makefile:80: nodesodium] Error 1
/src/server/node_modules/sodium/install.js:288
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make nodesodium exited with code 2
    at ChildProcess.<anonymous> (/src/server/node_modules/sodium/install.js:288:19)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@1.2.3 install: `node install.js --install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@1.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by bnoordhuis** [comment]
@victortony Different issue.  "Unexpected end of file" means a corrupted download.  `rm -rf ~/.node-gyp/` and try again.
