### ISSUE TITLE
Question of calling .so file from nan 

### ISSUE THREAD

**Issue by jimmylin212** [nodejs/nan#720]
Not sure it's `nan` problem or `node-gyp` problem. I would like to call my `.so` file from nan, but I am confused with the document. 

My problem could be separated into 
1. In order to call .so from c or nodejs, should I put the so file in `direct_dependent_settings` or `link_settings`?
2. How to include or use the functions in .so file from my c++ code?

My `binding.gyp` looks like:

```json
{
  "targets": [
    {
      "target_name": "mysofile",
      "type": "static_library",
      "sources": ["/path/to/file.so", "main.cc"],
      "include_dirs": [
        "<!(node -e \"require('nan')\")",
        ""
      ],
      "link_settings" : {
        "libraries" : ["-ldl"]
      }
    }
  ]
}

```
and my `main.cc` is below:

```c++
#include <nan.h>

void PrintDebug(const Nan::FunctionCallbackInfo<v8::Value>& printString) {
  printDebug(printString); //printDebug is a function within .so file
}

void InitChifDll(v8::Local<v8::Object> exports) {
  exports->Set(Nan::New("hello").ToLocalChecked(),
               Nan::New<v8::FunctionTemplate>(PrintDebug)->GetFunction());
}

NODE_MODULE(chifdll, InitChifDll)
```
It's seems a basic question, but I just can't figure it out.

Thank you very much for your help !!

**Comment by bnoordhuis** [comment]
Let's start off with the observation that your question is not specific to nan.  nodejs/help would have been a more appropriate place to post it.

With that out of the way, you link against a shared library like this:
```python
'libraries': ['-L/path/to', '-lfile'],  # requires that the file is called libfile.so
'ldflags': ['-Wl,-rpath,/path/to/libfile.so'],
```
The `-L...` and `-rpath`switches aren't necessary if the shared library lives in a standard location, like /usr/lib.

As to how you use it - like you use any external component: include the appropriate header files and build it.

**Comment by jimmylin212** [comment]
Thank you for reply.

Even if I use the .so file, I still need to include the `.h` file in my c++ code, right? Kindly help to check the final file, do I need to remove the `"/path/to/libfile.so"` from column sources?

```json
{
      "target_name": "chifdll",
      "type": "static_library",
      'sources': ["/path/to/libfile.so", "main.cc"],
      "include_dirs": [
        "<!(node -e \"require('nan')\")",
      ],
      "libraries": ["-L/path/to/", "-lfile"],
      "ldflags": ["-Wl,-rpath,/path/to/libfile.so"],
      "link_settings" : {
        "libraries" : ["-ldl"]
      }
    }
```

**Comment by bnoordhuis** [comment]
It shouldn't be in 'sources', no.

**Comment by jimmylin212** [comment]
Thank you very much.
I will post another issue on node-gyp and close this one.
