### ISSUE TITLE
Call function from Nodejs failed

### ISSUE THREAD

**Issue by jimmylin212** [nodejs/nan#721]
Hi, I would like to call function that I wrote in C++ from my `.js` file but it failed even I tried many different ways. The purpose of the function is go through the input `args` and check the type of each arg, then transfer it to C++ type. 

Another question is how can I pass the arguments into function in my `void J2C`?

My C++ code is below:
```c++
void J2C(const Nan::FunctionCallbackInfo<v8::Value>& args) {
    
    for (int i = 0; i < args.Length(); i++) {
        Local<Function> fn;
        Local<FunctionTemplate> tpl;

        if (args[i] -> IsNumber()) {
            tpl = Nan::New<FunctionTemplate>(J2CNumber);
        } else if (args[i] -> IsBoolean()) {
            tpl = Nan::New<FunctionTemplate>(J2CBoolean);
        } else if (args[i] -> IsString()) {
            tpl = Nan::New<FunctionTemplate>(J2CString);
        } else if (args[i] -> IsArray()) {
            tpl = Nan::New<FunctionTemplate>(J2CArray);
        } else if (args[i] -> IsObject()) {
            tpl = Nan::New<FunctionTemplate>(J2CObj);
        } else {
            continue;
        }
    
        fn = tpl->GetFunction();
        fn->SetName(Nan::New("j2c").ToLocalChecked());
        args.GetReturnValue().Set(fn);
    }
 }

void Init(Local<Object> exports, Local<Object> module) {
    Nan::SetMethod(module, "exports", J2C);
}

NODE_MODULE(convertor, Init)
```

My javascript code is below:
```javascript
var convertor = require('./build/Release/convertor.node');
var fn = convertor();
console.log(fn([1, 2]));
```

it always throw error: **TypeError: fn is not a function** in line 3.

Thank you very much for your help.

**Comment by agnat** [comment]
> Let's start off with the observation that your question is not specific to nan. nodejs/help would have been a more appropriate place to post it.

Still true...

That said, I believe you're confused by your own code... Try this: Put a couple of debug `print(...)` lines in there. Then watch...

You'll notice that `J2C` is called in line 2 of your js code. It just doesn't do anything because it has no arguments...

Closing as not a nan issue.

**Comment by agnat** [comment]
See https://github.com/nodejs/node-addon-examples
