### ISSUE TITLE
feature request: add `Nan::HasInstance` back or `Nan::InstanceOf`

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/nan#722]
`Nan::HasInstance` was removed in https://github.com/nodejs/nan/commit/30cc9cb67f74620aaea6a6bf56d85c35164a6d7e in favor of `tpl->HasInstance(value)`, but in v8 v6.x <del>this API was removed</del>(EDIT: this is not removed) `value->InstanceOf(context, ctor)` was added. It would be useful to add a normalized API back for this to ease the compatibility work. I can open a PR if there is no strong objection.

**Comment by bnoordhuis** [comment]
In light of your edit - do you still want to pursue this?

**Comment by joyeecheung** [comment]
No, now that I discovered `HasInstance` seems to be in the lkgr there is no need to add a compatibility API yet. Sorry for the noise.
