### ISSUE TITLE
Knowing when a wrap object is ready to be garbage collected

### ISSUE THREAD

**Issue by jackcaron** [nodejs/nan#737]
I have a particular wrap object and store internally a lot of memory, but that memory doesn't show up in the V8 stats, because it's allocated inside, through another object.

The problem is that this memory only gets deallocated when that wrapped object is garbage collected. Is there a way to know when that object is not in used anymore, so we could do internal clean up way before it is GC'ed?

I tried overriding the *Unref* function, but I never saw it getting called.

**Comment by kkoopa** [comment]
Don't know off the top of my head how to do it with `ObjectWrap` directly, but if you have a `Persistent` handle somewhere, you can make it weak and give it a callback which triggers as the object is being garbage collected.

**Comment by jackcaron** [comment]
But I need this to happen way before the GC is in action.

I checked in the stack trace and one of the item in the call is *WeakCallback*. But the problem is that the GC might runs seconds after that object is not in used anymore.

In our use case, that wrapped object is referring to a bigger data structure (*coming from the library with want to wrap in an addon*), that can end up being megabytes in size. But for JS, that object is probably a most a kilobyte for storing all that stuff.

```js
let a = MyWrappedObject();
//...
let b = a;
// DO things
a = null;
//...
b = null; // this was the last reference, I want a sort of callback or virtual function that is triggered by that so I can ask to deallocate that huge data structure.
//...
// LATER: garbage collector runs and finish destroying that object
```
Maybe *WeakCallback* could do that, but I cannot find any example on how to add that. If that's the solution, a simple snippet would be really great. And maybe updating the docs for *nan* to have that example around.

**Comment by kkoopa** [comment]
No, there is no such mechanism. For starters, garbage collection is nondeterministic. It need never occur.
Additionally, `ObectWrap::Unref` is not a callback. See [the implementation](https://github.com/nodejs/nan/blob/master/nan_object_wrap.h#L86-L113) of `ObjectWrap`.

You have to manage reference counts and actions to take when reaching 0 in your derived class if you want reference counting.

**Comment by jackcaron** [comment]
That's what I thought, so far, we have to force the user of the lib to call a *free* function when they know the life cycle is over. Because like you said, the GC might not need to run at all.

Thanks for the quick answers @kkoopa.

**Comment by kkoopa** [comment]
That is the recommended way, but there might be an alternative if all you want is to free memory more aggressively: You can use `Nan::AdjustExternalMemory` to inform the garbage collector of external memory pressure.

**Comment by jackcaron** [comment]
That is way more aggressive... the GC is called way more. Thanks.

**Comment by kkoopa** [comment]
You are welcome. Do not forget to readjust the external memory as the pressure is relieved.
