### ISSUE TITLE
Wrapping objects: the document makes me confused.

### ISSUE THREAD

**Issue by wlzla000** [nodejs/nan#748]
I'm familiar with Javascript, but new to C++ and V8; I'd appreciate it if you could help me out understand these things.

https://github.com/nodejs/nan/blob/master/doc/object_wrappers.md

-----

```cpp
  static inline Nan::Persistent<v8::Function> & constructor() {
    static Nan::Persistent<v8::Function> my_constructor;
    return my_constructor;
  }
```

 Why does the document declare a _constructor_ in this way? Can't we just use

```cpp
static const Nan::Persistent<v8::Function> constructor;
```

in the header, and use `constructor` instead of `constructor()`?

-----

```cpp
  static NAN_METHOD(New) {
    if (info.IsConstructCall()) {
      double value = info[0]->IsUndefined() ? 0 : Nan::To<double>(info[0]).FromJust();
      MyObject *obj = new MyObject(value);
      obj->Wrap(info.This());
      info.GetReturnValue().Set(info.This());
    } else {
      const int argc = 1;
      v8::Local<v8::Value> argv[argc] = {info[0]};
      v8::Local<v8::Function> cons = Nan::New(constructor()); /// Q1
      info.GetReturnValue().Set(cons->NewInstance(argc, argv)); /// Q2
    }
  }
```

```cpp
  static NAN_METHOD(New) {
    if (info.IsConstructCall()) {
      double value = info[0]->IsNumber() ? Nan::To<double>(info[0]).FromJust() : 0;
      MyFactoryObject * obj = new MyFactoryObject(value);
      obj->Wrap(info.This());
      info.GetReturnValue().Set(info.This());
    } else {
      const int argc = 1;
      v8::Local<v8::Value> argv[argc] = {info[0]};
      v8::Local<v8::Function> cons = Nan::New(constructor()); /// Q1
      info.GetReturnValue().Set(Nan::NewInstance(cons, argc, argv).ToLocalChecked()); /// Q2
    }
  }
```

 1. As well as a `Local`, a `Persistent` is also a `Handle`, which overrides the `->` operator. Can't we just use it as it is? Why does it make a `Local` copy of the `Persistent` `Function` handle?

 2. Why does the former use `v8::Function#NewInstance()` while the latter uses `Nan::NewInstance`?
 Shouldn't we stick to _Nan_ for compatibility?

**Comment by kkoopa** [comment]
You can simply declare the constructor and use that if you like.

1. If it compiles, yes.
2. Oversight, it should use `Nan::NewInstance`

**Comment by wlzla000** [comment]
@kkoopa Thank you so much and I'm sorry for bothering you again. May I ask a question: should I avoid using `NAN_METHOD`?

**Comment by wlzla000** [comment]
Thank you so much for your help. Closing this interrogative issue.

**Comment by wlzla000** [comment]
The reason why it used

```cpp
  static inline Nan::Persistent<v8::Function> & constructor() {
    static Nan::Persistent<v8::Function> my_constructor;
    return my_constructor;
  }
```

instead of

```cpp
static const Nan::Persistent<v8::Function> constructor;
```

was that, **unlike Javascript**, by making the object `const`, the compiler forbids modification of its members, hence its methods that modify its members as well. That's how C++ works. So I need to make it non-`const` and prevent it from being _replaced_; thus, the wrapper function (I don't know the C++ term for it) is used.

> [**`const` object** - an object whose type is `const`-qualified, or a non-mutable subobject of a `const` object. **Such object cannot be modified**: attempt to do so directly is a compile-time error, and attempt to do so indirectly (e.g., by modifying the `const` object through a reference or pointer to non-`const` type) results in _undefined behavior_.](http://en.cppreference.com/w/cpp/language/cv)

**Comment by wlzla000** [comment]
**`Nan::NewInstance` does not accept a `Nan::Persistent` as its argument!** So it cannot be compiled without making the `Persistent` handle `Local` with `Nan::New(......)`.

```cpp
Nan::MaybeLocal<v8::Object> Nan::NewInstance(v8::Local<v8::Function> h);
Nan::MaybeLocal<v8::Object> Nan::NewInstance(v8::Local<v8::Function> h, int argc, v8::Local<v8::Value> argv[]);
Nan::MaybeLocal<v8::Object> Nan::NewInstance(v8::Local<v8::ObjectTemplate> h);
```

@kkoopa I'm sorry for bothering you again; could you please help me understand the reason why it does not accept (“support”?) a `Nan::Persistent`?

**Comment by kkoopa** [comment]
A `Local` must be created at some point. Creating a `Local` from a `Persistent` is easy, so you must make a `Local` from the `Persistent`.
