### ISSUE TITLE
Sending a another wrapped oject from native addon function

### ISSUE THREAD

**Issue by jay11ca39** [nodejs/nan#750]
Hello All,
I am writing native addon for my CPP library.
I have 2 classes:

```
  class A : public Nan::ObjectWrap
    {
        public:
            static void Init(v8::Local<v8::Object> exports);
            virtual ~A();

        private:
            static void New(const Nan::FunctionCallbackInfo<v8::Value>& info);

             ...................other methods.................

            static Nan::Persistent<v8::Function> constructor;
    };
```

```
  class B : public Nan::ObjectWrap
    {
        public:
            static void Init(v8::Local<v8::Object> exports);
            virtual ~B();

        private:
            static void New(const Nan::FunctionCallbackInfo<v8::Value>& info);
            static void GetAObj(const Nan::FunctionCallbackInfo<v8::Value>& info);
           
             ...................other methods.................

            static Nan::Persistent<v8::Function> constructor;
    };
```

In class B there is a method: **GetAObj** , in this method i want to return a Class A object to javascript and from javascript I want to use that A class object to make function call of class A.

Can anybody help me out in defining GetAObj method of class B ? 

Thanks in advance.

**Comment by agnat** [comment]
Here is an (untested) starting point:

````
v8::Local<v8::Function> constructor = A::GetConstructor();
info.GetReturnValue().Set(Nan::NewInstance(constructor).ToLocalChecked());
````

`GetConstructor()` is a trivial getter for the constructor function of A. This snippet will return a JS wrapped instance of `A`.

Hope this helps.

**Comment by jay11ca39** [comment]
Hi @agnat ,
Thanks for your reply. i am getting the below error :
`../src/B.cc:146:47: error: ‘GetConstructor’ is not a member of ‘A’`

Also i have one more thing to ask, in the wrapped object [A] i want make some calls to some fields of the newly constructed object and then finally return wrapped object to javascript.

**Comment by agnat** [comment]
Hehe ... you have to *implement* `GetConstructor()`... or provide some other way to access the constructor of `A`.

Regarding your second question: `Nan::NewInstance()` returns the wrapped object. Just `unwrap()` the native instance in the usual way...

**Comment by jay11ca39** [comment]
Hello @agnat ,
I got the constructor of class A: 
static Nan::Persistent<v8::Function> constructor;

build is fine now..
But when I called method : static void GetAObj(const Nan::FunctionCallbackInfo<v8::Value>& info);
from JS , I got the following error:

```
node: ../node_modules/nan/nan_object_wrap.h:33: static T* Nan::ObjectWrap::Unwrap(v8::Local<v8::Object>) [with T = A]: Assertion `object->InternalFieldCount() > 0' failed.
Aborted (core dumped)
```

**Comment by agnat** [comment]
Happy to point you in the right direction, but I'm not going to debug this further. I'd recommend reading the [nodejs/node-addon-examples](https://github.com/nodejs/node-addon-examples). General programming questions can be asked at [nodejs/help](https://github.com/nodejs/help)

**Comment by jay11ca39** [comment]
Hi @agnat ,
I have raised the question as you said but it since 3-4 days, nobody replied. Because of that I am trying some other way around.

Now, In my scenario I defined a method in class B and that method is taking class A object as its argument.

```
NAN_METHOD(B::SetAClassObject)
{
   B* bObj = ObjectWrap::Unwrap<B>(info.Holder());  // Working fine
   A* aObj = Nan::ObjectWrap::Unwrap<A>(info[0].As<Object>());  //This is the problem
}

```
Code is compiling fine. But while calling this API from JS application, I am getting **following error**:

```
node: ../node_modules/nan/nan_object_wrap.h:33: static T* Nan::ObjectWrap::Unwrap(v8::Local<v8::Object>) [with T = nezmq::A]: Assertion `object->InternalFieldCount() > 0' failed.
Aborted (core dumped)
```

On checking, I found the InternalFieldCount is zero for the class A object which is the problem. 

@agnat  and @kkoopa , 
can you please help me in this if this issue is known to you.

Thanks in advance.

**Comment by kkoopa** [comment]
You are doing something wrong. This works just fine for me:
```c++
class A : public ObjectWrap {
 public:
  static NAN_MODULE_INIT(Init) {
    v8::Local<v8::FunctionTemplate> tpl = Nan::New<v8::FunctionTemplate>(New);
    tpl->SetClassName(Nan::New("A").ToLocalChecked());
    tpl->InstanceTemplate()->SetInternalFieldCount(1);

    constructor().Reset(Nan::GetFunction(tpl).ToLocalChecked());
    Set(target, Nan::New("A").ToLocalChecked(),
      Nan::GetFunction(tpl).ToLocalChecked());
  }

  static Persistent<v8::Function> &constructor() {
    static Persistent<v8::Function> my_constructor;
    return my_constructor;
  }

 private:
  ~A() {}

  static NAN_METHOD(New) {
    A *obj = new A();
    obj->Wrap(info.This());
    info.GetReturnValue().Set(info.This());
  }
};

class B : public ObjectWrap {
 public:
  static NAN_MODULE_INIT(Init) {
    v8::Local<v8::FunctionTemplate> tpl = Nan::New<v8::FunctionTemplate>(New);
    tpl->SetClassName(Nan::New("B").ToLocalChecked());
    tpl->InstanceTemplate()->SetInternalFieldCount(1);

    SetPrototypeMethod(tpl, "setA", SetAObj);
    constructor().Reset(Nan::GetFunction(tpl).ToLocalChecked());
    Set(target, Nan::New("B").ToLocalChecked(),
      Nan::GetFunction(tpl).ToLocalChecked());
  }

 private:
  ~B() {}
  A *a_obj;
  static Persistent<v8::Function> &constructor() {
    static Persistent<v8::Function> my_constructor;
    return my_constructor;
  }
  static NAN_METHOD(New) {
    B *obj = new B();
    obj->Wrap(info.This());
    info.GetReturnValue().Set(info.This());
  }
  static NAN_METHOD(SetAObj) {
    B *b_obj = ObjectWrap::Unwrap<B>(info.Holder());
    b_obj->a_obj = ObjectWrap::Unwrap<A>(info[0].As<v8::Object>());
  }
};

NAN_MODULE_INIT(Init) {
  A::Init(target);
  B::Init(target);
}
```

**Comment by jay11ca39** [comment]
I have tried the same and it worked. May be I messed up some code. [Working on nodejs and addon first time..:( ]
Thank you very much @kkoopa .
