### ISSUE TITLE
Question: how do I make handle-returning functions inline, safely?

### ISSUE THREAD

**Issue by wlzla000** [nodejs/nan#753]
How do I make handle-returning functions `inline` **_safely_**?
Assuming I'd like to make this function `inline`:

```cpp
v8::Local<v8::String> String(const char *c_string)
{
	Nan::EscapableHandleScope handle_scope;
	v8::Local<v8::String> h_string = Nan::New<v8::String>(c_string).ToLocalChecked();
	return handle_scope.Escape(h_string);
}
```

-----

```cpp
/*not-forced*/inline v8::Local<v8::String> String(const char *c_string)
{
	//  Is it okay to declare a `Nan::EscapableHandleScope`
	// if the compiler *succeeds* to inline this function?
	Nan::EscapableHandleScope handle_scope;
	v8::Local<v8::String> h_string = Nan::New<v8::String>(c_string).ToLocalChecked();
	return handle_scope.Escape(h_string);
}
```

```cpp
/*not-forced*/inline v8::Local<v8::String> String(const char *c_string)
{
	//  Is it safe not to declare a `Nan::EscapableHandleScope`
	// if the compiler *fails* to inline this function?
	v8::Local<v8::String> h_string = Nan::New<v8::String>(c_string).ToLocalChecked();
	return h_string;
}
```

```cpp
__attribute__((always_inline)) v8::Local<v8::String> String(const char *c_string)
{
	v8::Local<v8::String> h_string = Nan::New<v8::String>(c_string).ToLocalChecked();
	return h_string;
}
```

**Comment by kkoopa** [comment]
Wether the compiler inlines the function or not does not matter. Handles will always be registered with the innermost `HandleScope`. If you define a function which does not contain a `HandleScope`, created handles belong to the previous `HandleScope`. If a `HandleScope` does not exist and something attempts to create a handle, the process will terminate.

**Comment by wlzla000** [comment]
> If you define a function which does not contain a `HandleScope`, handles created in the function belong to the previous `HandleScope`.

I thought I have to declare a `HandleScope` in every functions that treats `Handle`s.
It seems so far I mistook the concept and misused `EscapableHandleScope`s.

Thank you for your answer.

**Comment by kkoopa** [comment]
The primary reason for using additional handle scopes is to prevent memory leaks. Until the owning scope is destroyed, the associated handles will keep their values alive, thus preventing the garbage collector from freeing memory. Keep in mind that the `v8::Handle` object itself is not directly known to the Javascript side. Destruction of a `v8::Handle` object does not directly affect the Javascript side, it is the destruction of the owning `HandleScope`  (or `EscapableHandleScope`) that enables garbage collection on its next run.
