### ISSUE TITLE
Nan::Callback weird behaviour after Nan::ThrowError

### ISSUE THREAD

**Issue by justadudewhohacks** [nodejs/nan#758]
Hi,

I am facing some weird issue, trying to invoke a callback after an error has been thrown with `Nan::ThrowError`. 

Given the following code:
``` c++
NAN_METHOD(MyFunc) {
  std::cout << "MyFunc" << std::endl;

  Nan::TryCatch tryCatch;
  if (info.Length() < 1 || !info[0]->IsFunction()) {
    Nan::ThrowError("callback expected");
    return;
  }

  std::cout << "has callback" << std::endl;
  Nan::Callback *callback = new Nan::Callback(info[0].As<v8::Function>());

  Nan::ThrowError("an error");

  v8::Local<v8::Value> argv[] = { Nan::Null(), Nan::Null() };
  callback->Call(2, argv);
  std::cout << "callback called" << std::endl;
}
```

Called with:
``` javascript
cv.myFunc(() => console.log('an error occured'))
```

Seems to result in an infinite recursive call of MyFunc:
```
MyFunc         
has callback   
callback called
MyFunc         
has callback   
callback called
MyFunc         
has callback   
callback called
...
```

I am kind of clueless why that is. Looks like the function pointer is now pointing to "MyFunc" instead of the callback? Any help is highly appreciated.

Thanks!

**Comment by agnat** [comment]
Not sure what's going on, but it is not "infinite recursion". Note that the last line of `MyFunc` _is_ executed _before_ starting over. So, `callback` doesn't point to `MyFunc`. The repetition is triggered externally, like in a loop.

A couple of things jump the eye:

1. You don't want a local `TryCatch`. You want these exceptions to reach JS.
1. Never continue execution after throwing an error. Always return immediately, like with your first exception.
1. There is a `new` but no `delete`.

On a side note, recursion is never infinite. The application will crash when the stack is exhausted, which usually happens pretty fast.

Hope this helps.

**Comment by justadudewhohacks** [comment]
Hi, thanks for the quick response.

The reason I am using a TryCatch is, because my intention is to catch an error that is being thrown under certain conditions, but I want to forward the error to the callback like this:

```
v8::Local<v8::String> formatCatchedError(Nan::TryCatch* tryCatch, std::string methodName) {
  return Nan::New(
    std::string(methodName)
    + std::string(" - ")
    + std::string(*Nan::Utf8String(tryCatch->Exception()->ToString()))
  ).ToLocalChecked();
}

NAN_METHOD(MyFunc) {
...
v8::Local<v8::Value> argv[] = { formatCatchedError(tryCatch, "MyFunc"), Nan::Null() };
callback->Call(2, argv);
}
```

> On a side note, recursion is never infinite.

Yes true, the thing what's strange is, that there is like 2 seconds delay between each recursive call and I don't know what's going on.

**Comment by justadudewhohacks** [comment]
Okay sorry I should have said that I am running this with mocha and the 2 seconds delay seems to be related to the mocha test timeout: `mocha --require ./globals --timeout 2000 --recursive ./tests`.

Running this with node actually calls the callback as expected.

I don't know what kind of strange evilness let's mocha rerun the unit test over and over again, but I fixed it by calling `tryCatch.Reset()` after throwing the error.

I guess clearing the Exception with `tryCatch.Reset()` is the preferred way to go in order to continue execution and pass the error message to the callback?

**Comment by agnat** [comment]
> I guess clearing the Exception with tryCatch.Reset() is the preferred way to go in order to continue execution and pass the error message to the callback?

To be honest, I'm not sure. I haven't used `TryCatch` in ages and I'm not familiar with the nan wrapper.

**Comment by kkoopa** [comment]
Should be the way. According to the docs, Reset cancels the exception: https://v8docs.nodesource.com/node-9.3/d4/dc6/classv8_1_1_try_catch.html#a372de693ad40b3f42839c8ec6ac845f4
