### ISSUE TITLE
PersistentBase.Reset does not take 1 argument

### ISSUE THREAD

**Issue by Spongman** [nodejs/nan#759]
https://github.com/nodejs/nan/blob/77d0046d4a8378a0cd31d8110130471b44c99d8d/test/cpp/accessors.cpp#L47

this doesn't build

**Comment by bnoordhuis** [comment]
Works for me.  It sounds like you're confusing `Nan::Persistent` with `v8::Persistent`.

**Comment by Spongman** [comment]
nope. definitely not.

even if i specify the namespace:
```c++
static Nan::Persistent<v8::FunctionTemplate> constructor_template;
...
constructor_template.Reset(Nan::New<FunctionTemplate>(New));
```

i still get the same error:
```
error C2660: 'v8::PersistentBase<T>::Reset': function does not take 1 arguments
```

please don't close bugs immediately. it's very rude.

**Comment by bnoordhuis** [comment]
Then file good bug reports.  The test you link to compiles just fine.  Wasting a maintainer's time, now that's rude.

**Comment by Spongman** [comment]
ok. please ignore this bug report. i'm sorry i ever wasted your time. it's obvious to me that you don't care a damn about people having issues with your project. obviously if it works on your machine, that's all that matters.

good day to you.

**Comment by bnoordhuis** [comment]
Sounds like you don't know who you're talking to; I helped more people than anyone on the Node.js project.  But you're right: if you don't care a damn to write a good bug report, then I don't care a damn either.

Google "how to write a good bug report" and take the results to heart, it'll help you in the future.

**Comment by bnoordhuis** [comment]
Hey, I have another helpful and caring tip for you.  Those big keys on both sides of your keyboard with the word "Shift" on them?  Did you know they're not just for decoration?  Try them, they're awesome and make you look smart!

**Comment by Spongman** [comment]
how old are you?

**Comment by bnoordhuis** [comment]
Old enough to know what a Shift key is for.  Also old enough to not cowardly delete my comments when the discussion doesn't go my way.

**Comment by agnat** [comment]
Right...

@Spongman, it definitely is a local issue on your machine. My gut feeling is your compiler grabs the wrong set of v8 headers. Look for messed up node installations, v8.h in global include directories and unused, superfluous node installations. That sort of thing...

That said, please reread your initial bug report. It literally provides _zero_ context. That _is_ a bit rude.

**Comment by bnoordhuis** [comment]
> My gut feeling is your compiler grabs the wrong set of v8 headers.

My money is on indiscriminate use of `using namespace`.

**Comment by agnat** [comment]
Or that!

**Comment by agnat** [comment]
No, can't be namespaces ... it happens in one of our tests ... it's the system, not the code

**Comment by bnoordhuis** [comment]
OP posted code (before he deleted it again) that wasn't from our test suite; the link to our `test/cpp/accessors.cpp` in the original message was a red herring.
