### ISSUE TITLE
FATAL ERROR: v8::HandleScope::CreateHandle() Cannot create a handle without a HandleScope with LevelDB in child thread

### ISSUE THREAD

**Issue by genisgetman** [nodejs/nan#800]
After i run levelDB in child thread(Node.js), i get the error as follow

```
FATAL ERROR: v8::HandleScope::CreateHandle() Cannot create a handle without a HandleScope
 1: 0x8b8210 node::Abort() [/usr/local/bin/node]
 2: 0x8b825c  [/usr/local/bin/node]
 3: 0xac1afa v8::Utils::ReportApiFailure(char const*, char const*) [/usr/local/bin/node]
 4: 0xe7fa37 v8::internal::HandleScope::Extend(v8::internal::Isolate*) [/usr/local/bin/node]
 5: 0xfad07c v8::internal::JSReceiver::GetCreationContext() [/usr/local/bin/node]
 6: 0xacafdc v8::Object::CreationContext() [/usr/local/bin/node]
 7: 0x8bb203 node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/usr/local/bin/node]
 8: 0x7f6fb050bc39 Nan::AsyncWorker::HandleOKCallback() [/home/denis/proj/plasma/dev-plasma/plasma1/Plasma-cash/client/node_modules/leveldown/build/Release/leveldown.node]
 9: 0x7f6fb050b983 Nan::AsyncWorker::WorkComplete() [/home/denis/proj/plasma/dev-plasma/plasma1/Plasma-cash/client/node_modules/leveldown/build/Release/leveldown.node]
10: 0x7f6fb050b3c5 Nan::AsyncExecuteComplete(uv_work_s*) [/home/denis/proj/plasma/dev-plasma/plasma1/Plasma-cash/client/node_modules/leveldown/build/Release/leveldown.node]
11: 0x9ee4d5  [/usr/local/bin/node]
12: 0x9f283f  [/usr/local/bin/node]
13: 0xa03718  [/usr/local/bin/node]
14: 0x9f317b uv_run [/usr/local/bin/node]
15: 0x8c2d95 node::Start(v8::Isolate*, node::IsolateData*, int, char const* const*, int, char const* const*) [/usr/local/bin/node]
16: 0x8c191f node::Start(int, char**) [/usr/local/bin/node]
17: 0x7f6fb2786830 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
18: 0x87dbe5  [/usr/local/bin/node]
Аварийный останов (сделан дамп памяти)
```

Please, any help for me? :C 
At least describe what happened 
google search does not give back a result

**Comment by agnat** [comment]
First, pretty sure this is not a nan bug. Unfortunately, there is not enough information in your bug report to help you. Reading your description it is not obvious to me what you are trying to do. We either need the source code or a much better description.

That said here is some wild guessing:

1. Node is inherently single threaded. It is a programming error to create any handle on a child thread.
1. If you are unfamiliar with handles and handle scopes, take a look at the [v8 embedder's guide](https://github.com/v8/v8/wiki/Embedder%27s-Guide).

I'm going to close this issue. If you have evidence that this _is_ a nan bug, just open a new one.

**Comment by genisgetman** [comment]
But in Node.js 10.5.0 be able to use 'worker-thread' module that included in node as default

**Comment by root1984** [comment]
I got the same bug too, I'm running nodejs 12.13.0 and when I call Google Api with Protobuf (may relate with C++ native layer), OS is Windows 10.

`FATAL ERROR: v8::HandleScope::CreateHandle() Cannot create a handle without a HandleScope
 1: 00007FF66DBE094F napi_wrap+124431
 2: 00007FF66DB82696 v8::base::CPU::has_sse+34502
 3: 00007FF66DB83356 v8::base::CPU::has_sse+37766
 4: 00007FF66E386EBC v8::FunctionTemplate::RemovePrototype+284
 5: 00007FF66E26DB95 v8::internal::HandleScope::Extend+53
 6: 00007FF66E0E6580 v8::internal::JSReceiver::GetCreationContext+288
 7: 00007FF66E36C030 v8::Object::CreationContext+32
 8: 00007FF66DBFCE58 node::MakeCallback+40
10: 00007FFE4005ED30
12: 00007FF66DC1FC42 uv_prepare_init+114
13: 00007FF66DC29426 uv_run+262
14: 00007FF66DB4B892 EVP_CIPHER_CTX_buf_noconst+30946
15: 00007FF66DBA9263 node::Start+275`
