### ISSUE TITLE
How to Free Memory for ObjectWrap Derived Classes in Parent-Child Relationships?

### ISSUE THREAD

**Issue by rbuck** [nodejs/nan#828]
I work at a SQL database company. I am writing a SQL driver for Node.js that wraps the C++ SQL API of our product.

I am having difficulty modeling the parent-child relationships between the objects; the relationships are as follows, including cardinalities:

```
Driver (1) ---- > (*) Connection (1)  ----> (0..1) ResultSet
```

Each of these classes inherit from ObjectWrap. Details for these include:

- Driver is a singleton object allocated globally in the index.js file provided with the module.
- Driver has an async method `connect(options, function(err, connection) { ... });`, this takes optional connection information such as username, password, etc, plus an error-first callback receiving the allocated Connection object
- Connection itself has an async method `execute(sql, function(err, results) { ... });`, the error first callback receives the result set.
- Connection itself has an async method `close(function(err) { ... });`, the method should cause the internal SQL connection state to be freed, and the Connection ObjectWrap derived class to be freed too.

Despite all attempts, whether using NAN or NAPI/C++ Addon APIs, the ResultSet object and the Connection objects NEVER get freed, and leak, leaking 16 GB memory in less than 10 minutes. The C++ destructors for classes inheriting from ObjectWrap NEVER get called.

I've scrounged the web, StackOverflow, node add on examples project, other DB driver projects, so many sources, but nowhere can I find information that seems to resolve the issues.

How does one model parent-child relationships with ObjectWrap and have the ObjectWrap instances freed when the user calls `close` on them, for example?

I shared out [my project on Github that illustrates this](https://github.com/rbuck/native-node-leaks). While this one is written using NAN, I have other examples written in NAPI (etc) that also have the exact same behavior (I abandoned NAPI b/c I found lots of use cases that trigger SEGVs inside NAPI, so I went back to NAN to get more stable behavior.

**Comment by bnoordhuis** [comment]
I've taken a quick look through your code and here are things that stood out to me:

1. I didn't see calls to `ObjectWrap::Wrap()`. The Wrap() method is what turns the object into a weak reference that's eligible for garbage collection (provided there are no strong references elsewhere.)

2. Call `Ref()` before you call `uv_queue_work()` and call `Unref()` in the after-work callback to keep the object alive while the work item is being processed.

`ObjectWrap` is basically a reference-counted weak pointer. It starts out with a reference count of 1; `Wrap()` and `Unref()` decrement the reference count, and `Ref()` increments it.

**Comment by rbuck** [comment]
Regarding `ObjectWrap::Wrap()`, are you talking about [the calls I have in `newInstance` here](https://github.com/rbuck/native-node-leaks/blob/master/src/NuoJsConnection.cpp#L51)?

**Comment by bnoordhuis** [comment]
Ah, right. Looking at that, you probably want to Ref() in newInstance() and Unref() in afterAsyncClose(). I'm assuming the connection object should stay alive as long as it's open.

I couldn't locate `Connection:createBaton()` but if it takes out a strong reference to the Connection object - and the Reset() call in `Connection::close()` appears to be doing that - you have a cycle that you need to break manually, unless the baton is itself a weak reference (but it doesn't look like it is.)

**Comment by rbuck** [comment]
These are the important details that clearly I am lacking. Thank you for responding, by the way. I really appreciate this. If you need something from me sometime, reach out, willing to help.

Back to the topic at hand...

The connection object (ObjectWrap instance) and the underlying SQL connection lifecycle are tied, and both should be released when `close` is called.

The [Baton class is located here](https://github.com/rbuck/native-node-leaks/blob/master/src/NuoJsBaton.cpp).

If I switch to using AsyncWorker solely, and avoid using the libuv code directly, would I need to call Unref in its `HandleOKCallback` handler of AsyncWorker? That is, your statements regarding `Ref` and `Unref` apply to pure NAN constructs (where I don't use libuv directly) as well?

(BTW, no examples I see online do any of this, and the model you see in my example is the Oracle model, which I decided to test, and itself leaks like a sieve. I'd like to get the model flawless so it runs perfectly clean under valgrind, which is wired into `make test` in the project.

In any of my three different attempts (of which were based upon: Addon C++, NAPI, NAN+libuv), all failed to release child objects. So, if I went with a simple parent-child model with straight NAN, in newInstance methods always Ref in newInstance, and Unref in HandleOKCallback?

By the way, in my baton class, its destructor has a persistent reference to the Driver, the async caller, and the callback. [In the Baton destructor it calls Reset](https://github.com/rbuck/native-node-leaks/blob/master/src/NuoJsBaton.cpp#L21):

```
    jsDriver.Reset(); // jsDriver is the singleton Driver object that never gets freed, btw
    jsCaller.Reset(); // when creating a result set, this would be the connection object, e.g.
    jsCallback.Reset();
```

**Comment by bnoordhuis** [comment]
> If I switch to using AsyncWorker solely, and avoid using the libuv code directly, would I need to call Unref in its HandleOKCallback handler of AsyncWorker?

If you call `AsyncWorker::SaveToPersistent(connection_obj)`, it'll maintain a strong reference to the connection object until the `AsyncWorker` instance is destructed. No need to Ref/Unref() in that case.

Ref/Unref() does have a small performance advantage but it's pretty marginal unless you have thousands upon thousands of objects. Weak objects are handled by a special GC post-processing pass. Fewer weak objects = less post-processing.

> I'd like to get the model flawless so it runs perfectly clean under valgrind

That's going to be hard because destructors are not guaranteed to run on exit because objects aren't reclaimed on exit, there is no final collect-all-the-things sweep.

If you need that kind of determinacy, take a look at `node::AtExit()`. There's no nan wrapper for it but the non-isolate overload of that method never changed after I added it in Node.js v0.10.0.

**Comment by rbuck** [comment]
It's not that I need strict determinacy, it's just that right now every time we call Connection.execute, what this really does is create a Statement object in the SQL database, and an associated ResultSet object. This means that if the destructors are never called, for as many objects as there are outstanding, there are open statements, which are limited to a max of 1000/connection.

I do need to know that if I cannot guarantee that the destructors are going to get called, ever, I need to find another way to model this. I need to ensure that at least the SQL objects are cleaned up when `close` is called, and if we cannot trust that destructors will get called at all, or get deferred to a later time, I need to move all the important cleanup code in the AsyncWorker background threads, and find a way to do reference management somehow, perhaps use std::shared_ptr myself with an internal tree of my own design that gets pruned on `close`.

**Comment by rbuck** [comment]
Net-net, if we can hold open this ticket till I get a working example. If I can get a simple parent-child relationship modeled and see the ObjectWrap class destructors fire even just once, at that point I'm good to go. It may take me a few days to get there.

**Comment by rbuck** [comment]
So I created another clean-room example following your recommendations. Same problems. None of the NAN objects ever get cleaned up by the GC (ever) and the process eventually OOMs.

Again, I see the exact same behavior with the Oracle driver, which also leaks like a sieve at a rate of at least 50 MB/sec, so I know it's not just me. Are there any simple examples people are aware of that model basic parent-child relationships, and provably eventually release objects (destructors are called). The user code should look something like this, and never leak:

```
for (;;) {
  database.connect(config, function (err, connection) { // connect allocates/opens a connection
    if (err) {
      console.error(err.message);
      return;
    }
    connection.close(function (err) { 
       // close should free the connection and eventually the objectwrap instance
      if (err) {
        console.error(err.message);
        return;
      }
    });
  });
}
```

I really need to see a concrete example on how to do this. I've yet to see an example that properly represents how to do this. And I'm about $60,000 into this with no useful results.

**Comment by rbuck** [comment]
So an update...

**One Hint**: What I am seeing is that objects that are created in JS such as `new MyThing` do get freed. But those that were allocated using a factory method do not.

So I'm working on the factory method right now, and I'm running into difficulty with it faulting... Consider the following:

```

Nan::Persistent<FunctionTemplate> Connection::constructor;

NAN_MODULE_INIT(Connection::init)
{
    TRACE("Connection::init");
    Nan::HandleScope scope;

    // prepare constructor template...
    Local<FunctionTemplate> tpl = Nan::New<FunctionTemplate>(Connection::newInstance);
    tpl->SetClassName(Nan::New("Connection").ToLocalChecked());
    tpl->InstanceTemplate()->SetInternalFieldCount(1);

    // prototypes...
    // Nan::SetPrototypeMethod(tpl, "destroy", destroy);

    // constructor.Reset(Nan::GetFunction(tpl).ToLocalChecked());
    constructor.Reset(tpl);
    // constructor.Reset(tpl->GetFunction());
    // target->Set(Nan::New("Connection").ToLocalChecked(), tpl->GetFunction());
    Nan::Set(target, Nan::New<v8::String>("Connection").ToLocalChecked(),
        tpl->GetFunction());

}
```
Elsewhere this will fault b/c template is empty? I'm just not sure why the template is empty, thoughts?

```...
Local<FunctionTemplate> tpl = Nan::New<FunctionTemplate>(Connection::constructor);

printf("tpl %s\n", tpl.IsEmpty() ? "true" : "false");  // << --- always returns true!

Nan::MaybeLocal<v8::Object> maybeInstance = Nan::NewInstance(cons);
v8::Local<v8::Object> wrapper;
if (maybeInstance.IsEmpty()) {
    Nan::ThrowError("Could not create new Connection instance");
} else {
    wrapper = maybeInstance.ToLocalChecked();
}
Nan::SetInternalFieldPointer(wrapper, 0, connection);
```

Does something look wrong here?
