### ISSUE TITLE
v8::StringObject::New(v8::Local<v8::String>&) is not available in latest v8-canary build

### ISSUE THREAD

**Issue by nolanmar511** [nodejs/nan#834]
I see the deprecation warnings are silenced where `v8::StringObject::New(v8::Local<v8::String>&)` is used ([here](https://github.com/nodejs/nan/blob/509859cc23b1770376b56550a027840a2ce0f73d/nan_implementation_12_inl.h#L356)). With the latest v8-canary release, this method is no longer available.

It would be awesome if it were possible to use nan in (some capacities) with v8-canary build!

**Comment by Flarna** [comment]
see #831

**Comment by kkoopa** [comment]
As mentioned in #831 it will not be merged quite yet, since more breaking changes might come, but if you check out that PR branch everything should work for now.

**Comment by nolanmar511** [comment]
I should mention, the module I work on might be a bit weird. It uses v8's profiling tools, so we like have a continuous e2e test which uses the v8-canary build, to try to find any problems that might occur in the profilers we use sooner.

I know this use case isn't really supported by NAN, but it's definitely nice when it works.

**Comment by kkoopa** [comment]
I was planning on holding out until the release of Node 12 or just before. While I suppose there is no greater harm in merging it earlier, that would still require pulling the master branch in place of the #831 branch.

**Comment by kkoopa** [comment]
Alright, it is merged.

**Comment by nolanmar511** [comment]
Thanks!
