### ISSUE TITLE
fatal error: node_version.h: No such file or directory

### ISSUE THREAD

**Issue by anoadragon453** [nodejs/nan#838]
So I've been trying to compile another library that indirectly makes use of `nan` and have been running into a compilation error:

```
[ 87%] Building CXX object CMakeFiles/iohook.dir/src/iohook.cc.o
In file included from /home/user/code/iohook/src/iohook.h:3,
                 from /home/user/code/iohook/src/iohook.cc:1:
/home/user/code/iohook/node_modules/nan/nan.h:24:10: fatal error: node_version.h: No such file or directory
 #include <node_version.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
```

I only run into this issue when compiling against Electron v4.x.x (v3.x.x has no errors) as have others in this issue: https://github.com/wilix-team/iohook/issues/144

Typically similar errors have been fixed by just updating `nan` in the past, but running on latest build (or indeed this repo's master branch) have resulted in the same problem. Something with it being unable to find node's headers for some reason?

If you any insight into what the problem might be that would be most appreciated!

**Comment by bnoordhuis** [comment]
node_version.h comes from the Node.js headers tarball, it's not provided by nan. node-gyp downloads it automatically for you but since you're not using that, you need to provide it yourself (somehow - you're in self-support waters here.)

**Comment by anoadragon453** [comment]
Hm, so perhaps electron provides this but isn't doing so in v4.x.x/the node version nan needs isn't the same as that supplied by electron v4.x.x?

**Comment by bnoordhuis** [comment]
It's possible; I don't know electron well enough to comment. I know its source tree bundles node and therefore contains a copy of node_version.h but I don't know how it works if all you have is its executable.

**Comment by anoadragon453** [comment]
Hrm, sounds like a problem I need to take the electron repo then. I'll leave this open for a little bit in case anyone pops in with a solution here. Thanks!

**Comment by bnoordhuis** [comment]
It looks like you received answers in the electron and iohook issues so I'll go ahead and close this out, cheers.
