### ISSUE TITLE
Nan::Maybe<T> ToChecked not implemented for Node.js 6.x

### ISSUE THREAD

**Issue by LinusU** [nodejs/nan#851]
I'm getting the following error when I fixing a warning that told me the return value of `Get` was unchecked.

```
../src/backend/ImageBackend.cc: In static member function ‘static void ImageBackend::Initialize(v8::Local<v8::Object>)’:
../src/backend/ImageBackend.cc:69:53: error: ‘Nan::Maybe<bool>’ has no member named ‘ToChecked’
            Nan::GetFunction(ctor).ToLocalChecked()).ToChecked();
```

https://github.com/Automattic/node-canvas/pull/1415 &bullet; [Travis CI jobs/526851510#L638](https://travis-ci.org/Automattic/node-canvas/jobs/526851510#L638)

Is this something that should be added to `nan_maybe_pre_43_inl.h`?

**Comment by bnoordhuis** [comment]
#852

**Comment by LinusU** [comment]
@kkoopa would love it if you could tag a release with this in ❤️ would like to get my PR to node-canvas moving forward 🐎
