### ISSUE TITLE
node: ../node_modules/nan/nan.h:822: Nan::MaybeLocal<v8::Object> Nan::NewBuffer(char*, size_t, node::Buffer::FreeCallback, void*): Assertion `length <= imp::kMaxLength &&  "too large buffer"' failed.

### ISSUE THREAD

**Issue by IrfanAli17899** [nodejs/nan#860]
node: ../node_modules/nan/nan.h:822: Nan::MaybeLocal<v8::Object> Nan::NewBuffer(char*, size_t, node::Buffer::FreeCallback, void*): Assertion `length <= imp::kMaxLength && 
"too large buffer"' failed.

it gives me this error when i am taking a large buffer from php to node over tcp . i am using zeromq for socket communication between node and php unfortunately i can not change the php server otherwise i might send data in chunks can anyone help me thanks in advance

**Comment by IrfanAli17899** [comment]
var express = require('express'); 
var app = express();
var fs = require('fs');


var options = {
key: fs.readFileSync('/etc/letsencrypt/live/run.sportsfier.com/privkey.pem'),
cert: fs.readFileSync('/etc/letsencrypt/live/run.sportsfier.com/fullchain.pem'),
ca: fs.readFileSync('/etc/letsencrypt/live/run.sportsfier.com/chain.pem')
};

var https = require('https').Server(options, app);

var zmq = require('zeromq')
, sock = zmq.socket('pull');
sock.bind('tcp://10.150.0.6:1010');

var io = require('socket.io')(https); 

io.on('connection', function(socket){ 

socket.on('disconnect',function(){
console.log("client disconnected");
})	


sock.on('message',function(msg){ 

console.log('work: %s', msg.toString());	
socket.emit('latest_score',msg.toString());

});

});

https.listen(2222);
sock.on('connect', function(fd, ep) {console.log('connect, endpoint:', ep);});

console.log('Worker connected to port 2222');

**Comment by bnoordhuis** [comment]
It's ultimately a V8 issue, NAN is just the messenger. Byte arrays cannot be > 1 GB.

You didn't show your C++ code but you'll have to work around that size limit.
