### ISSUE TITLE
pcl integration problem

### ISSUE THREAD

**Issue by HTLife** [nodejs/nan#867]
If I include
`find_package(PCL 1.7 REQUIRED)`
in `CMakeLists.txt` inside `nan/examples/async_pi_estimate/`
The following error will pop-up

```
[ 20%] Building CXX object CMakeFiles/addon.dir/src/addon.cc.o
In file included from /home/code/pcdviewer/server/addon/node_modules/nan/nan.h:54:0,
                 from /home/code/pcdviewer/server/addon/src/addon.cc:9:
/usr/include/python2.7/node.h:19:20: error: expected constructor, destructor, or type conversion before 'PyNode_New'
 PyAPI_FUNC(node *) PyNode_New(int type);
```
Is that the the `find_package` introduce some conflict?

**Comment by bnoordhuis** [comment]
Yes, but it's not a nan issue. Python's headers declare a type called `node` but that's also the namespace that Node's `node.h` uses. You basically can't mix the two inside a single compilation unit.

**Comment by HTLife** [comment]
@bnoordhuis I found a solution to avoid this issue.
Just make sure the line related to Node include variable 
```
target_include_directories(${PROJECT_NAME} PRIVATE ${CMAKE_JS_INC})
```
are placing before PCL's include statement.

Then the compiler will find the correct Node `node.h` and use it.
