### ISSUE TITLE
silently failing make

### ISSUE THREAD

**Issue by majioa** [nodejs/nan#884]
I'm trying to run make from the root pf the project but it is failed to lint the files silently:

    $ PYTHON=/usr/bin/python3 make
    cd ./ && /usr/bin/python3 .//cpplint.py --filter=-whitespace/parens examples/async_pi_estimate/addon.cc examples/async_pi_estimate/async.cc examples/async_pi_estimate/async.h examples/async_pi_estimate/pi_est.cc examples/async_pi_estimate/pi_est.h examples/async_pi_estimate/sync.cc examples/async_pi_estimate/sync.h nan.h nan_callbacks.h nan_callbacks_12_inl.h nan_callbacks_pre_12_inl.h nan_converters.h nan_converters_43_inl.h nan_converters_pre_43_inl.h nan_define_own_property_helper.h nan_implementation_12_inl.h nan_implementation_pre_12_inl.h nan_json.h nan_maybe_43_inl.h nan_maybe_pre_43_inl.h nan_new.h nan_object_wrap.h nan_persistent_12_inl.h nan_persistent_pre_12_inl.h nan_private.h nan_string_bytes.h nan_weak.h test/cpp/accessors.cpp test/cpp/accessors2.cpp test/cpp/asyncresource.cpp test/cpp/asyncworker.cpp test/cpp/asyncprogressworker.cpp test/cpp/asyncprogressworkerstream.cpp test/cpp/asyncprogressworkersignal.cpp test/cpp/asyncprogressqueueworker.cpp test/cpp/asyncprogressqueueworkerstream.cpp test/cpp/asyncworkererror.cpp test/cpp/buffer.cpp test/cpp/bufferworkerpersistent.cpp test/cpp/error.cpp test/cpp/gc.cpp test/cpp/indexedinterceptors.cpp test/cpp/callbackcontext.cpp test/cpp/converters.cpp test/cpp/isolatedata.cpp test/cpp/json-parse.cpp test/cpp/json-stringify.cpp test/cpp/makecallback.cpp test/cpp/maybe.cpp test/cpp/morenews.cpp test/cpp/multifile1.cpp test/cpp/multifile2.cpp test/cpp/multifile2.h test/cpp/namedinterceptors.cpp test/cpp/nancallback.cpp test/cpp/nannew.cpp test/cpp/news.cpp test/cpp/objectwraphandle.cpp test/cpp/persistent.cpp test/cpp/private.cpp test/cpp/returnemptystring.cpp test/cpp/returnnull.cpp test/cpp/returnundefined.cpp test/cpp/returnvalue.cpp test/cpp/setcallhandler.cpp test/cpp/settemplate.cpp test/cpp/sleep.h test/cpp/strings.cpp test/cpp/symbols.cpp test/cpp/threadlocal.cpp test/cpp/trycatch.cpp test/cpp/typedarrays.cpp test/cpp/weak.cpp test/cpp/weak2.cpp test/cpp/wrappedobjectfactory.cpp node_modules/node-gyp/gyp/data/win/large-pdb-shim.cc
    make: *** [Makefile:92: lint] Ошибка 1

How to fix it?

**Comment by bnoordhuis** [comment]
Try this: `make PYTHON=python2` - cpplint.py currently dies quietly with python 3.

**Comment by majioa** [comment]
We have not supported python2 already... (
