### ISSUE TITLE
Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by parmarmitesh** [nodejs/nan#893]
I am using npm version:- 6.14.5 and node version:- 12.16.1

Following are steps to build and test the nan package:

git clone https://github.com/nodejs/nan.git
npm install
npm test
After performing **npm test**, I am getting following **46 error,** so can you help me please in this or suggest me steps if I missing something.:

The errors are of similar type:

/nan/node_modules/bindings/bindings.js:91
  throw err
  ^

**Error: Could not locate the bindings file**. Tried:
 → /nan/test/build/wrappedobjectfactory.node
 → /nan/test/build/Debug/wrappedobjectfactory.node
 → /nan/test/build/Release/wrappedobjectfactory.node
 → /nan/test/out/Debug/wrappedobjectfactory.node
 → /nan/test/Debug/wrappedobjectfactory.node
 → /nan/test/out/Release/wrappedobjectfactory.node
 → /nan/test/Release/wrappedobjectfactory.node
 → /nan/test/build/default/wrappedobjectfactory.node
 → /nan/test/compiled/12.16.1/linux/ppc64/wrappedobjectfactory.node
    at bindings (/nan/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/nan/test/js/wrappedobjectfactory-test.js:11:37)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  tries: [
    '/nan/test/build/wrappedobjectfactory.node',
    '/nan/test/build/Debug/wrappedobjectfactory.node',
    '/nan/test/build/Release/wrappedobjectfactory.node',
    '/nan/test/out/Debug/wrappedobjectfactory.node',
    '/nan/test/Debug/wrappedobjectfactory.node',
    '/nan/test/out/Release/wrappedobjectfactory.node',
    '/nan/test/Release/wrappedobjectfactory.node',
    '/nan/test/build/default/wrappedobjectfactory.node',
    '/nan/test/compiled/12.16.1/linux/ppc64/wrappedobjectfactory.node'
  ]
}
not ok test/js/wrappedobjectfactory-test.js ............. 0/1
    Command: "/root/.nvm/versions/node/v12.16.1/bin/node --expose-gc wrappedobjectfactory-test.js"
    TAP version 13
    not ok 1 test/js/wrappedobjectfactory-test.js
      ---
        exit:    1
        stderr:  |
          /nan/node_modules/bindings/bindings.js:91
            throw err
            ^

          **Error: Could not locate the bindings file.** Tried:
           → /nan/test/build/wrappedobjectfactory.node
           → /nan/test/build/Debug/wrappedobjectfactory.node
           → /nan/test/build/Release/wrappedobjectfactory.node
           → /nan/test/out/Debug/wrappedobjectfactory.node
           → /nan/test/Debug/wrappedobjectfactory.node
           → /nan/test/out/Release/wrappedobjectfactory.node
           → /nan/test/Release/wrappedobjectfactory.node
           → /nan/test/build/default/wrappedobjectfactory.node
           → /nan/test/compiled/12.16.1/linux/ppc64/wrappedobjectfactory.node
              at bindings (/nan/node_modules/bindings/bindings.js:88:9)
              at Object.<anonymous> (/nan/test/js/wrappedobjectfactory-test.js:11:37)
              at Module._compile (internal/modules/cjs/loader.js:1158:30)
              at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
              at Module.load (internal/modules/cjs/loader.js:1002:32)
              at Function.Module._load (internal/modules/cjs/loader.js:901:14)
              at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
              at internal/main/run_main_module.js:18:47 {
            tries: [
              '/nan/test/build/wrappedobjectfactory.node',
              '/nan/test/build/Debug/wrappedobjectfactory.node',
              '/nan/test/build/Release/wrappedobjectfactory.node',
              '/nan/test/out/Debug/wrappedobjectfactory.node',
              '/nan/test/Debug/wrappedobjectfactory.node',
              '/nan/test/out/Release/wrappedobjectfactory.node',
              '/nan/test/Release/wrappedobjectfactory.node',
              '/nan/test/build/default/wrappedobjectfactory.node',
              '/nan/test/compiled/12.16.1/linux/ppc64/wrappedobjectfactory.node'
            ]
          }
        command: "/root/.nvm/versions/node/v12.16.1/bin/node --expose-gc wrappedobjectfactory-test.js"
      ...

    1..1
    # tests 1
    # fail  1

**Comment by agnat** [comment]
You have to build the test bindings first. Please take a look at the [README](https://github.com/nodejs/nan#tests).

**Comment by parmarmitesh** [comment]
I had gone With README document but while running command **npm run-script rebuild-tests**, I am getting following error.
 nan@2.14.1 rebuild-tests /nan
> node-gyp rebuild --msvs_version=2015 --directory test

gyp ERR! find Python
**gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON**
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/root/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (/root/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/root/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/root/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:310:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:322:5)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:469:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
gyp ERR! System Linux 4.4.0-179-generic
gyp ERR! command "/root/.nvm/versions/node/v12.16.1/bin/node" "/root/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--msvs_version=2015" "--directory" "test"
gyp ERR! cwd /nan/test
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nan@2.14.1 rebuild-tests: `node-gyp rebuild --msvs_version=2015 --directory test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nan@2.14.1 rebuild-tests script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-29T12_20_57_093Z-debug.log

**Comment by agnat** [comment]
Right. Bye.
