### ISSUE TITLE
cannot put the 4th AsyncProgressQueueWorker to AsyncQueueWorker

### ISSUE THREAD

**Issue by fw23t9** [nodejs/nan#900]
in my code I put less than 4 AsyncProgressQueueWorker  to AsyncQueueWorker, just like 
`class MyAsyncWorker1 : public AsyncProgressQueueWorker  
   ....
 MyAsyncWorker* pWorker1 = new MyAsyncWorker1(...);
AsyncQueueWorker(pWorker1)
`
the pWorker works well, 
but when I put the 4th AsyncWorker into AsyncQueueWorker, it doesn't work
what should I do if I need more than 4 AsyncWorkers?

**Comment by fivdi** [comment]
This may be related to the libuv thread pool size. The thread pool has a default size of 4 which can be changed using the `UV_THREADPOOL_SIZE ` environment variable. For further information see [here](http://docs.libuv.org/en/v1.x/threadpool.html).

**Comment by fw23t9** [comment]
> This may be related to the libuv thread pool size. The thread pool has a default size of 4 which can be changed using the `UV_THREADPOOL_SIZE ` environment variable. For further information see [here](http://docs.libuv.org/en/v1.x/threadpool.html).

it works! thank you very much!
