### ISSUE TITLE
nan is affected by the update to V8 8.9 in Node.js

### ISSUE THREAD

**Issue by targos** [nodejs/nan#909]
See https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2639/nodes=fedora-latest-x64/testReport/junit/(root)/citgm/nan_v2_14_2/

**Comment by Flarna** [comment]
Is this the v8 version which will be in Node 16? Or is it expected that there are more API changes till then?

**Comment by targos** [comment]
Not sure. We might still be able to update V8 once more before Node 16.
