### ISSUE TITLE
v8 Fast API with NAN.h

### ISSUE THREAD

**Issue by H4ad** [nodejs/nan#954]
It's possible to use [v8 Fast API](https://github.com/nodejs/node/blob/main/doc/contributing/adding-v8-fast-api.md) with NAN?

There are some libraries like [node-libpq](https://github.com/brianc/node-libpq/blob/master/src/connection.cc#L220-L229) that use NAN and return values that match with the requirements of Fast APIs, but I'm not sure if Fast APIs is supported outside the codebase of NodeJS.

**Comment by theweipeng** [comment]
> It's possible to use [v8 Fast API](https://github.com/nodejs/node/blob/main/doc/contributing/adding-v8-fast-api.md) with NAN?
> 
> There are some libraries like [node-libpq](https://github.com/brianc/node-libpq/blob/master/src/connection.cc#L220-L229) that use NAN and return values that match with the requirements of Fast APIs, but I'm not sure if Fast APIs is supported outside the codebase of NodeJS.

Fast APIs are not declared in NAN, so they are not accessible outside the codebase of Node.js. Fury JavaScript's use of fast APIs is an experimental test. 😁
