### ISSUE TITLE
Nan with Node 18

### ISSUE THREAD

**Issue by sanya-adobe** [nodejs/nan#972]
I am working on  a package which uses the latest version of "nan". Currently, I am on Node16 and everything works fine. There is a requirement to upgrade to Node18 but I am unable to do that as npm install gives the following error.

```
: note: 'SetAccessor' has been explicitly marked deprecated here
  V8_DEPRECATED("Do signature check in accessor")
```

The readme mentions that the package is compatible with Node 18. But I find that incorrect.
My setup : 
Node - v18.20.4
Npm - 10.7.0
MacOS machine

**Comment by agnat** [comment]
No discernible or actionable defect. I'm closing this.
