### ISSUE TITLE
crash app when call function export from Nan::Export

### ISSUE THREAD

**Issue by giangtran99** [nodejs/nan#980]
* Problem:
i try to use Nan::Export but when i call function export from Nan::Export, it cause crash app,
i debug nan_callbacks_12_inl.h and i see that error  occur at callstack function :

obj->GetInternalField(kFunctionIndex)
---I::GetInstanceType(obj);
----------ReadRawField<uint16_t>(map, kMapInstanceTypeOffset);

```
void FunctionCallbackWrapper(const v8::FunctionCallbackInfo<v8::Value> &info) {
  v8::Local<v8::Object> obj = info.Data().As<v8::Object>();
  FunctionCallback callback = reinterpret_cast<FunctionCallback>(
      reinterpret_cast<intptr_t>(
          obj->GetInternalField(kFunctionIndex) // -> error line
          .As<v8::Value>().As<v8::External>()->Value()));
  FunctionCallbackInfo<v8::Value>
      cbinfo(info, obj->GetInternalField(kDataIndex).As<v8::Value>());
  callback(cbinfo);
}
```

* Enviroment:
electronjs : 32.2.0
nan: 2.22.0
v8 : 12.8.374.36-electron.0
node : 20.18.0

**Comment by oopses** [comment]
Hi, how did you solve it in the end?

**Comment by giangtran99** [comment]
@oopses i use node-api module instead of nan module

Docs : https://nodejs.org/api/n-api.html
